{%- set run_date = "CURRENT_TIMESTAMP()" -%}


{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_erm_esr_data/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


select 
po_no,
expedite_hdr_no,
exh_po_no,
expedite_item_no,
expedite_occurrence,
supplementary_item_occurrence,
early_prom_contract_date,
early_forecast_del_date,
early_ros,
early_forecast_arri_on_site,
expli_po_item_no,
expli_mat_no,
poli_po_item_no,
poli_po_no,
project,
project_title,
purchase_order_no,
cust_po_no,
revision,
latest_client_revision,
issue_date,
line_item_count,
purchase_order_descr,
suppl_no,
supplier,
buyer_name,
expeditor,
inspector,
last_contact_date,
next_contact_date,
first_forecast_date,
last_forecast_date,
floats_earlros_firstforecast,
earliest_ros_date,
last_ros_date,
floats_lastros_lastforecast,
origin,
order_pos_sub,
shipment_pos_sub,
order_qty,
unit_id,
commopodity_code_tag_number,
tag_number,
s_item_no,
item_description,
mat_grp,
incoterm_delivery_place,
delivery_place,
site_id,
delivery_designation,
prom_contract_date,
forecast_delivery_date,
delays,
first_shipping_actual,
ros,
forecast_arrival_on_site,
floats,
arrival_on_site_actual,
receipt_status,
expedite_quan,
total_received_to_date,
outstanding_qty,
exp_hdr_comments,
proj_client_logo,
logo_file,
released_flg,
received_flg,
long_descr,
l_comments,
po_max_issue_ver,
po_max_issue_date,
po_first_issue_date,
qty_chk,
nxt_contact_date,
size1,
size2,
size3,
size4,
comnt,
hc_comnt,
sub_project,
srn_no,
srn_qty,
mmt_approved_date,
mrr_no,
mrr_date,
mrr_qty,
req_no,
gen_mto_cwp,
gen_att,
delivery_type,
mv.proj_no,
cvli.value as project_region ,
mv.etl_load_date,
{{run_date}} as model_created_date,
{{run_date}} as model_updated_date,
{{ generate_load_id(model) }} as model_load_id
from       {{ ref('transformed_esr_cext_w_exp_api_51005_new') }} mv  
left join  {{ source('curated_erm', 'proj_cpv') }} pc on mv.proj_no = pc.proj_no  AND pc.is_current = 1
left join  {{ source('curated_erm', 'cusp_value_list_item') }} cvli on pc.proj_region = cvli.value_list_item_no AND cvli.is_current = 1