{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False',
        custom_location=target.location ~ 'oracle_p6/transformed_p6_project/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["p6", "v2"]
        )
}}

SELECT 
activityid as activity_key,
activityid as activity_val_id,
activitydefaultactivitytype as activitydefaultactivitytype,
activitydefaultcalendarname as activitydefaultcalendarname,
activitydefaultcalendarobjectid as activitydefaultcalendarobjectid,
activitydefaultdurationtype as activitydefaultdurationtype,
activitydefaultpercentcompletetype as activitydefaultpercentcompletetype,
activitydefaultpriceperunit as activitydefaultpriceperunit,
activityidbasedonselectedactivity as activityidbasedonselectedactivity,
activityidincrement as activityidincrement,
activityidprefix as activityidprefix,
activityidsuffix as activityidsuffix,
activityowneruserid as activityowneruserid,
activitypercentcompletebasedonactivitysteps as activitypercentcompletebasedonactivitysteps,
actuallaborunits as actuallaborunits,
addactualtoremaining as addactualtoremaining,
addedby as addedby,
allownegativeactualunitsflag as allownegativeactualunitsflag,
allowstatusreview as allowstatusreview,
assignmentdefaultdrivingflag as assignmentdefaultdrivingflag,
assignmentdefaultratetype as assignmentdefaultratetype,
calculatefloatbasedonfinishdate as calculatefloatbasedonfinishdate,
cbscode as cbscode,
cbsid as cbsid,
checkoutstatus as checkoutstatus,
computetotalfloattype as computetotalfloattype,
containssummarydata as containssummarydata,
costquantityrecalculateflag as costquantityrecalculateflag,
createdate as createdate,
createuser as createuser,
criticalactivityfloatlimit as criticalactivityfloatlimit,
criticalactivityfloatthreshold as criticalactivityfloatthreshold,
criticalactivitypathtype as criticalactivitypathtype,
criticalfloatthreshold as criticalfloatthreshold,
currentbudget as currentbudget,
currentvariance as currentvariance,
datadate as datadate,
dateadded as dateadded,
defaultpricetimeunits as defaultpricetimeunits,
discountapplicationperiod as discountapplicationperiod,
distributedcurrentbudget as distributedcurrentbudget,
earnedvaluecomputetype as earnedvaluecomputetype,
earnedvalueetccomputetype as earnedvalueetccomputetype,
earnedvalueetcuservalue as earnedvalueetcuservalue,
earnedvalueuserpercent as earnedvalueuserpercent,
enableprimesycflag as enableprimesycflag,
enablepublication as enablepublication,
enablesummarization as enablesummarization,
etlinterval as etlinterval,
externalcrkey as externalcrkey,
externalearlystartdate as externalearlystartdate,
externallatefinishdate as externallatefinishdate,
feedback as feedback,
financialperiodtemplateid as financialperiodtemplateid,
fiscalyearstartmonth as fiscalyearstartmonth,
floatpath as floatpath,
floatpathorder as floatpathorder,
guid as guid,
hasfuturebucketdata as hasfuturebucketdata,
historyinterval as historyinterval,
historylevel as historylevel,
id as id,
ignoreotherprojectrelationships as ignoreotherprojectrelationships,
independentetclaborunits as independentetclaborunits,
independentetctotalcost as independentetctotalcost,
integratedtype as integratedtype,
integratedwbs as integratedwbs,
istemplate as istemplate,
lastapplyactualsdate as lastapplyactualsdate,
lastscheduledate as lastscheduledate,
lastupdatedate as lastupdatedate,
lastupdateuser as lastupdateuser,
levelallresources as levelallresources,
leveldateflag as leveldateflag,
levelfloatthresholdcount as levelfloatthresholdcount,
levelingpriority as levelingpriority,
levelouterassign as levelouterassign,
levelouterassignpriority as levelouterassignpriority,
leveloverallocationpercent as leveloverallocationpercent,
levelprioritylist as levelprioritylist,
levelresourcelist as levelresourcelist,
levelwithinfloat as levelwithinfloat,
limitmultiplefloatpaths as limitmultiplefloatpaths,
linkactualtoactualthisperiod as linkactualtoactualthisperiod,
linkpercentcompletewithactual as linkpercentcompletewithactual,
linkplannedandatcompletionflag as linkplannedandatcompletionflag,
locationname as locationname,
locationobjectid as locationobjectid,
makeopenendedactivitiescritical as makeopenendedactivitiescritical,
maximumduration as maximumduration,
maximummultiplefloatpaths as maximummultiplefloatpaths,
minimumduration as minimumduration,
mostlikelyduration as mostlikelyduration,
multiplefloatpathsenabled as multiplefloatpathsenabled,
multiplefloatpathsusetotalfloat as multiplefloatpathsusetotalfloat,
name as name,
notestoresources as notestoresources,
objectid as objectid,
obsname as obsname,
obsobjectid as obsobjectid,
originalbudget as originalbudget,
outofsequencescheduletype as outofsequencescheduletype,
overallprojectscore as overallprojectscore,
owneridarray as owneridarray,
ownernamesarray as ownernamesarray,
parentepsid as parentepsid,
parentepsname as parentepsname,
parentepsobjectid as parentepsobjectid,
plannedstartdate as plannedstartdate,
postrespcriticalityindex as postrespcriticalityindex,
postresponsepessimisticfinish as postresponsepessimisticfinish,
postresponsepessimisticstart as postresponsepessimisticstart,
prerespcriticalityindex as prerespcriticalityindex,
preresponsepessimisticfinish as preresponsepessimisticfinish,
preresponsepessimisticstart as preresponsepessimisticstart,
primaryconstraintdate as primaryconstraintdate,
primaryresourcescanmarkactivitiesascompleted as primaryresourcescanmarkactivitiesascompleted,
primaryresourcescanupdateactivitydates as primaryresourcescanupdateactivitydates,
project_id as project_id,
projectid as projectid,
projectscheduletype as projectscheduletype,
propertytype as propertytype,
proposedbudget as proposedbudget,
publicationpriority as publicationpriority,
publishlevel as publishlevel,
relationshiplagcalendar as relationshiplagcalendar,
resetplannedtoremainingflag as resetplannedtoremainingflag,
resourcecanbeassignedtosameactivitymorethanonce as resourcecanbeassignedtosameactivitymorethanonce,
resourcescanassignthemselvestoactivities as resourcescanassignthemselvestoactivities,
resourcescanassignthemselvestoactivitiesoutsideobsaccess as resourcescanassignthemselvestoactivitiesoutsideobsaccess,
resourcescaneditassignmentpercentcomplete as resourcescaneditassignmentpercentcomplete,
resourcescanmarkassignmentascompleted as resourcescanmarkassignmentascompleted,
resourcescanstaffroleassignment as resourcescanstaffroleassignment,
resourcescanviewinactiveactivities as resourcescanviewinactiveactivities,
resumedate as resumedate,
reviewfinishdate as reviewfinishdate,
reviewtype as reviewtype,
riskexposure as riskexposure,
risklevel as risklevel,
riskscore as riskscore,
scheduledfinishdate as scheduledfinishdate,
schedulewbshierarchytype as schedulewbshierarchytype,
secondaryconstraintdate as secondaryconstraintdate,
source_system_name as source_system_name,
startdate as startdate,
starttostartlagcalculationtype as starttostartlagcalculationtype,
status as status,
strategicpriority as strategicpriority,
summarizeresourcesrolesbywbs as summarizeresourcesrolesbywbs,
summarizetowbslevel as summarizetowbslevel,
summarylevel as summarylevel,
summaryunitspercentcomplete as summaryunitspercentcomplete,
suspenddate as suspenddate,
taskstatusindicator as taskstatusindicator,
teammemberactivityfields as teammemberactivityfields,
teammemberassignmentoption as teammemberassignmentoption,
teammemberdisplaydiscussionsflag as teammemberdisplaydiscussionsflag,
teammemberincludeprimaryresources as teammemberincludeprimaryresources,
teammemberresourceassignmentfields as teammemberresourceassignmentfields,
teammemberstepsadddeletable as teammemberstepsadddeletable,
totalbenefitplan as totalbenefitplan,
totalbenefitplantally as totalbenefitplantally,
totalspendingplan as totalspendingplan,
totalspendingplantally as totalspendingplantally,
unallocatedbudget as unallocatedbudget,
undistributedcurrentvariance as undistributedcurrentvariance,
useexpectedfinishdates as useexpectedfinishdates,
useprojectbaselineforearnedvalue as useprojectbaselineforearnedvalue,
wbscodeseparator as wbscodeseparator,
wbsmilestonepercentcomplete as wbsmilestonepercentcomplete,
wbsobjectid as wbsobjectid,
workpackageid as workpackageid,
cast(null as string) as workpackagename,
cast(execution_date as date),
{{run_date}} as created_date,
{{run_date}} as updated_date,
{{ generate_load_id(model) }} as load_id
FROM
{{ source('curated_p6', 'curated_project') }}
