dbt_project_control:
    target: dev
    outputs:
        dev:
            type: glue
            query-comment: dbt-glue-project_control
            role_arn: "arn:aws:iam::891377181979:role/worley-datalake-sydney-dev-iam-service-role-glue"
            region: ap-southeast-2
            glue_version: "5.0"
            workers: 8
            worker_type: G.4X
            schema: "worley_datalake_sydney_dev_glue_catalog_database_project_control_transformed"
            database: "worley_datalake_sydney_dev_glue_catalog_database_project_control_transformed"
            session_provisioning_timeout_in_seconds: 120
            location: "s3://worley-datalake-sydney-dev-bucket-transformed-xd5ydg/project_control/"
            datalake_formats: iceberg
            security_configuration: "worley_datalake_sydney_dev_glue_security_configuration_kms"
            glue_session_id: "dbt_project_control_transformed_load_session"
            glue_session_reuse: false
            connections: "worley-datalake-sydney-dev-glue-connection-2"
            conf: >
                spark.sql.defaultCatalog=glue_catalog
                --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog
                --conf spark.sql.catalog.glue_catalog.warehouse="s3://worley-datalake-sydney-dev-bucket-transformed-xd5ydg/project_control/warehouse/"
                --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
                --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
                --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
                --conf spark.sql.legacy.timeParserPolicy=LEGACY
            default_arguments: "--enable-metrics=true, --enable-continuous-cloudwatch-log=true, --enable-continuous-log-filter=true, --enable-auto-scaling=true"

        qa:
            type: glue
            query-comment: dbt-glue-project_control
            role_arn: "arn:aws:iam::533267239288:role/worley-datalake-sydney-qa-iam-service-role-glue"
            region: ap-southeast-2
            glue_version: "5.0"
            workers: 8
            worker_type: G.4X
            schema: "worley_datalake_sydney_qa_glue_catalog_database_project_control_transformed"
            database: "worley_datalake_sydney_qa_glue_catalog_database_project_control_transformed"
            session_provisioning_timeout_in_seconds: 120
            location: "s3://worley-datalake-sydney-qa-bucket-transformed-k7eatg/project_control/"
            datalake_formats: iceberg
            security_configuration: "worley_datalake_sydney_qa_glue_security_configuration_kms"
            glue_session_id: "dbt_project_control_transformed_load_session"
            glue_session_reuse: false
            connections: "worley-datalake-sydney-qa-glue-connection-2"
            conf: >
                spark.sql.defaultCatalog=glue_catalog
                --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog
                --conf spark.sql.catalog.glue_catalog.warehouse="s3://worley-datalake-sydney-qa-bucket-transformed-k7eatg/project_control/warehouse/"
                --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
                --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
                --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
                --conf spark.sql.legacy.timeParserPolicy=LEGACY
            default_arguments: "--enable-metrics=true, --enable-continuous-cloudwatch-log=true, --enable-continuous-log-filter=true, --enable-auto-scaling=true"
            
