{{ config(materialized='table') }}


SELECT DISTINCT
    activityactualfinish,
    activityid,
    activityname,
    activityobjectid,
    activitytype,
    actualcost,
    actualcurve,
    actualduration,
    actualfinishdate,
    actualovertimecost,
    actualovertimeunits,
    actualregularcost,
    actualregularunits,
    actualstartdate,
    actualthisperiodcost,
    actualthisperiodunits,
    actualunits,
    assignmentpercentcomplete,
    atcompletioncost,
    atcompletionduration,
    atcompletionunits,
    autocomputeactuals,
    budgetatcompletioncosts,
    budgetatcompletionunits,
    cbscode,
    cbsid,
    calendarname,
    calendarobjectid,
    costaccountid,
    costaccountname,
    costaccountobjectid,
    createdate,
    createuser,
    drivingactivitydatesflag,
    durationpercentcomplete,
    estimatetocompletioncosts,
    estimatetocompletionunits,
    financialperiodtmplid,
    finishdate,
    guid,
    hasfuturebucketdata,
    isactive,
    isactivityflagged,
    isbaseline,
    iscostunitslinked,
    isovertimeallowed,
    isprimaryresource,
    istemplate,
    lastupdatedate,
    lastupdateuser,
    objectid,
    overtimefactor,
    pendingactualovertimeunits,
    pendingactualregularunits,
    pendingpercentcomplete,
    pendingremainingunits,
    percentcomplete,
    percentcompletetype,
    plannedcost,
    plannedcurve,
    plannedduration,
    plannedfinishdate,
    plannedlag,
    plannedstartdate,
    plannedunits,
    plannedunitspertime,
    priceperunit,
    prioractualovertimeunits,
    prioractualregularunits,
    proficiency,
    projectflag,
    project_id,
    projectname,
    projectobjectid,
    projectprojectflag,
    ratesource,
    ratetype,
    remainingcost,
    remainingcurve,
    remainingduration,
    remainingfinishdate,
    remaininglag,
    remaininglatefinishdate,
    remaininglatestartdate,
    remainingstartdate,
    remainingunits,
    remainingunitspertime,
    resourcecalendarname,
    resourcecurvename,
    resourcecurveobjectid,
    resourceid,
    resourcename,
    resourceobjectid,
    resourcetype,
    reviewrequired,
    roleid,
    rolename,
    roleobjectid,
    roleshortname,
    staffedremainingcost,
    staffedremainingunits,
    startdate,
    statuscode,
    totalpastperiodcost,
    totalpastperiodunits,
    unitspercentcomplete,
    unreadcommentcount,
    unstaffedremainingcost,
    unstaffedremainingunits,
    wbsnamepath,
    wbsobjectid,
    projectid,
    execution_date
--    is_current
FROM 
(
    SELECT DISTINCT
        *,
        ROW_NUMBER() OVER (PARTITION BY objectid order by execution_date DESC) as rownum
    FROM 
    {{ source('curated_vg_p6', 'curated_project_resourceassignment') }}

    WHERE -- is_current = 1  and 
    projectobjectid = projectid
) t
WHERE rownum = 1