{{ config(materialized='table') }}

Select 
	SECORG,
	PROJECT as ProjectNumber,
	PROJECTINTERNALID,
	SYSTEMDATE,
	CAID as CA_ID,
	CAINTERNALID,
	MAJORPERIOD as MajorPeriod,
	MINORPERIOD as MinorPeriod,
	OHOURS as Original_Budget_Hours,
	BHOURS as Current_Budget_Hours,
	CHOURS as ChangedHours,
	PENDINGCHGHOURS as PendingVariations_Hrs,
	PENDINGBGTHOURS as Pending_Budget_Hrs,
	AHOURS as ActualHours,
	EHOURS as Earned_Value_Hours,
	FTCHOURS as ETC_Hrs,
	FACHOURS as EAC_Hours,
	OCOST as Original_Budget_Cost,
	BCOST as Current_Budget_Cost,
	CCOST as ChangedCost,
	PENDINGCHGCOST as PendingVariations_Cost,
	PENDINGBGTCOST as Pending_Budget_Cost,
	ACOST as ActualCost,
	ECOST as Earned_Value_Cost,
	FTCCOST as ETC_Cost,
	FACCOST as EAC_Cost,
	OSELL as Original_Budget_Rev,
	BSELL as Current_Budget_Rev,
	CSELL as ChangedSell,
	PENDINGCHGSELL as PendingVariations_Sell,
	PENDINGBGTSELL as Pending_Budget_Revenue,
	ASELL as ActualRev,
	ESELL as Earned_Value_Rev,
	FTCSELL as ETC_Rev,
	FACSELL as EAC_Rev,
	COMMITTEDCOST,
	COMMITTEDSELL,
	CA,
	BILLABLEYESNOID as BillCode,
	CODEOFACCOUNTIDNAME as CodeOfAccount,
	COSTTYPEID as CostType,
	COSTTYPEINTERNALID as Cost_Type_Internal_ID,
    'NULL' as AbsoluteETCHrs,
    'NULL' as AbsoluteETCRev,
    'NULL' as Datecreated       
 From {{ source('curated_vg_ecosys', 'curated_timephased') }}