SELECT
    project_id,
    projectname,
    projectobjectid,
    cast(projectdatadate as date) as projectdatadate,
    activityid,
    '' as billcode,
    '' as codeofaccount,
    '' as areacode,
    activityobjectid,
    activityname,
    activity_type,
    activity_status,
    activity_wbsname,
    activity_wbspath,
    activity_wbsnamepath,
    activity_wbscode,
    activity_actualstartdate,
    activity_actualfinishdate,
    activity_plannedstartdate,
    activity_plannedfinishdate,
    activity_baselinestartdate,
    activity_baselinefinishdate,
    activity_remaininglatestartdate,
    activity_remaininglatefinishdate,
    activity_remainingearlystartdate,
    activity_remainingearlyfinishdate,
    activity_earlystartdate,
    activity_earlyfinishdate,
    activity_latestartdate,
    activity_latefinishdate_activty,
    activity_schedulevariance,
    activity_floatpath,
    activity_floatpathorder,
    activity_freefloat,
    activity_totalfloat,
    activity_plannedlaborunits,
    activity_baselineplannedlaborunits,
    activity_remainingduration,
    activity_startdate,
    activity_finishdate,
    activity_baselineduration,
    activity_plannedduration,
    activity_finishdatevariance,
    activity_datadate,
    activitycodeconcatname,
    activitycodedescription,
    activitycodetypescope,
    activitycodetypename,
    activitycodevalue,
    resource_id,
    resourcename,
    resourcetype,
    resourceassignmentobjectid,
    --cast(period_startdate as date) as period_startdate,
    cast(period_enddate as date) as period_enddate,
    plannedunits,
    '0' as etc_hrs,
    pcs.cost_object_category_value_id,
    pcs.cost_object_category_value_name,
    pcs.parent_category_id,
    pcs.cost_type_pcs_map_id,
    pcs.parent_cost_type_pcs_map_id,
    pcs.display_name,
    pcs.library,
    pcs.level_1_description,
    pcs.level_2_description,
    pcs.level_3_description,
    pcs.level_4_description,
    pcs.level_5_description,
    'P6' as source
FROM
    {{ref('fact_p6_plan_obt_many')}} p6
        --   vg_analytics.fact_p6_plan_obt_many p6
left join {{ref('dim_ecosys_cost_type_pcs_mapping_list')}} pcs
-- vg_analytics.dim_ecosys_cost_type_pcs_mapping_list pcs
          on p6.costtypeid = pcs.cost_object_category_value_id
where period_enddate is not null

union all

SELECT
    projectnumber,
    secorg,
    projectinternalid,
    cast(systemdate as date) as systemdate,
    ca_id,
    billcode,
    codeofaccount,
    areacode,
    null as activityobjectid,
    null as activityname,
    null as activity_type,
    null as activity_status,
    null as activity_wbsname,
    null as activity_wbspath,
    null as activity_wbsnamepath,
    null as activity_wbscode,
    cast(null as date) as activity_actualstartdate,
    cast(null as date) as activity_actualfinishdate,
    cast(null as date) as activity_plannedstartdate,
    cast(null as date) as activity_plannedfinishdate,
    cast(null as date) as activity_baselinestartdate,
    cast(null as date) as activity_baselinefinishdate,
    cast(null as date) as activity_remaininglatestartdate,
    cast(null as date) as activity_remaininglatefinishdate,
    cast(null as date) as activity_remainingearlystartdate,
    cast(null as date) as activity_remainingearlyfinishdate,
    cast(null as date) as activity_earlystartdate,
    cast(null as date) as activity_earlyfinishdate,
    cast(null as date) as activity_latestartdate,
    null as activity_latefinishdate_activty,
    null as activity_schedulevariance,
    null as activity_floatpath,
    null as activity_floatpathorder,
    null as activity_freefloat,
    null as activity_totalfloat,
    null as activity_plannedlaborunits,
    null as activity_baselineplannedlaborunits,
    null as activity_remainingduration,
    cast(null as date) as activity_startdate,
    cast(null as date) as activity_finishdate,
    null as activity_baselineduration,
    null as activity_plannedduration,
    null as activity_finishdatevariance,
    cast(null as date) as activity_datadate,
    null as activitycodeconcatname,
    null as activitycodedescription,
    null as activitycodetypescope,
    null as activitycodetypename,
    null as activitycodevalue,
    null as resource_id,
    null as resourcename,
    null as resourcetype,
    null as resourceassignmentobjectid,
    --cast(majorperiod as date) as majorperiod ,
    cast(minorperiod as date) as minorperiod,
    '0' as plannedunits,
    etc_hrs,
    cost_object_category_value_id,
    cost_object_category_value_name,
    parent_category_id,
    cost_type_pcs_map_id,
    parent_cost_type_pcs_map_id,
    display_name,
    library,
    level_1_description,
    level_2_description,
    level_3_description,
    level_4_description,
    level_5_description,
    'ECOSYS' as source
FROM {{ref('fact_ecosys_timephased_obt')}};
-- vg_analytics.fact_ecosys_timephased_obt