dbt_supply_chain:
    target: dev
    outputs:
        dev:
            type: glue
            query-comment: dbt-glue-supply-chain
            role_arn: "arn:aws:iam::891377181979:role/worley-datalake-sydney-dev-iam-service-role-glue"
            region: ap-southeast-2
            glue_version: "5.0"
            workers: 8
            worker_type: G.4X
            schema: "worley_datalake_sydney_dev_glue_catalog_database_supply_chain_transformed"
            database: "worley_datalake_sydney_dev_glue_catalog_database_supply_chain_transformed"
            session_provisioning_timeout_in_seconds: 300
            idle_timeout: 60
            location: "s3://worley-datalake-sydney-dev-bucket-transformed-xd5ydg/supply_chain/"
            datalake_formats: iceberg
            security_configuration: "worley_datalake_sydney_dev_glue_security_configuration_kms"
            glue_session_id: "dbt_supply_chain_transformed_load_session"
            glue_session_reuse: true
            connections: "worley-datalake-sydney-dev-glue-connection-2"
            conf: >
                spark.sql.defaultCatalog=glue_catalog 
                --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog 
                --conf spark.sql.catalog.glue_catalog.warehouse="s3://worley-datalake-sydney-dev-bucket-transformed-xd5ydg/supply_chain/warehouse/" 
                --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog 
                --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO 
                --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
                --conf spark.sql.legacy.timeParserPolicy=LEGACY
            default_arguments: "--enable-metrics=true, --enable-continuous-cloudwatch-log=true, --enable-continuous-log-filter=true, --enable-auto-scaling=true"

        qa: 
            type: glue
            query-comment: dbt-glue-supply-chain
            role_arn: "arn:aws:iam::533267239288:role/worley-datalake-sydney-qa-iam-service-role-glue"
            region: ap-southeast-2
            glue_version: "5.0"
            workers: 8
            worker_type: G.4X
            schema: "worley_datalake_sydney_qa_glue_catalog_database_supply_chain_transformed"
            database: "worley_datalake_sydney_qa_glue_catalog_database_supply_chain_transformed"
            session_provisioning_timeout_in_seconds: 300
            idle_timeout: 60
            location: "s3://worley-datalake-sydney-qa-bucket-transformed-k7eatg/supply_chain/"
            datalake_formats: iceberg
            security_configuration: "worley_datalake_sydney_qa_glue_security_configuration_kms"
            glue_session_id: "dbt_supply_chain_transformed_load_session"
            glue_session_reuse: true
            connections: "worley-datalake-sydney-qa-glue-connection-2"
            conf: >
                spark.sql.defaultCatalog=glue_catalog 
                --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog 
                --conf spark.sql.catalog.glue_catalog.warehouse="s3://worley-datalake-sydney-qa-bucket-transformed-k7eatg/supply_chain/warehouse/" 
                --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog 
                --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO 
                --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
                --conf spark.sql.legacy.timeParserPolicy=LEGACY
            default_arguments: "--enable-metrics=true, --enable-continuous-cloudwatch-log=true, --enable-continuous-log-filter=true, --enable-auto-scaling=true"
            
            
        prd:
            type: glue
            query-comment: dbt-glue-supply-chain
            role_arn: "arn:aws:iam::471112986846:role/worley-datalake-sydney-prd-iam-service-role-glue"
            region: ap-southeast-2
            glue_version: "5.0"
            workers: 8
            worker_type: G.4X
            schema: "worley_datalake_sydney_prd_glue_catalog_database_supply_chain_transformed"
            database: "worley_datalake_sydney_prd_glue_catalog_database_supply_chain_transformed"
            session_provisioning_timeout_in_seconds: 300
            idle_timeout: 60
            location: "s3://worley-datalake-sydney-prd-bucket-transformed-cuyglg/supply_chain/"
            datalake_formats: iceberg
            security_configuration: "worley_datalake_sydney_prd_glue_security_configuration_kms"
            glue_session_id: "dbt_supply_chain_transformed_load_session"
            glue_session_reuse: true
            connections: "worley-datalake-sydney-prd-glue-connection-2"
            conf: >
                spark.sql.defaultCatalog=glue_catalog 
                --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog 
                --conf spark.sql.catalog.glue_catalog.warehouse="s3://worley-datalake-sydney-prd-bucket-transformed-cuyglg/supply_chain/warehouse/" 
                --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog 
                --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO 
                --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
                --conf spark.sql.legacy.timeParserPolicy=LEGACY
            default_arguments: "--enable-metrics=true, --enable-continuous-cloudwatch-log=true, --enable-continuous-log-filter=true, --enable-auto-scaling=true"