{{
     config(
         materialized = "table",
         tags=["supply_chain"]
     )

}}

SELECT DISTINCT
    proj_no as Project_No,
    project as Project_ID,
    req_no as TMR_Number,
    purchase_order_no as PO_Number,
    cust_po_no as Customer_PO,
    revision as Latest_Rev,
    tag_number as Tag_Number,
    supplier as Supplier,
    expeditor as Expediter,
    purchase_order_descr as Description,
    item_description as Item_Description,
    order_qty as Order_Qty,
    outstanding_qty as Outstanding_Qty,
    incoterm_delivery_place as Incoterm,
    delivery_place as Delivery_Location,
    delivery_designation as Delivery_Site,
    po_first_issue_date as PO_1st_Issue,
    next_contact_date as Next_Contact_Date,
    prom_contract_date as Contract_Delivery_Date,
    forecast_delivery_date as Forecast_Delivery_Date,
    issue_date as Latest_Issue_Date,
    forecast_arrival_on_site as Forecast_Arrival_On_Site,
    ros as Exp_ROS,
    floats as ROS_Float,
    delays as Delivery_Float,
    line_item_count as Total_Exp_Items,
    comnt as Expediting_Comments,
    project_region as Project_Region,
    buyer_name as Buyer,
    commopodity_code_tag_number as CommodityCode,
    gen_mto_cwp as CWP,
    delivery_type as Delivery_Type,
    early_prom_contract_date as Earliest_Contract_Delivery_Date,
    early_forecast_arri_on_site as Earliest_Forecast_Arrival_Date,
    early_forecast_del_date as Earliest_Forecast_Delivery_Date,
    earliest_ros_date as Earliest_ROS,
    expedite_occurrence as EO,
    expedite_quan as Exp_Qty,
    first_shipping_actual as First_Shipping_Actual,
    gen_att as General_Attribute,
    inspector as Inspector,
    l_comments as Item_Comments,
    s_item_no as ItemNo,
    last_contact_date as Last_Contact_Date,
    mrr_date as MRR_Date,
    mrr_no as MRR_Number,
    mrr_qty as MRR_Qty,
    order_pos_sub as Order_Position,
    size1 as Size1,
    size2 as Size2,
    size3 as Size3,
    supplementary_item_occurrence as SO,
    mmt_approved_date as SRN_Date,
    srn_no as SRN_No,
    srn_qty as SRN_Qty,
    sub_project as SubProject,
    total_received_to_date as Total_Received,
    unit_id as UOM,
    arrival_on_site_actual as Arrival_On_Site_Actual,
    etl_load_date as dataset_refershed_date
FROM
    {{ source('supply_chain_dim', 'erm_esr_data') }}
