version: 2

sources:
  - name: curated_p6
    tags: ["p6","v2"]
    schema: "{{ var('curated_p6_schema').get(target.name,'v2') }}"
    tables:
      - name: curated_activitycode
      - name: curated_activitycodetype
      - name: curated_eps
      - name: curated_project
      - name: curated_project_activity
      - name: curated_project_activitycode
      - name: curated_project_activitycodeassignment
      - name: curated_project_activitycodetype
      - name: curated_project_activityspread
      - name: curated_project_resourceassignment
      - name: curated_project_resourceassignmentspread
      - name: curated_project_udfvalue
      - name: curated_project_relationship
      - name: curated_resource
      - name: curated_udftype

  - name: curated_ecosys
    tags: ["ecosys","v2"]
    schema: "{{ var('curated_ecosys_schema').get(target.name,'v2')}}"
    tables:
      - name: curated_ecosys_progress_category
      - name: curated_ecosys_status
      - name: curated_ecosys_cost
      - name: curated_ecosys_global_phases
      - name: curated_ecosys_global_locations
      - name: curated_ecosys_service_type
      - name: curated_ecosys_org_access
      - name: curated_ecosys_costtypepcsmapping
      - name: curated_ecosys_calendar
      - name: curated_ecosys_cost_category
      - name: curated_ecosys_ecodata
      - name: curated_ecosys_gross_margin_category
      - name: curated_header
      - name: curated_ecosys_hours_category
      - name: curated_ecosys_revenue_category
      - name: curated_ecosys_users
      - name: curated_ecosys_snapidlist
      - name: curated_ecosys_usersecorg
      - name: curated_ecosys_secorglist
      - name: curated_ecosys_snapshotlog
      - name: curated_gate_data
      - name: curated_dcs_mapping  
      - name: curated_ecosys_snapshotfull
      - name: curated_ecosys_findata
      - name: curated_ecosys_findatapcs
      - name: curated_ecosys_budget_grid_cols
      - name: curated_ecosys_budget_grid_rows
      - name: curated_ecosys_data_type_switch
      - name: curated_ecosys_invoice_due_categories
      - name: curated_ecosys_progress_type
      - name: curated_ecosys_revenue_at_risk
      - name: curated_ecosys_project_risks
      - name: curated_ecosys_project_sizes
      - name: curated_ecosys_exchange_rates
      - name: curated_ecosys_projectkeymembers
      - name: curated_project_list
      - name: curated_control_account
      - name: curated_ecosys_userproject
      - name: ecosys_finance_contingency
      - name: ecosys_finance_outstanding
      - name: curated_timephased
      - name: curated_change_deliverable
      - name: curated_control_account_snapshot
      - name: curated_deliverable
      - name: curated_deliverable_gate
      - name: curated_deliverable_source
      - name: curated_ecosys_archival
      - name: curated_ecosys_actuallog
      - name: curated_ecosys_earnedvaluelog
      - name: curated_ecosys_workingforecastlog
      - name: curated_ecosys_our_dates
