version: 2


sources:
  - name: curated_e3d
    schema: "{{ var('curated_schema')[target.name] }}"
    tables:
      - name: curated_dim_memstatus
      - name: curated_vg_e3d_vglequip_sheet
      - name: curated_vg_e3d_vglpipes_sheet
      - name: curated_vg_e3d_vglstruc_sheet
      - name: curated_elecequilistrep
      - name: curated_electraywbsrep
      - name: curated_vg_e3d_vglfloor_sheet
      - name: curated_vg_e3d_vglgensec_sheet
      - name: curated_instequiwbseep
      - name: curated_pipecompwbsrep
      - name: curated_pipelistrep
      - name: curated_vg_e3d_vglpipesupport_sheet
      - name: curated_strcbeamwbsrep
      - name: curated_strcfdnswbsrep
      - name: curated_strcpanewbsrep
      - name: curated_roc_status_projectname      
      - name: curated_dim_project
      - name: curated_elecequiwbsrep
      - name: curated_me_function_code
      - name: curated_modelreviewitemstracker

  - name: curated_spel
    schema: "{{ var('curated_spel_schema')[target.name] }}"
    tables:
      - name: curated_codelists
      - name: curated_t_equipment
      - name: curated_t_plantitem
      - name: curated_t_modelitem
      - name: curated_t_cable
      - name: curated_t_electricalequipment

  - name: curated_isotracker
    schema: "{{ var('curated_isotracker_schema')[target.name] }}"
    tables:
      - name: curated_bog
      - name: curated_bop_sm_sz
      - name: curated_lfm
      - name: curated_mar
      - name: curated_mpr
      - name: curated_nruisotracker
      - name: curated_ptm
      - name: curated_ug
      - name: curated_bop_um_uz
      - name: curated_cp2_stress_calc      


  - name: curated_omie
    schema: "{{ var('curated_omie_schema')[target.name] }}"
    tables:
      - name: curated_combo
      - name: curated_req
      - name: curated_wfstatus      

  - name: curated_spi
    schema: "{{ var('curated_spi_schema')[target.name] }}"
    tables:
      - name: curated_component
      - name: curated_component_function_type
      - name: curated_component_handle
      - name: curated_component_location
      - name: curated_component_sys_io_type
      - name: curated_drawing
      - name: curated_line
      - name: curated_loop
      - name: curated_plant
      - name: curated_tag_category
      - name: curated_udf_component 
      - name: curated_dim_static_phyinstru      

  - name: curated_engreg
    schema: "{{ var('curated_engreg_schema')[target.name] }}"
    tables:
      - name: curated_assumptions_index
      - name: curated_holds_index
      - name: curated_seal_decisions
      - name: curated_td_index

  - name: curated_aim
    schema: "{{ var('curated_aim_schema')[target.name] }}"
    tables:
      - name: curated_vwe_vg_cp2_tags_pwrbi    
      - name: curated_tag_to_po

  - name: curated_mel
    schema: "{{ var('curated_mel_schema')[target.name] }}"
    tables:
      - name: curated_mechanical_equipment_list_eql    
            
  - name: curated_mps
    schema: "{{ var('curated_mps_schema')[target.name] }}"
    tables:
      - name: mps_log_all_bog  
      - name: mps_log_all_bop  
      - name: mps_log_all_lfm  
      - name: mps_log_all_mar  
      - name: mps_log_all_mpr  
      - name: mps_log_all_nru  
      - name: mps_log_all_ptm  
      - name: mps_log_all_tnk

            