{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_spi_loop/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


select
    cast(loop_id as numeric(38, 0)),
    cast(proj_id as numeric(38, 0)),
    cast(site_id as numeric(38, 0)),
    cast(chg_num as numeric(38, 0)),
    cast(plant_id as numeric(38, 0)),
    cast(area_id as numeric(38, 0)),
    cast(unit_id as numeric(38, 0)),
    user_name,
    chg_status,
    chg_date,
    loop_name,
    loop_num,
    cast(loop_proc_id as numeric(38, 0)),
    cast(loop_type_id as numeric(38, 0)),
    cast(loop_func_id as numeric(38, 0)),
    loop_suff,
    name_lock_flg,
    loop_serv,
    loop_prefix,
    old_loop_name,
    loop_note,
    serv_cmpnt_flg,
    loop_trans_name,
    loop_param,
    loop_sheet_type_flg,
    cast(loop_seq_no as numeric(38, 0)),
    cast(dwg_id as numeric(38, 0)),
    dwg_cmpnt_flg,
    ext_macro_source,
    type_gen,
    cast(loop_set_id as numeric(38, 0)),
    cast (loop_calib_error as float),
    cast(eng_proj_id as numeric(38, 0)),
    cast(eng_ref_id as numeric(38, 0)),
    cast(loop_equip_id as numeric(38, 0)),
    loop_equip_flg,
    loop_error_calc,
    cast(esl_loop_set_id as numeric(38, 0)),
    ext_drawing_path,
    note_cmpnt_flg,
    cast(loop_equip_id as numeric(38, 0)) loop_criticality_id,
    generated_flg,
    kks_totalplant,
    kks_function_key_prefix,
    kks_function_key,
    kks_function_key_sequence,
    kks_equipment_unit_code,
    kks_equipment_unit_sequence,
    kks_equipment_unit_add_code,
    kks_component_key,
    kks_component_key_sequence,
    merge_release_flg,
    cast(dwg_external_blk_id as numeric(38, 0)),
    'VGCP2' as project_code,
    source_system_name,
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id,
    cast(execution_date as date) as extracted_date
from
    {{ source('curated_spi', 'curated_loop') }}