{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_spel_t_equipments/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}

select
	sp_id,
	CAST(statustype AS decimal(38,0)) AS statustype,
	CAST(noofphases AS decimal(38,0)) AS noofphases,
	CAST(gasgroup AS decimal(38,0)) AS gasgroup,
	CAST(issld AS decimal(38,0)) AS issld,
	CAST(model AS decimal(38,0)) AS model,
	sp_circuitid,
	sp_busid,
	sp_cellid,
	sp_powerdistributionboardid,
	CAST(sequenceingroup AS decimal(38,0)) AS sequenceingroup,
	sp_reftypicalschematicid,
	sp_reflookuptableid,
	storespartnumber,
	CAST(manufacturer AS decimal(38,0)) AS manufacturer,
	sp_refequipmentid,
	note,
	itemtypeidentifier,
	CAST(electricalequipmenttype AS decimal(38,0)) AS electricalequipmenttype,
	CAST(ingressionprotection AS decimal(38,0)) AS ingressionprotection,
	CAST(temperatureclass AS decimal(38,0)) AS temperatureclass,
	CAST(explosionprotection AS decimal(38,0)) AS explosionprotection,
	CAST(iselectricaltree AS decimal(38,0)) AS iselectricaltree,
	CAST(electricalequipmentclass AS decimal(38,0)) AS electricalequipmentclass,
	CAST(electricalequipmentsubclass AS decimal(38,0)) AS electricalequipmentsubclass,
	CAST(supplyacdcflag AS decimal(38,0)) AS supplyacdcflag,
	CAST(complytonamingconvention AS decimal(38,0)) AS complytonamingconvention,
	sp_powersourceid,
	fullloadcurrent,
	CAST(sp_fullloadcurrentsi AS float) AS sp_fullloadcurrentsi,
	CAST(erpcostcenter AS decimal(38,0)) AS erpcostcenter,
	CAST(erpcriticalityclass AS decimal(38,0)) AS erpcriticalityclass,
	CAST(erpequipmentclass AS decimal(38,0)) AS erpequipmentclass,
	CAST(erpequipmenttype AS decimal(38,0)) AS erpequipmenttype,
	erpfunctionallocation,
	CAST(erpplanner AS decimal(38,0)) AS erpplanner,
	CAST(erpworkcenter AS decimal(38,0)) AS erpworkcenter,
	sp_refsignalgroupid,
	CAST(iscircuitinternal AS decimal(38,0)) AS iscircuitinternal,
	sp_alternatepowersourceid,
	sp_alternatecircuitid,
	CAST(sp_equipmenttypeidentifier AS decimal(38,0)) AS sp_equipmenttypeidentifier,
	CAST(sp_procurementstatus AS decimal(38,0)) AS sp_procurementstatus,
	CAST(sp_isspare AS decimal(38,0)) AS sp_isspare,
	vg_processsystemgroupid,
	CAST(vg_equipmentlocation AS decimal(38,0)) AS vg_equipmentlocation,
	CAST(vg_lpsno1 AS decimal(38,0)) AS vg_lpsno1,
	CAST(vg_projectscopephase AS decimal(38,0)) AS vg_projectscopephase,
	CAST(vg_areaname AS decimal(38,0)) AS vg_areaname,
	CAST(vg_loadtype AS decimal(38,0)) AS vg_loadtype,
	CAST(vg_cwa AS decimal(38,0)) AS vg_cwa,
	vg_revisionnumber,
	vg_schematicdrawingnumber,
	vg_weighttransport,
	CAST(sp_vg_weighttransportsi AS float) AS sp_vg_weighttransportsi,
	vg_unitdepth,
	CAST(sp_vg_unitdepthsi AS float) AS sp_vg_unitdepthsi,
	vg_unitwidth,
	CAST(sp_vg_unitwidthsi AS float) AS sp_vg_unitwidthsi,
	vg_unitheight,
	CAST(sp_vg_unitheightsi AS float) AS sp_vg_unitheightsi,
	vg_unitweight,
	CAST(sp_vg_unitweightsi AS float) AS sp_vg_unitweightsi,
	vg_packagenumber,
	vg_weightmaximum,
	CAST(sp_vg_weightmaximumsi AS float) AS sp_vg_weightmaximumsi,
	vg_weightoperational,
	CAST(sp_vg_weightoperationalsi AS float) AS sp_vg_weightoperationalsi,
	vg_mainequipment,
	CAST(vg_installedby AS decimal(38,0)) AS vg_installedby,
	source_system_name,
	'VGCP2' project_code,
	cast(execution_date as date) as extracted_date,
	{{run_date}} as model_created_date,
	{{run_date}} as model_updated_date,
	{{ generate_load_id(model) }} as model_load_id
FROM 
{{ source('curated_spel', 'curated_t_equipment') }}

