{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_spi_line/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}

select
    cast(line_id as decimal(38, 0)) as line_id,
    cast(proj_id as decimal(38, 0)) as proj_id,
    cast(site_id as decimal(38, 0)) as site_id,
    cast(chg_num as decimal(38, 0)) as chg_num,
    cast(unit_id as decimal(38, 0)) as unit_id,
    cast(user_name as varchar(300)) as user_name,
    cast(chg_status as varchar(500)) as chg_status,
    chg_date,
    cast(line_num as varchar(500)) as line_num,
    cast(line_size as varchar(500)) as line_size,
    cast(wall_thick as float) as wall_thick,
    cast(rtg as varchar(500)) as rtg,
    cast(plant_id as decimal(38, 0)) as plant_id,
    cast(area_id as decimal(38, 0)) as area_id,
    cast(line_type_id as decimal(38, 0)) as line_type_id,
    cast(line_sched as varchar(500)) as line_sched,
    cast(line_internal_dia as float) as line_internal_dia,
    cast(temperature_rtg as varchar(500)) as temperature_rtg,
    cast(press_rtg as varchar(500)) as press_rtg,
    cast(pd_corros_allow as float) as pd_corros_allow,
    cast(pd_insul as varchar(500)) as pd_insul,
    cast(pd_pump_drop_uid as varchar(500)) as pd_pump_drop_uid,
    cast(pd_velocity_min as float) as pd_velocity_min,
    cast(pd_velocity_max as float) as pd_velocity_max,
    cast(pd_velocity_nor as float) as pd_velocity_nor,
    cast(pd_velocity_uid as varchar(500)) as pd_velocity_uid,
    cast(pd_line_from as varchar(500)) as pd_line_from,
    cast(pd_line_to as varchar(500)) as pd_line_to,
    cast(pd_piping_class as varchar(500)) as pd_piping_class,
    cast(pd_pour_pnt_up as float) as pd_pour_pnt_up,
    cast(pd_pour_pnt_low as float) as pd_pour_pnt_low,
    cast(pd_pour_pnt_uid as varchar(500)) as pd_pour_pnt_uid,
    cast(pd_sys_fric_loss as float) as pd_sys_fric_loss,
    cast(pd_sys_fric_loss_uid as varchar(500)) as pd_sys_fric_loss_uid,
    cast(pd_corros_allow_uid as varchar(500)) as pd_corros_allow_uid,
    cast(pd_pump_drop as float) as pd_pump_drop,
    cast(pipe_std_id as decimal(38, 0)) as pipe_std_id,
    cast(line_uom as varchar(500)) as line_uom,
    cast(pipe_material as varchar(500)) as pipe_material,
    cast(ansi_din as varchar(500)) as ansi_din,
    cast(pipe_size as float) as pipe_size,
    cast(wall_thick_uom as varchar(500)) as wall_thick_uom,
    cast(line_internal_dia_uom as varchar(500)) as line_internal_dia_uom,
    cast(pd_insulation_id as decimal(38, 0)) as pd_insulation_id,
    cast(pipe_orif_mat_id as decimal(38, 0)) as pipe_orif_mat_id,
    cast(line_isize_pipeschid_indx as decimal(38, 0)) as line_isize_pipeschid_indx,
    cast(line_isize_sched_indx as decimal(38, 0)) as line_isize_sched_indx,
    cast(rev_id as decimal(38, 0)) as rev_id,
    cast(eng_proj_id as decimal(38, 0)) as eng_proj_id,
    cast(eng_ref_id as decimal(38, 0)) as eng_ref_id,
    cast(stream_num as varchar(400)) as stream_num,
    cast(dwg_id as decimal(38, 0)) as dwg_id,
    cast(pipe_class_id as decimal(38, 0)) as pipe_class_id,
    cast(kks_totalplant as varchar(500)) as kks_totalplant,
    cast(kks_function_key_prefix as varchar(500)) as kks_function_key_prefix,
    cast(kks_function_key as varchar(500)) as kks_function_key,
    cast(kks_function_key_sequence as varchar(500)) as kks_function_key_sequence,
    cast(kks_equipment_unit_code as varchar(500)) as kks_equipment_unit_code,
    cast(kks_equipment_unit_sequence as varchar(500)) as kks_equipment_unit_sequence,
    cast(kks_equipment_unit_add_code as varchar(500)) as kks_equipment_unit_add_code,
    cast(kks_component_key as varchar(500)) as kks_component_key,
    cast(kks_component_key_sequence as varchar(500)) as kks_component_key_sequence,
    cast(merge_release_flg as varchar(500)) as merge_release_flg,
    'VGCP2' as project_code,
    cast(execution_date as date) as extracted_date,
    source_system_name,
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from
    {{ source('curated_spi', 'curated_line') }}
	