{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_e3d_struc/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


SELECT 
    NAME,
    type,
    lock,
    owner,
    desc,
    func,
    purp,
    numb,
    buil,
    area,
    pos,
    ori,
    grdref,
    usrwei,
    usrwwe,
    usrcog,
    usrwco,
    uwmtxt,
    desp,
    dunion,
    propst,
    optblo,
    pdname,
    skey,
    mps_line_number,
    mps_isometric_number,
    mps_date_piping_placeholder_modeling_completed,
    mps_date_piping_stress_loads_to_stru,
    mps_date_structural_modeling_complete,
    mps_structural_engineering_released_to_piping,
    mps_date_structural_engineering_forecast,
    mps_date_structural_engineering_actual,
    mps_date_structural_engineering_complete,
    structural_mps_number,
    mps_foundation_req,
    mps_comment,
    constcat,
    deckimpact,
    fstat,
    drwgissue,
    furntype,
    mpstyp,
    wtbare_lb,
    wtoper_lb,
    wsupphori,
    inprtr,
    wsupphtag,
    ouprtr,
    wsuppudim,
    wsuppcod,
    track_id,
    requisition,
    serialno,
    fstatus,
    modulefabricator,
    comment0,
    rocstatus,
    progress,
    hold,
    stvval_wor_status_strc_stru,
    areacode,
    areano,
    cgflowmed,
    cgvolume,
    ctllocation,
    comment,
    dcgpos,
    holdcomment,
    holdflag,
    issued,
    issuedby,
    issueddate,
    ocgpos,
    tcgpos,
    transmittalno,
    wcgcomnt,
    wcgdte,
    wcgloc,
    wcgstat,
    workpackno,
    worktype,
    cwarea,
    '' as CWP,     -- Missing Column
    ewp,
    '' as GUID,     -- Missing Column
    discipline,
    tagno,
    '' as TYPE1,     -- Missing Column
    units,
    uom,
    '' as MATERIAL,     -- Missing Column
    '' as SUBSYSTEM,     -- Missing Column
    fireproofing,
    insulation,
    itemno,
    commcode,
    '' as INSUTYPE,     -- Missing Column
    section_name,
    strutype,
    strucate,
    piecemark,
    steeltype,
    status,
    zone,
    site,
    cast(execution_date as date) as extracted_date,
    source_system_name,
    'VGCP2' project_code,
    Split_part(site, '-', 2) AS WBS,
    Substring(zone, 2, 2) AS CWA,
    Substring(zone, 2, 4) AS CWPZONE,
    Split_part(zone, '/', 1) AS CWP1,
	'VGCP2'|| '_' ||
    Split_part(site, '-', 2)|| '_' ||
    Substring(zone, 2, 2) || '_' ||
    Substring(zone, 2, 4) AS PROJECT_CODE_WBS_CWA_CWPZONE,    
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
FROM 
    {{ source('curated_e3d', 'curated_vg_e3d_vglstruc_sheet') }}

	
