SourceSystemId: assurance
MetadataType: curated#assurance#event_consequence_security#job#iceberg
source:
  compute_engine: spark
  glue_options:
    connection_options: s3://${raw_bucket}/health_safety_environment/assurance/parquet/event_consequence_security.parquet/
    connection_type: s3
    format: parquet
    format_options:
      mergeSchema: true
    transformation_ctx: event_consequence_security
  name: event_consequence_security
  spark_options:
    format: parquet
target:
  compute_engine: spark
  drop_duplicates: true
  primary_constraint_properties:
    enforce_primary_constraint: true
    timestamp_column_name: bms_lastmodified
  iceberg_properties:
    database_name: ${database_prefix}_health_safety_environment_assurance_curated
    iceberg_configuration:
      create_table: true
      iceberg_catalog_warehouse: ${curated_bucket}/health_safety_environment/assurance/event_consequence_security/
      table_properties:
        format-version: '2'
        write.format.default: parquet
    table_name: event_consequence_security
  load_type: incremental
  name: event_consequence_security
  primary_key: dwi_event_consequence_security
  spark_options:
    format: iceberg
    options:
      path: s3://${curated_bucket}/health_safety_environment/assurance/event_consequence_security
transforms:
- rename_column: true
  transform: rename_columns
- select_columns: true
  transform: select_columns_from_config_file
- change_types: true
  transform: change_data_types
- sql: SELECT *, 'assurance' as SOURCE_SYSTEM_NAME FROM temp_df_static
  temp_view_name: temp_df_static
  transform: custom_sql
- column_name: EXECUTION_DATE
  date_format: yyyy-MM-dd  HH:mm:ss
  transform: add_run_date
table_schema:
  schema_properties:
    enforce: true
    primary_key: dwi_event_consequence_security
    rename_columns: true
  columns:
  - column_name: dwi_event_consequence_security
    column_data_type: decimal(38,0)
    comment: dwi_event_consequence_security
    data_classification:
    nullable: true
    raw_column_name: dwi_event_consequence_security
  - column_name: offender_or_suspect_details_name_of_offendersuspect_if_not_in_list
    column_data_type: string
    comment: offender_or_suspect_details_name_of_offendersuspect_if_not_in_list
    data_classification:
    nullable: true
    raw_column_name: offender_or_suspect_details_name_of_offendersuspect_if_not_in_list
  - column_name: offender_or_suspect_details_offender_or_suspect_age_group
    column_data_type: string
    comment: offender_or_suspect_details_offender_or_suspect_age_group
    data_classification:
    nullable: true
    raw_column_name: offender_or_suspect_details_offender_or_suspect_age_group
  - column_name: li_offender_or_suspect_details_offender_or_suspect_age_group
    column_data_type: string
    comment: li_offender_or_suspect_details_offender_or_suspect_age_group
    data_classification:
    nullable: true
    raw_column_name: li_offender_or_suspect_details_offender_or_suspect_age_group
  - column_name: lo_offender_or_suspect_details_offender_or_suspect_age_group
    column_data_type: decimal(38,0)
    comment: lo_offender_or_suspect_details_offender_or_suspect_age_group
    data_classification:
    nullable: true
    raw_column_name: lo_offender_or_suspect_details_offender_or_suspect_age_group
  - column_name: offender_or_suspect_details_offender_or_suspect_gender
    column_data_type: string
    comment: offender_or_suspect_details_offender_or_suspect_gender
    data_classification:
    nullable: true
    raw_column_name: offender_or_suspect_details_offender_or_suspect_gender
  - column_name: li_offender_or_suspect_details_offender_or_suspect_gender
    column_data_type: string
    comment: li_offender_or_suspect_details_offender_or_suspect_gender
    data_classification:
    nullable: true
    raw_column_name: li_offender_or_suspect_details_offender_or_suspect_gender
  - column_name: lo_offender_or_suspect_details_offender_or_suspect_gender
    column_data_type: decimal(38,0)
    comment: lo_offender_or_suspect_details_offender_or_suspect_gender
    data_classification:
    nullable: true
    raw_column_name: lo_offender_or_suspect_details_offender_or_suspect_gender
  - column_name: reference_number
    column_data_type: string
    comment: reference_number
    data_classification:
    nullable: true
    raw_column_name: reference_number
  - column_name: resolution_details_further_details
    column_data_type: string
    comment: resolution_details_further_details
    data_classification:
    nullable: true
    raw_column_name: resolution_details_further_details
  - column_name: resolution_details_resolution_outcome
    column_data_type: string
    comment: resolution_details_resolution_outcome
    data_classification:
    nullable: true
    raw_column_name: resolution_details_resolution_outcome
  - column_name: li_resolution_details_resolution_outcome
    column_data_type: string
    comment: li_resolution_details_resolution_outcome
    data_classification:
    nullable: true
    raw_column_name: li_resolution_details_resolution_outcome
  - column_name: lo_resolution_details_resolution_outcome
    column_data_type: decimal(38,0)
    comment: lo_resolution_details_resolution_outcome
    data_classification:
    nullable: true
    raw_column_name: lo_resolution_details_resolution_outcome
  - column_name: resolution_details_resolution_property
    column_data_type: string
    comment: resolution_details_resolution_property
    data_classification:
    nullable: true
    raw_column_name: resolution_details_resolution_property
  - column_name: li_resolution_details_resolution_property
    column_data_type: string
    comment: li_resolution_details_resolution_property
    data_classification:
    nullable: true
    raw_column_name: li_resolution_details_resolution_property
  - column_name: lo_resolution_details_resolution_property
    column_data_type: decimal(38,0)
    comment: lo_resolution_details_resolution_property
    data_classification:
    nullable: true
    raw_column_name: lo_resolution_details_resolution_property
  - column_name: security_details
    column_data_type: string
    comment: security_details
    data_classification:
    nullable: true
    raw_column_name: security_details
  - column_name: victim_details_name_of_victim_if_not_in_list
    column_data_type: string
    comment: victim_details_name_of_victim_if_not_in_list
    data_classification:
    nullable: true
    raw_column_name: victim_details_name_of_victim_if_not_in_list
  - column_name: victim_details_victim_address
    column_data_type: string
    comment: victim_details_victim_address
    data_classification:
    nullable: true
    raw_column_name: victim_details_victim_address
  - column_name: victim_details_victim_age_group
    column_data_type: string
    comment: victim_details_victim_age_group
    data_classification:
    nullable: true
    raw_column_name: victim_details_victim_age_group
  - column_name: li_victim_details_victim_age_group
    column_data_type: string
    comment: li_victim_details_victim_age_group
    data_classification:
    nullable: true
    raw_column_name: li_victim_details_victim_age_group
  - column_name: lo_victim_details_victim_age_group
    column_data_type: decimal(38,0)
    comment: lo_victim_details_victim_age_group
    data_classification:
    nullable: true
    raw_column_name: lo_victim_details_victim_age_group
  - column_name: victim_details_victim_gender
    column_data_type: string
    comment: victim_details_victim_gender
    data_classification:
    nullable: true
    raw_column_name: victim_details_victim_gender
  - column_name: li_victim_details_victim_gender
    column_data_type: string
    comment: li_victim_details_victim_gender
    data_classification:
    nullable: true
    raw_column_name: li_victim_details_victim_gender
  - column_name: lo_victim_details_victim_gender
    column_data_type: decimal(38,0)
    comment: lo_victim_details_victim_gender
    data_classification:
    nullable: true
    raw_column_name: lo_victim_details_victim_gender
  - column_name: sys_legacy_id
    column_data_type: string
    comment: sys_legacy_id
    data_classification:
    nullable: true
    raw_column_name: sys_legacy_id
  - column_name: employment_category
    column_data_type: string
    comment: employment_category
    data_classification:
    nullable: true
    raw_column_name: employment_category
  - column_name: li_employment_category
    column_data_type: string
    comment: li_employment_category
    data_classification:
    nullable: true
    raw_column_name: li_employment_category
  - column_name: lo_employment_category
    column_data_type: decimal(38,0)
    comment: lo_employment_category
    data_classification:
    nullable: true
    raw_column_name: lo_employment_category
  - column_name: dwk_event_as_source_of_security_consequence
    column_data_type: decimal(38,0)
    comment: dwk_event_as_source_of_security_consequence
    data_classification:
    nullable: true
    raw_column_name: dwk_event_as_source_of_security_consequence
  - column_name: dwk_security_victim
    column_data_type: decimal(38,0)
    comment: dwk_security_victim
    data_classification:
    nullable: true
    raw_column_name: dwk_security_victim
  - column_name: dwk_security_offender_or_suspect
    column_data_type: decimal(38,0)
    comment: dwk_security_offender_or_suspect
    data_classification:
    nullable: true
    raw_column_name: dwk_security_offender_or_suspect
  - column_name: si_status
    column_data_type: string
    comment: si_status
    data_classification:
    nullable: true
    raw_column_name: si_status
  - column_name: sn_status
    column_data_type: string
    comment: sn_status
    data_classification:
    nullable: true
    raw_column_name: sn_status
  - column_name: si_base_state
    column_data_type: string
    comment: si_base_state
    data_classification:
    nullable: true
    raw_column_name: si_base_state
  - column_name: sn_base_state
    column_data_type: string
    comment: sn_base_state
    data_classification:
    nullable: true
    raw_column_name: sn_base_state
  - column_name: uniqueid
    column_data_type: string
    comment: uniqueid
    data_classification:
    nullable: true
    raw_column_name: uniqueid
  - column_name: bms_id
    column_data_type: string
    comment: bms_id
    data_classification:
    nullable: true
    raw_column_name: bms_id
  - column_name: bms_lastmodified
    column_data_type: timestamp
    comment: bms_lastmodified
    data_classification:
    nullable: true
    raw_column_name: bms_lastmodified