SourceSystemId: assurance
MetadataType: curated#assurance#event_consequence_environmental_contaminants_contaminant_type#job#iceberg
source:
  compute_engine: spark
  glue_options:
    connection_options: s3://${raw_bucket}/health_safety_environment/assurance/parquet/event_consequence_environmental_contaminants_contaminant_type.parquet/
    connection_type: s3
    format: parquet
    format_options:
      mergeSchema: true
    transformation_ctx: event_consequence_environmental_contaminants_contaminant_type
  name: event_consequence_environmental_contaminants_contaminant_type
  spark_options:
    format: parquet
target:
  compute_engine: spark
  iceberg_properties:
    database_name: ${database_prefix}_health_safety_environment_assurance_curated
    iceberg_configuration:
      create_table: true
      iceberg_catalog_warehouse: ${curated_bucket}/health_safety_environment/assurance/event_consequence_environmental_contaminants_contaminant_type/
      table_properties:
        format-version: '2'
        write.format.default: parquet
    table_name: event_consequence_environmental_contaminants_contaminant_type
  load_type: incremental
  name: event_consequence_environmental_contaminants_contaminant_type
  primary_key: [dwk_event_consequence_environmental, li_contaminants_contaminant_type]
  spark_options:
    format: iceberg
    options:
      path: s3://${curated_bucket}/health_safety_environment/assurance/event_consequence_environmental_contaminants_contaminant_type
transforms:
- rename_column: true
  transform: rename_columns
- select_columns: true
  transform: select_columns_from_config_file
- change_types: true
  transform: change_data_types
- sql: SELECT *, 'assurance' as SOURCE_SYSTEM_NAME FROM temp_df_static
  temp_view_name: temp_df_static
  transform: custom_sql
- column_name: EXECUTION_DATE
  date_format: yyyy-MM-dd  HH:mm:ss
  transform: add_run_date
table_schema:
  schema_properties:
    enforce: true
    primary_key: [dwk_event_consequence_environmental, li_contaminants_contaminant_type]
    rename_columns: true
  columns:
  - column_name: dwk_event_consequence_environmental
    column_data_type: decimal(38,0)
    comment: dwk_event_consequence_environmental
    data_classification:
    nullable: true
    raw_column_name: dwk_event_consequence_environmental
  - column_name: contaminants_contaminant_type
    column_data_type: string
    comment: contaminants_contaminant_type
    data_classification:
    nullable: true
    raw_column_name: contaminants_contaminant_type
  - column_name: li_contaminants_contaminant_type
    column_data_type: string
    comment: li_contaminants_contaminant_type
    data_classification:
    nullable: true
    raw_column_name: li_contaminants_contaminant_type
  - column_name: lo_contaminants_contaminant_type
    column_data_type: decimal(38,0)
    comment: lo_contaminants_contaminant_type
    data_classification:
    nullable: true
    raw_column_name: lo_contaminants_contaminant_type