{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_TIMESTAMP" -%}


{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_jacobs_project__c/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["csp_salesforce"]
    ) 
}}


with sfjp_cdc as (
    select *  from {{ source('curated_salesforce', 'curated_jacobs_project__c') }} sfjp
    where sfjp.is_current = 1
    {%- if execution_date_arg != "" %}
      and execution_date >= '{{ execution_date_arg }}'
    {%- else %}
        {%- if is_incremental() %}
            and cast(sfjp.execution_date as DATE) > (select max(etl_load_date)  from {{ this }})
        {%- endif %}
    {%- endif %}
),

sfjp_data AS (
    select 
        id,
        ownerid,
        isdeleted,
        name,
        currencyisocode,
        recordtypeid,
        createddate,
        createdbyid,
        lastmodifieddate,
        lastmodifiedbyid,
        systemmodstamp,
        lastactivitydate,
        lastvieweddate,
        lastreferenceddate,
        account_namec,
        CAST(actual_cost_localc AS FLOAT) as actual_cost_localc,
        actual_costc as actual_costc,
        actual_gm_hrc as actual_gm_hrc,
        CAST(actual_gross_margin_localc AS FLOAT) as actual_gross_margin_localc,
        actual_gross_marginc as actual_gross_marginc,
        CAST(actual_revenue_localc AS FLOAT) as actual_revenue_localc,
        actual_revenuec as actual_revenuec,
        actual_value_mismatchc,
        area_of_businessc,
        CAST(b_p_budget_localc AS FLOAT) as b_p_budget_localc,
        b_p_budgetc as b_p_budgetc,
        b_p_request_created_datec,
        b_p_requestc,
        CAST(billable_hoursc AS FLOAT) as billable_hoursc,
        CAST(budgeted_cost_localc AS FLOAT) as budgeted_cost_localc,
        budgeted_costc as budgeted_costc,
        budgeted_gm_hrc as budgeted_gm_hrc,
        budgeted_gmc as budgeted_gmc,
        budgeted_gross_marginc as budgeted_gross_marginc,
        CAST(budgeted_hoursc AS FLOAT) as budgeted_hoursc,
        CAST(budgeted_revenue_localc AS FLOAT) as budgeted_revenue_localc,
        budgeted_revenuec as budgeted_revenuec,
        ch2m_dynamics_idc,
        contract_typec,
        controlling_performance_unitc,
        CAST(cost_current_month_localc AS FLOAT) as cost_current_month_localc,
        cost_current_monthc  as cost_current_monthc,
        CAST(cost_ptd_localc AS FLOAT) as cost_ptd_localc,
        cost_ptdc  as cost_ptdc,
        CAST(cost_ytd_localc AS FLOAT) as cost_ytd_localc,
        cost_ytdc  as cost_ytdc,
        cost_budget_last_update_datec,
        cross_chargec,
        datasourcec,
        ecrmigrationexternalidc,
        fiscal_yearc,
        govt_agencyc,
        jacobs_sales_lead_employee_numberc,
        jacobs_sales_leadc,
        legacyvisionidc,
        legal_entityc,
        line_of_businessc,
        local_currencyc,
        market_sectorc,
        CAST(nonbillable_hoursc AS FLOAT) as nonbillable_hoursc,
        office_receiving_cross_chargec,
        operating_unitc,
        opportunityc,
        oracle_account_idc,
        ptd_projectc,
        pu_descriptionc,
        performance_unit_manual_entryc,
        program_contract_newc,
        project_accountant_employee_numberc,
        project_accountantc,
        project_codec,
        project_estimated_completion_datec,
        project_id_fy_keyc,
        project_idc,
        project_long_namec,
        project_manager_employee_numberc,
        project_managerc,
        project_start_datec,
        project_statusc,
        project_typec,
        reported_business_unitc,
        reported_line_of_businessc,
        reported_performance_unitc,
        request_typec,
        service_typec,
        status_mismatchc,
        sub_market_descriptionc,
        task_validationc,
        variance_gmc as variance_gmc,
        variance_revenuec as variance_revenuec,
        work_typec,
        cb_confidentialc,
        lr_clientc,
        CAST(nu_workhoursc AS FLOAT) as nu_workhoursc,
        txt_business_unitc,
        txt_descriptionc,
        txt_externally_communicated_project_namec,
        txt_project_numberc,
        CAST(actual_cost_contractc AS FLOAT) as actual_cost_contractc,
        CAST(actual_cost_corpc AS FLOAT) as actual_cost_corpc,
        CAST(actual_gm_hr_contractc AS FLOAT) as actual_gm_hr_contractc,
        CAST(actual_gm_hr_corpc AS FLOAT) as actual_gm_hr_corpc,
        CAST(actual_gross_margin_contractc AS FLOAT) as actual_gross_margin_contractc,
        CAST(actual_gross_margin_corpc AS FLOAT) as actual_gross_margin_corpc,
        CAST(actual_revenue_contractc AS FLOAT) as actual_revenue_contractc,
        CAST(actual_revenue_corpc AS FLOAT) as actual_revenue_corpc,
        CAST(b_p_budget_contractc AS FLOAT) as b_p_budget_contractc,
        CAST(b_p_budget_corpc AS FLOAT) as b_p_budget_corpc,
        CAST(budgeted_cost_contractc AS FLOAT) as budgeted_cost_contractc,
        CAST(budgeted_cost_corpc AS FLOAT) as budgeted_cost_corpc,
        budgeted_gm_contractc as budgeted_gm_contractc,
        CAST(budgeted_gm_corpc AS FLOAT) as budgeted_gm_corpc,
        budgeted_gm_hr_contractc as budgeted_gm_hr_contractc,
        CAST(budgeted_gm_hr_corpc AS FLOAT) as budgeted_gm_hr_corpc,
        CAST(budgeted_gross_margin_contractc AS FLOAT) as budgeted_gross_margin_contractc,
        CAST(budgeted_gross_margin_corpc AS FLOAT) as budgeted_gross_margin_corpc,
        CAST(budgeted_revenue_contractc AS FLOAT) as budgeted_revenue_contractc,
        CAST(budgeted_revenue_corpc AS FLOAT) as budgeted_revenue_corpc,
        CAST(cost_current_month_contractc AS FLOAT) as cost_current_month_contractc,
        CAST(cost_current_month_corpc AS FLOAT) as cost_current_month_corpc,
        CAST(cost_ptd_contractc AS FLOAT) as cost_ptd_contractc,
        CAST(cost_ptd_corpc AS FLOAT) as cost_ptd_corpc,
        CAST(cost_ytd_contractc AS FLOAT) as cost_ytd_contractc,
        CAST(cost_ytd_corpc AS FLOAT) as cost_ytd_corpc,
        CAST(exchange_rate_lookupc AS FLOAT) as exchange_rate_lookupc,
        project_current_exchange_ratec AS  project_current_exchange_ratec,
        CAST(variance_gm_contractc AS FLOAT) as variance_gm_contractc,
        CAST(variance_gm_corpc AS FLOAT) as variance_gm_corpc,
        CAST(variance_revenue_contractc AS FLOAT) as variance_revenue_contractc,
        CAST(variance_revenue_corpc AS FLOAT) as variance_revenue_corpc,
        accountidc,
        advisian_service_line_reportingc,
        advisian_service_linec,
        asset_typec,
        automated_finance_integrationc,
        CAST(b_p_labor_hoursc AS FLOAT) as b_p_labor_hoursc,
        b_p_project_numberc,
        bill_to_addressc,
        billing_locationc,
        billing_typec,
        business_linec,
        business_segment_reportingc,
        business_segmentc,
        csp_project_numberc,
        capability_subsector_reportingc,
        capability_subsectorc,
        contract_numberc,
        contractual_basis_definitionsc,
        contractual_basisc,
        country_of_assetc,
        currencyc,
        customer_idc,
        customer_typec,
        digital_projectc,
        CAST(duration_monthsc AS FLOAT) as duration_monthsc,
        ecr_project_numberc,
        final_approved_datec,
        first_doa_approverc,
        gbs_advisian_business_linec,
        gbs_business_line_reportingc,
        gbs_business_linec,
        gbs_customer_subsector_reportingc,
        gbs_customer_subsectorc,
        gbs_legal_entityc,
        gbs_location_reportingc,
        gbs_locationc,
        gbs_project_accountantc,
        gbs_project_controllerc,
        gbs_project_initiatorc,
        gbs_project_managerc,
        gbs_project_orgc,
        getc,
        goc,
        integration_statusc,
        location_operating_unitc,
        npis_project_typec,
        opportunity_primary_location_statusc,
        project_controller_employee_numberc,
        project_controllerc,
        project_phase_reportingc,
        project_phasec,
        project_risk_classificationc,
        CAST(proposal_budgetc AS FLOAT) as proposal_budgetc,
        proposal_managerc,
        purchase_order_numberc,
        refresh_financial_detailsc,
        refresh_instructionsc,
        scope_of_servicesc,
        second_doa_approverc,
        ship_to_addressc,
        site_numberc,
        technology_classificationc,
        toastshownc,
        sf_id_18c,
        oracle_account_numberc,
        ped_record_updatedc,
        market_segment_l3c,
        project_classificationc,
        cast(execution_date as date) as etl_load_date,
        CAST({{run_date}} as timestamp) as model_created_date,
        CAST({{run_date}} as timestamp) as model_updated_date,
        {{ generate_load_id(model) }} as model_load_id	
        from sfjp_cdc
)

SELECT  * FROM sfjp_data
