{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_TIMESTAMP" -%}


{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_opportunity/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["csp_salesforce"]
    ) 
}}


with sfco_cdc as (
    select *  from {{ source('curated_salesforce', 'curated_opportunity') }} sfco
    where sfco.is_current = 1
    {%- if execution_date_arg != "" %}
      and execution_date >= '{{ execution_date_arg }}'
    {%- else %}
        {%- if is_incremental() %}
            and cast(sfco.execution_date as DATE) > (select max(etl_load_date)  from {{ this }})
        {%- endif %}
    {%- endif %}
),

sfco_data AS (
    select 
        id,
        isdeleted,
        accountid,
        recordtypeid,
        isprivate,
        name,
        description,
        stagename,
        amount,
        probability,
        expectedrevenue,
        closedate,
        type,
        nextstep,
        leadsource,
        isclosed,
        iswon,
        forecastcategory,
        forecastcategoryname,
        currencyisocode,
        campaignid,
        hasopportunitylineitem,
        issplit,
        pricebook2id,
        ownerid,
        createddate,
        createdbyid,
        lastmodifieddate,
        lastmodifiedbyid,
        systemmodstamp,
        lastactivitydate,
        pushcount,
        laststagechangedate,
        contactid,
        lastvieweddate,
        lastreferenceddate,
        syncedquoteid,
        contractid,
        hasopenactivity,
        hasoverduetask,
        lastamountchangedhistoryid,
        lastclosedatechangedhistoryid,
        budget_confirmedc,
        discovery_completedc,
        roi_analysis_completedc,
        ecrmigrationexternalidc,
        loss_reasonc,
        db_competitorc,
        account_business_segmentc,
        annual_gmc,
        annual_revenuec,
        auto_create_contract_programc,
        avg_gmc,
        award_datec,
        base_currency_for_fx_conversion_to_usdc,
        booking_backlog_decision_treec,
        budgeted_gm2c,
        budgeted_gm_hr_var_percentc,
        budgeted_gm_hrc,
        budgeted_gm_var_percentc,
        budgeted_rev_var_percentc,
        budgeted_revenue2c,
        burnedc,
        business_unitc,
        ch2m_cost_centerc,
        ch2m_dynamics_idc,
        ch2m_market_segmentc,
        ch2m_org_idc,
        cpc_createdc,
        capture_managerc,
        client_personnel_notesc,
        commercial_strategyc,
        competition_typec,
        competitorsc,
        confetti_droppedc,
        confidentialc,
        consultancy_groupc,
        consultancy_prospect_typec,
        contract_award_typec,
        contract_ceilingc,
        contract_typec,
        contractual_modelc,
        convert_to_full_opportunityc,
        corporate_reporting_date_flaggedc,
        corporate_reporting_quarterc,
        corporate_reportingc,
        cost_to_date_newc,
        datamigridc,
        datasourcec,
        end_client_account_groupc,
        end_clientc,
        exclude_cpcc,
        executing_business_unitc,
        executing_line_of_businessc,
        execution_plan_summaryc,
        fbo_id_a_tc,
        fbo_linkc,
        frm_urlc,
        fy_end_datec,
        fiscal_yearc,
        forecast_categoryc,
        funding_clientc,
        gid_candidatec,
        gm_hr_to_datec,
        getc,
        goc,
        govwin_linkc,
        govwin_toc,
        gov_win_a_tc,
        gross_margin_b_p_ratioc,
        gross_margin_to_date_newc,
        groupc,
        idiq_a_tc,
        initial_stagec,
        is_cloned_opportunityc,
        jacobs_connected_enterprise_marketc,
        jacobs_connected_enterprise_technologiesc,
        jacobs_industry_groupc,
        latest_updatec,
        lead_performance_unit_puc,
        legacykmsidc,
        legacyvisionidc,
        legacy_award_typec,
        legacy_business_unitc,
        legacy_ch2m_close_datec,
        legacy_contract_award_typec,
        legacy_custindustrygroupc,
        legacy_lead_performance_unitc,
        legacy_lineofbusinessmarketc,
        legacy_locationc,
        legacy_opportunity_numberc,
        legacy_owneremailc,
        legacy_phasedirecthirehoursc,
        legacy_phasefsvdirecthirec,
        legacy_phasefsvpassthruc,
        legacy_phasefsvc,
        legacy_phasegmfsvc,
        legacy_phasegmpfsc,
        legacy_phasegmpsvc,
        legacy_phasepfsc,
        legacy_phasepsvc,
        legacy_phasesalaryhourspfsc,
        legacy_phasesalaryhourspsvc,
        legacy_scope_of_servicesc,
        legacy_sellingunitregionc,
        legacy_selling_unitc,
        legacy_visionnumberc,
        legacy_custfirstphaserecordidc,
        legacy_custmarketc,
        legacy_custmasterphasenumberc,
        legacy_custnatlgovtprogramtypec,
        legacy_custpucodec,
        legacy_custperformingofficec,
        legacy_custphasenumberc,
        legacy_custspecialtyservicesc,
        legacy_custstartdatefsc,
        legacy_custsubmarketc,
        line_of_businessc,
        link_to_documentsc,
        matoc,
        marketsc,
        move_to_wpc,
        my_selling_unitc,
        newco_de_duplication_status_reviewc,
        newco_duplicate_opportunity_idc,
        newco_factored_gm_synergyc,
        newco_factored_revenue_synergyc,
        newco_gm_changec,
        newco_guidancec,
        newco_pre_synergy_pwin_getc,
        newco_pwin_get_changec,
        newco_realized_gm_synergyc,
        newco_realized_revenue_synergyc,
        newco_revenue_changec,
        newco_revenue_synergy_commentc,
        newco_synergy_approvedc,
        newco_synergy_dis_synergy_reasonc,
        newco_synergy_identifiedc,
        newco_synergy_initiativec,
        oci_case_statusc,
        oci_indicatorc,
        odc_a_tc,
        opportunity_class_a_tc,
        opportunity_driversc,
        opportunity_idc,
        opportunity_numberc,
        opportunity_pull_throughc,
        opportunity_scopec,
        opportunity_structurec,
        opportunity_tierc,
        opportunity_winnerc,
        parent_opportunityc,
        payment_termsc,
        percent_variance_gm_hourc,
        percent_variance_gross_marginc,
        percent_variance_revenuec,
        percent_variance_work_hoursc,
        pipeline_factored_revenuec,
        previous_project_experiencec,
        previously_approved_b_pc,
        primary_cityc,
        primary_countryc,
        primary_locationc,
        primary_state_provincec,
        primary_streetc,
        primary_zip_postal_codec,
        prior_sales_leadc,
        program_newc,
        program_renewal_rebidc,
        project_categoriesc,
        project_rolec,
        project_statusc,
        proposal_due_datec,
        proposal_managerc,
        proposal_tracking_numberc,
        proposal_typec,
        proposed_period_of_performancec,
        rfp_datec,
        reason_lostc,
        rebid_opportunity_linkc,
        record_urlc,
        related_accounts_verifiedc,
        reporting_end_clientc,
        request_confidentialc,
        revenuec,
        revenue_to_date_newc,
        risk_level_categoryc,
        sec_codes_and_categoriesc,
        sales_plan_keyc,
        scope_of_servicesc,
        selling_unitc,
        service_type_codec,
        service_typec,
        sharepoint_site_requested_onc,
        sharepoint_urlc,
        sharepoint_site_requestorc,
        sharepoint_statusc,
        small_business_set_aside_typec,
        sold_gm_hrc,
        statusc,
        strategic_pipelinec,
        subcontractorsc,
        system_numberc,
        target_project_start_datec,
        task_order_newc,
        teammatesc,
        top_prospect_date_flaggedc,
        top_prospect_quarterc,
        top_prospectc,
        total_actual_b_pc,
        total_installed_cost_ticc,
        total_lifecycle_sales_costc,
        total_pending_b_pc,
        total_probable_gmc,
        total_requested_b_pc,
        variance_costc,
        variance_gm_hourc,
        variance_gross_marginc,
        variance_revenuec,
        wave_selling_unitc,
        win_strategy_outlinec,
        frm_my_business_unitc,
        frm_my_line_of_businessc,
        frm_txt_acct_billing_streetc,
        url_phasein_sharepointc,
        end_date_calculatedc,
        business_segmentc,
        lead_multi_office_start_datec,
        gbs_locationc,
        start_date_calculatedc,
        newco_synergy_not_approvedc,
        sales_plan_unitc,
        selling_line_of_businessc,
        selling_sales_regionc,
        selling_sectorc,
        sales_plan_unit_lob_textc,
        asset_typec,
        bid_no_bid_flagc,
        bid_officec,
        business_linec,
        crmt_opportunity_idc,
        crmt_opportunity_project_idc,
        crmt_sharepoint_linkc,
        contract_award_type_2c,
        contract_currencyc,
        country_of_asset_refc,
        country_of_assetc,
        executing_officec,
        gbs_project_numberc,
        gbs_proposal_numberc,
        newco_de_duplication_review_notesc,
        primary_billing_addressc,
        project_classificationc,
        project_phasec,
        risk_classificationc,
        specialtiesc,
        worley_capability_lead_subsectorc,
        worley_capability_sectorc,
        migrate_crmt_projectc,
        lead_global_service_linec,
        lead_service_linec,
        jv_jesa_geographyc,
        jv_jesa_sectorc,
        jv_jesa_servicec,
        jv_jesa_subsectorc,
        for_reconciliationc,
        owner_role_namec,
        selling_businessc,
        sync_role_namec,
        primary_billing_location_idc,
        primary_billing_location_statusc,
        risk_info_copied_fromc,
        ped_record_createdc,
        ecr_l0c,
        market_sector_l1c,
        market_segment_l3c,
        market_subsector_l2c,
        unit_l3_valuec,
        project_classification_audc,
        worley_legal_entityc,
        fileforcem1sharepoint_folder_idc,
        gph_sharepoint_folder_structurec,
        global_pursuit_hub_urlc,
        sharepoint_document_library_idc,
        override_opportunity_numberc,
        aggregate_gmc,
        gidc,
        gm_on_rev_minus_procurementc,
        psr_value_gmc,
        procurement_gm_percentc,
        professional_services_gm_percentc,
        jesa_client_typec,
        create_record_in_cleopatrac,
        us_government_fundingc,
        major_projectc,
        inside_sales_leadc,
        capture_manager_newc,
        link_to_eg_business_process_mapc,
        link_to_mg_business_process_mapc,
        consulting_pull_throughc,
        technology_pull_throughc,
        billing_addressc,
        create_project_experience_record_in_pedc,
        construction_fabrication_gm_percentc,
        CAST(active_projects2c AS FLOAT) AS active_projects2c,
        CAST(approved_bid_flagc AS FLOAT) AS approved_bid_flagc,
        CAST(award_fee_incentive_rev_audc AS FLOAT) AS award_fee_incentive_rev_audc,
        CAST(billable_hours_newc AS FLOAT) AS billable_hours_newc,
        CAST(budgeted_gm_hr_variancec AS FLOAT) AS budgeted_gm_hr_variancec,
        CAST(budgeted_gm_variancec AS FLOAT) AS budgeted_gm_variancec,
        CAST(budgeted_hours2c AS FLOAT) AS budgeted_hours2c,
        CAST(budgeted_revenue_variancec AS FLOAT) AS budgeted_revenue_variancec,
        CAST(close_date_adjustc AS FLOAT) AS close_date_adjustc,
        CAST(construction_fabrication_gm_audc AS FLOAT) AS construction_fabrication_gm_audc,
        CAST(construction_fabrication_gm_hr_audc AS FLOAT) AS construction_fabrication_gm_hr_audc,
        CAST(construction_fabrication_gmc AS FLOAT) AS construction_fabrication_gmc,
        CAST(construction_fabrication_hoursc AS FLOAT) AS construction_fabrication_hoursc,
        CAST(construction_fabrication_rev_audc AS FLOAT) AS construction_fabrication_rev_audc,
        CAST(construction_fabrication_revc AS FLOAT) AS construction_fabrication_revc,
        CAST(contract_gross_marginc AS FLOAT) AS contract_gross_marginc,
        CAST(contract_revenuec AS FLOAT) AS contract_revenuec,
        CAST(count_competitorsc AS FLOAT) AS count_competitorsc,
        CAST(count_of_cpcc AS FLOAT) AS count_of_cpcc,
        CAST(count_partnersc AS FLOAT) AS count_partnersc,
        CAST(duration_monthsc AS FLOAT) AS duration_monthsc,
        CAST(duration_weeksc AS FLOAT) AS duration_weeksc,
        CAST(exchange_rate_currentc AS FLOAT) AS exchange_rate_currentc,
        CAST(exchange_ratec AS FLOAT) AS exchange_ratec,
        CAST(factored_workhoursc AS FLOAT) AS factored_workhoursc,
        CAST(gross_margin_calculated_contractc AS FLOAT) AS gross_margin_calculated_contractc,
        CAST(gross_margin_calculated_corpc AS FLOAT) AS gross_margin_calculated_corpc,
        CAST(gross_margin_corpc AS FLOAT) AS gross_margin_corpc,
        CAST(home_office_gm_audc AS FLOAT) AS home_office_gm_audc,
        CAST(home_office_gmc AS FLOAT) AS home_office_gmc,
        CAST(newco_factored_gm_synergy_corpc AS FLOAT) AS newco_factored_gm_synergy_corpc,
        CAST(newco_factored_revenue_synergy_corpc AS FLOAT) AS newco_factored_revenue_synergy_corpc,
        CAST(newco_gm_change_corpc AS FLOAT) AS newco_gm_change_corpc,
        CAST(newco_realized_gm_synergy_corpc AS FLOAT) AS newco_realized_gm_synergy_corpc,
        CAST(newco_realized_revenue_synergy_corpc AS FLOAT) AS newco_realized_revenue_synergy_corpc,
        CAST(newco_revenue_change_corpc AS FLOAT) AS newco_revenue_change_corpc,
        CAST(nonbillable_hours_newc AS FLOAT) AS nonbillable_hours_newc,
        CAST(num_fiscal_week_close_datec AS FLOAT) AS num_fiscal_week_close_datec,
        CAST(number_of_months_calculatedc AS FLOAT) AS number_of_months_calculatedc,
        CAST(number_of_multi_office_splitsc AS FLOAT) AS number_of_multi_office_splitsc,
        CAST(opportunity_location_countc AS FLOAT) AS opportunity_location_countc,
        CAST(pipeline_factored_revenue_corpc AS FLOAT) AS pipeline_factored_revenue_corpc,
        CAST(previously_approved_b_p_corpc AS FLOAT) AS previously_approved_b_p_corpc,
        CAST(procurement_mark_up_audc AS FLOAT) AS procurement_mark_up_audc,
        CAST(procurement_mark_upc AS FLOAT) AS procurement_mark_upc,
        CAST(procurement_rev_at_zero_margin_audc AS FLOAT) AS procurement_rev_at_zero_margin_audc,
        CAST(procurement_rev_at_zero_marginc AS FLOAT) AS procurement_rev_at_zero_marginc,
        CAST(procurement_rev_audc AS FLOAT) AS procurement_rev_audc,
        CAST(procurement_revc AS FLOAT) AS procurement_revc,
        CAST(professional_services_gm_audc AS FLOAT) AS professional_services_gm_audc,
        CAST(professional_services_gm_hr_audc AS FLOAT) AS professional_services_gm_hr_audc,
        CAST(professional_services_gmc AS FLOAT) AS professional_services_gmc,
        CAST(professional_services_hoursc AS FLOAT) AS professional_services_hoursc,
        CAST(professional_services_rev_audc AS FLOAT) AS professional_services_rev_audc,
        CAST(projects_newc AS FLOAT) AS projects_newc,
        CAST(resource_type_mosc AS FLOAT) AS resource_type_mosc,
        CAST(revenue_calculated_contractc AS FLOAT) AS revenue_calculated_contractc,
        CAST(revenue_calculated_corpc AS FLOAT) AS revenue_calculated_corpc,
        CAST(revenue_corpc AS FLOAT) AS revenue_corpc,
        CAST(target_close_start_date_variancec AS FLOAT) AS target_close_start_date_variancec,
        CAST(total_actual_b_p_corpc AS FLOAT) AS total_actual_b_p_corpc,
        CAST(total_gid_hoursc AS FLOAT) AS total_gid_hoursc,
        CAST(total_installed_cost_tic_corpc AS FLOAT) AS total_installed_cost_tic_corpc,
        CAST(total_pending_b_p_corpc AS FLOAT) AS total_pending_b_p_corpc,
        CAST(total_probable_gm_corporatec AS FLOAT) AS total_probable_gm_corporatec,
        CAST(total_requested_b_p_corpc AS FLOAT) AS total_requested_b_p_corpc,
        CAST(totalopportunityquantity AS FLOAT) AS totalopportunityquantity,
        CAST(variance_hoursc AS FLOAT) AS variance_hoursc,
        CAST(work_hours_calculatedc AS FLOAT) AS work_hours_calculatedc,
        CAST(work_hoursc AS FLOAT) AS work_hoursc,
        --link_to_business_process_mapc,
        --additional_riskc,
        --agentsc,
        --comments_agentsc,
        --comments_ceo_approvalc,
        --comments_confidentiality_agreementc,
        --comments_dispute_resolutionc,
        --comments_exclusive_remedyc,
        --comments_fit_for_purposec,
        -- comments_form_of_securityc,
        -- comments_governing_lawc,
        -- comments_ip_at_riskc,
        -- comments_ip_usec,
        -- comments_nuclearc,
        -- comments_operational_controlc,
        -- comments_parent_guaranteesc,
        -- comments_payment_terms_reviewedc,
        -- comments_personal_datac,
        -- comments_sr10c,
        -- comments_sr11c,
        -- comments_sr11bfc,
        -- comments_sr12c,
        -- comments_sr13c,
        -- comments_sr14c,
        -- comments_sr15c,
        -- comments_sr16c,
        -- comments_sr17c,
        -- comments_sr18ac,
        -- comments_sr18bc,
        -- comments_sr19c,
        -- comments_sr1ac,
        -- comments_sr1bc,
        -- comments_sr20c,
        -- comments_sr20ec,
        -- comments_sr21abc,
        -- comments_sr21cc,
        -- comments_sr21dc,
        -- comments_sr21ec,
        -- comments_sr21e_newc,
        -- comments_sr2ac,
        -- comments_sr2bc,
        -- comments_sr2cc,
        -- comments_sr3c,
        -- comments_sr4c,
        -- comments_sr5c,
        -- comments_sr6c,
        -- comments_sr7c,
        -- comments_sr8c,
        -- comments_sr9c,
        -- comments_schedulec,
        -- comments_taxc,
        -- comments_terminationc,
        -- comments_capital_cost_estimatingc,
        -- comments_constructionc,
        -- comments_deferred_revenuec,
        -- comments_payments_requestedc,
        -- comments_social_licensec,
        --dispute_resolutionc,
        -- exclusive_remedyc,
        -- fit_for_purposec,
        -- form_of_securityc,
        -- governing_lawc,
        -- intellectual_property_use_by_other_partyc,
        -- intellectual_property_at_riskc,
        -- mitigation_additional_riskc,
        -- mitigation_sr10c,
        -- mitigation_sr11c,
        -- mitigation_sr11bfc,
        -- mitigation_sr12c,
        -- mitigation_sr13c,
        -- mitigation_sr14c,
        -- mitigation_sr15c,
        -- mitigation_sr16c,
        -- mitigation_sr17c,
        -- mitigation_sr18ac,
        -- mitigation_sr18bc,
        -- mitigation_sr19c,
        -- mitigation_sr1ac,
        -- mitigation_sr1bc,
        -- mitigation_sr20c,
        -- mitigation_sr20ec,
        -- mitigation_sr21abc,
        -- mitigation_sr21cc,
        -- mitigation_sr21dc,
        -- mitigation_sr21ec,
        -- mitigation_sr21e_newc,
        -- mitigation_sr2ac,
        -- mitigation_sr2bc,
        -- mitigation_sr2cc,
        -- mitigation_sr3c,
        -- mitigation_sr4c,
        -- mitigation_sr5c,
        -- mitigation_sr6c,
        -- mitigation_sr7c,
        -- mitigation_sr8c,
        -- mitigation_sr9c,
        -- nuclearc,
        -- operational_controlc,
        -- parent_guaranteesc,
        -- payment_terms_reviewed_by_financec,
        -- personal_data_protectionc,
        -- sr10_warranty_periodc,
        -- sr11_cash_managementc,
        -- sr11_other_cash_managementc,
        -- sr12_currency_exposurec,
        -- sr13_trade_compliancec,
        -- sr14_exclusivity_agreementsc,
        -- sr15_restrictive_practicesc,
        -- sr16_teaming_agreementsc,
        -- sr17_procurement_on_worley_paperc,
        -- sr18a_check_engineeringc,
        -- sr18b_endorsing_3rd_party_informationc,
        -- sr19_due_diligence_engineeringc,
        -- sr1a_services_outside_core_competencyc,
        -- sr1b_unproven_technologyc,
        -- sr20_risky_customer_project_financialc,
        -- sr20e_doubtful_creditworthinessc,
        -- sr21ab_risky_customer_project_ethicalc,
        -- sr21c_coal_processingc,
        -- sr21d_negative_media_coveragec,
        -- sr21e_industry_body_or_special_interestc,
        -- sr21e_loss_of_biodiversityc,
        -- sr2a_high_hse_riskc,
        -- sr2b_extreme_risk_country_r3c,
        -- sr2c_non_operating_countryc,
        -- sr3_indemnitiesc,
        -- sr4_project_specific_insurancec,
        -- sr5_consequential_damagesc,
        -- sr6_overall_limit_of_liabilityc,
        -- sr7_liquidated_damagesc,
        -- sr8_performance_guaranteesc,
        -- sr9_defective_servicesc,
        -- schedulec,
        -- taxc,
        -- terminationc,
        cast(execution_date as date) as etl_load_date,
        CAST({{ run_date }} AS TIMESTAMP) AS model_created_date,
        CAST({{ run_date }} AS TIMESTAMP) AS model_updated_date,
        {{ generate_load_id(model) }} as model_load_id	
        from sfco_cdc
)

SELECT  * FROM sfco_data
