{{
     config(
         materialized = "table",
         tags=["supply_chain"]
     )

}}


SELECT 
    DISTINCT cast(proj_no as integer) as project_no,
    cast(project as varchar(100)) as project_id,
    req_no as tmr_number,
    purchase_order_no as po_number,
    cust_po_no as customer_po,
    cast(revision as integer) as latest_rev,
    tag_number as tag_number,
    supplier as supplier,
    expeditor as expediter,
    purchase_order_descr as "Description",
    item_description as item_description,
    cast(order_qty as integer) as order_qty,
    cast(outstanding_qty as integer) as outstanding_qty,
    incoterm_delivery_place as incoterm,
    delivery_place as delivery_location,
    delivery_designation as delivery_site,
    po_first_issue_date as po_1st_issue,
    next_contact_date as next_contact_date,
    prom_contract_date as contract_delivery_date,
    forecast_delivery_date as forecast_delivery_date,
    issue_date as latest_issue_date,
    forecast_arrival_on_site as forecast_arrival_on_site,
    ros as exp_ros,
    cast(floats as integer) as ros_float,
    cast(delays as integer) as delivery_float,
    cast(line_item_count as integer) as total_exp_items,
    comnt as expediting_comments,
    project_region as project_region,
    buyer_name as buyer,
    commopodity_code_tag_number as commodityCode,
    gen_mto_cwp as cwp,
    delivery_type as delivery_type,
    early_prom_contract_date as earliest_contract_delivery_date,
    early_forecast_arri_on_site as earliest_forecast_arrival_date,
    early_forecast_del_date as earliest_forecast_delivery_date,
    cast(earliest_ros_date as date) as earliest_ros,
    expedite_occurrence as eo,
    cast(expedite_quan as integer) as exp_qty,
    first_shipping_actual as first_shipping_actual,
    gen_att as general_attribute,
    inspector as inspector,
    l_comments as item_comments,
    s_item_no as itemno,
    last_contact_date as last_contact_date,
    mrr_date as mrr_date,
    mrr_no as mrr_number,
    cast(mrr_qty as integer) as mrr_qty,
    cast(order_pos_sub as integer) as order_position,
    size1 as size1,
    size2 as size2,
    size3 as size3,
    cast(supplementary_item_occurrence as integer) as so,
    mmt_approved_date as srn_date,
    srn_no as srn_no,
    cast(srn_qty as integer) as srn_qty,
    sub_project as subproject,
    cast(total_received_to_date as integer) as total_received,
    unit_id as uom,
    arrival_on_site_actual,
    etl_load_date as dataset_refershed_date,
    COALESCE(project_id, 'default_req') || '_' ||COALESCE(po_number, 'default_req')  AS project_po
from
     {{ source('supply_chain_dim', 'transformed_erm_esr_data') }}