{{
     config(
         materialized = "table",
         tags=["supply_chain"]
     )

}}

SELECT
    DISTINCT project_id,
    po_number,
    po_creation_date,
    title,
    client,
    supplier_location,
    po_issue_date,
    purchase_order_line_item_internal_id,
    po_line_number,
    po_line_quantity,
    promised_date,
    incoterm_tax_terms,
    code_of_account,
    item_tag,
    item_description,
    req_creation_date,
    received_quantity,
    polt_v1,
    cast(po_approval_time as integer) as po_approval_time,
    po_stts_flag,
    unspsc,
    worley_project_region,
    project_sub_region,
    project_country,
    worley_project_office,
    sector,
    paper,
    catg_supplier,
    erm_supplier_country,
    group_l1,
    category_l2,
    sub_category_l3,
    family_l4,
    sub_project,
    cast(req_processing_time as integer) as req_processing_time ,
    gross_value,
    CAST(usd_conv as integer) as usd_conv,
    usd_line_total_conv,
    usd_line_unit_conv,
    po_range_filter,
    EXTRACT(year FROM po_issue_date) as po_issue_date_year,
    EXTRACT(month FROM po_issue_date) as po_issue_date_month,
    'Qtr '|| EXTRACT(quarter FROM po_issue_date) as po_issue_date_quarter,
    to_char(po_issue_date , 'Month') as po_issue_date_month_name,
    EXTRACT(year FROM received_date) as received_date_year,
    EXTRACT(month FROM received_date) as received_date_month,
    'Qtr '|| EXTRACT(quarter FROM received_date) as received_date_quarter,
    to_char(received_date , 'Month') as received_date_month_name,
    data_refreshed_date
from {{ ref('erm_procurement_obt') }}
