{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False',
        custom_location=target.location ~ 'oracle_p6/transformed_p6_project_resourceassignment/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["p6", "v2"]
        )
}}

SELECT 
activityid as activityid,
activityactualfinish as activityactualfinish,
activityname as activityname,
activityobjectid as activityobjectid,
objectid as activityspreadobjectid,
activitytype as activitytype,
actualcost as actualcost,
-- actualcurve as actualcurve,
actualduration as actualduration,
actualfinishdate as actualfinishdate,
actualovertimecost as actualovertimecost,
actualovertimeunits as actualovertimeunits,
actualregularcost as actualregularcost,
actualregularunits as actualregularunits,
actualstartdate as actualstartdate,
actualthisperiodcost as actualthisperiodcost,
actualthisperiodunits as actualthisperiodunits,
actualunits as actualunits,
assignmentpercentcomplete as assignmentpercentcomplete,
atcompletioncost as atcompletioncost,
atcompletionduration as atcompletionduration,
atcompletionunits as atcompletionunits,
autocomputeactuals as autocomputeactuals,
-- budgetatcompletioncosts as budgetatcompletioncosts,
-- budgetatcompletionunits as budgetatcompletionunits,
cbscode as cbscode,
cbsid as cbsid,
calendarname as calendarname,
calendarobjectid as calendarobjectid,
-- costaccountid as costaccountid,
-- costaccountname as costaccountname,
-- costaccountobjectid as costaccountobjectid,
createdate as createdate,
createuser as createuser,
drivingactivitydatesflag as drivingactivitydatesflag,
durationpercentcomplete as durationpercentcomplete,
-- estimatetocompletioncosts as estimatetocompletioncosts,
-- estimatetocompletionunits as estimatetocompletionunits,
financialperiodtmplid as financialperiodtmplid,
finishdate as finishdate,
guid as guid,
hasfuturebucketdata as hasfuturebucketdata,
isactive as isactive,
isactivityflagged as isactivityflagged,
isbaseline as isbaseline,
iscostunitslinked as iscostunitslinked,
isovertimeallowed as isovertimeallowed,
isprimaryresource as isprimaryresource,
istemplate as istemplate,
lastupdatedate as lastupdatedate,
lastupdateuser as lastupdateuser,
-- overtimefactor as overtimefactor,
-- pendingactualovertimeunits as pendingactualovertimeunits,
-- pendingactualregularunits as pendingactualregularunits,
-- pendingpercentcomplete as pendingpercentcomplete,
-- pendingremainingunits as pendingremainingunits,
percentcomplete as percentcomplete,
percentcompletetype as percentcompletetype,
plannedcost as plannedcost,
-- plannedcurve as plannedcurve,
plannedduration as plannedduration,
plannedfinishdate as plannedfinishdate,
plannedlag as plannedlag,
plannedstartdate as plannedstartdate,
plannedunits as plannedunits,
plannedunitspertime as plannedunitspertime,
priceperunit as priceperunit,
-- prioractualovertimeunits as prioractualovertimeunits,
-- prioractualregularunits as prioractualregularunits,
proficiency as proficiency,
projectflag as projectflag,
project_id as project_id,
projectname as projectname,
projectobjectid as projectobjectid,
projectprojectflag as projectprojectflag,
ratesource as ratesource,
ratetype as ratetype,
remainingcost as remainingcost,
-- remainingcurve as remainingcurve,
remainingduration as remainingduration,
remainingfinishdate as remainingfinishdate,
remaininglag as remaininglag,
remaininglatefinishdate as remaininglatefinishdate,
remaininglatestartdate as remaininglatestartdate,
remainingstartdate as remainingstartdate,
remainingunits as remainingunits,
remainingunitspertime as remainingunitspertime,
resourcecalendarname as resourcecalendarname,
-- resourcecurvename as resourcecurvename,
-- resourcecurveobjectid as resourcecurveobjectid,
resourceid as resourceid,
resourcename as resourcename,
resourceobjectid as resourceobjectid,
resourcetype as resourcetype,
reviewrequired as reviewrequired,
-- roleid as roleid,
-- rolename as rolename,
-- roleobjectid as roleobjectid,
-- roleshortname as roleshortname,
staffedremainingcost as staffedremainingcost,
staffedremainingunits as staffedremainingunits,
startdate as startdate,
statuscode as statuscode,
totalpastperiodcost as totalpastperiodcost,
totalpastperiodunits as totalpastperiodunits,
unitspercentcomplete as unitspercentcomplete,
unreadcommentcount as unreadcommentcount,
unstaffedremainingcost as unstaffedremainingcost,
unstaffedremainingunits as unstaffedremainingunits,
wbsnamepath as wbsnamepath,
wbsobjectid as wbsobjectid,
projectid as projectid,
cast(execution_date as date),
{{run_date}} as created_date,
{{run_date}} as updated_date,
{{ generate_load_id(model) }} as load_id
FROM
{{ source('curated_p6', 'curated_project_resourceassignment') }}
