{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False',
        custom_location=target.location ~ 'oracle_p6/transformed_p6_project_resourceassignmentspread/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["p6", "v2"]
        )
}}

select
activityid as activityid,
resourceassignmentobjectid as resourceassignmentobjectid,
startdate as startdate,
enddate as enddate,
periodtype as periodtype,
period_startdate as period_startdate,
period_enddate as period_enddate,
actuallaborunits as actuallaborunits,
activityowneruserid as activityowneruserid,
cbscode as cbscode,
cbsid as cbsid,
externalearlystartdate as externalearlystartdate,
externallatefinishdate as externallatefinishdate,
feedback as feedback,
floatpath as floatpath,
floatpathorder as floatpathorder,
hasfuturebucketdata as hasfuturebucketdata,
locationname as locationname,
locationobjectid as locationobjectid,
maximumduration as maximumduration,
minimumduration as minimumduration,
mostlikelyduration as mostlikelyduration,
notestoresources as notestoresources,
owneridarray as owneridarray,
ownernamesarray as ownernamesarray,
postrespcriticalityindex as postrespcriticalityindex,
postresponsepessimisticfinish as postresponsepessimisticfinish,
postresponsepessimisticstart as postresponsepessimisticstart,
prerespcriticalityindex as prerespcriticalityindex,
preresponsepessimisticfinish as preresponsepessimisticfinish,
preresponsepessimisticstart as preresponsepessimisticstart,
primaryconstraintdate as primaryconstraintdate,
projectid as projectid,
resumedate as resumedate,
reviewfinishdate as reviewfinishdate,
secondaryconstraintdate as secondaryconstraintdate,
suspenddate as suspenddate,
taskstatusindicator as taskstatusindicator,
workpackageid as workpackageid,
period_actualcost as period_actualcost,
period_actualovertimecost as period_actualovertimecost,
period_actualovertimeunits as period_actualovertimeunits,
period_actualregularcost as period_actualregularcost,
period_actualregularunits as period_actualregularunits,
period_actualunits as period_actualunits,
period_atcompletioncost as period_atcompletioncost,
period_atcompletionunits as period_atcompletionunits,
period_plannedcost as period_plannedcost,
period_plannedunits as period_plannedunits,
period_remainingcost as period_remainingcost,
period_remaininglatecost as period_remaininglatecost,
period_remaininglateunits as period_remaininglateunits,
period_remainingunits as period_remainingunits,
period_staffedremainingcost as period_staffedremainingcost,
period_staffedremaininglatecost as period_staffedremaininglatecost,
period_staffedremaininglateunits as period_staffedremaininglateunits,
period_staffedremainingunits as period_staffedremainingunits,
period_unstaffedremainingcost as period_unstaffedremainingcost,
period_unstaffedremaininglatecost as period_unstaffedremaininglatecost,
period_unstaffedremaininglateunits as period_unstaffedremaininglateunits,
period_unstaffedremainingunits as period_unstaffedremainingunits,
period_periodactualcost as period_periodactualcost,
period_periodactualunits as period_periodactualunits,
period_periodatcompletioncost as period_periodatcompletioncost,
period_periodatcompletionunits as period_periodatcompletionunits,
period_cumulativeactualcost as period_cumulativeactualcost,
period_cumulativeactualovertimecost as period_cumulativeactualovertimecost,
period_cumulativeactualovertimeunits as period_cumulativeactualovertimeunits,
period_cumulativeactualregularcost as period_cumulativeactualregularcost,
period_cumulativeactualregularunits as period_cumulativeactualregularunits,
period_cumulativeactualunits as period_cumulativeactualunits,
period_cumulativeatcompletioncost as period_cumulativeatcompletioncost,
period_cumulativeatcompletionunits as period_cumulativeatcompletionunits,
period_cumulativeplannedcost as period_cumulativeplannedcost,
period_cumulativeplannedunits as period_cumulativeplannedunits,
period_cumulativeremainingcost as period_cumulativeremainingcost,
period_cumulativeremaininglatecost as period_cumulativeremaininglatecost,
period_cumulativeremaininglateunits as period_cumulativeremaininglateunits,
period_cumulativeremainingunits as period_cumulativeremainingunits,
period_cumulativestaffedremainingcost as period_cumulativestaffedremainingcost,
period_cumulativestaffedremaininglatecost as period_cumulativestaffedremaininglatecost,
period_cumulativestaffedremaininglateunits as period_cumulativestaffedremaininglateunits,
period_cumulativestaffedremainingunits as period_cumulativestaffedremainingunits,
period_cumulativeunstaffedremainingcost as period_cumulativeunstaffedremainingcost,
period_cumulativeunstaffedremaininglatecost as period_cumulativeunstaffedremaininglatecost,
period_cumulativeunstaffedremaininglateunits as period_cumulativeunstaffedremaininglateunits,
period_cumulativeunstaffedremainingunits as period_cumulativeunstaffedremainingunits,
project_id as project_id,
source_system_name as source_system_name,
cast(execution_date as date),
{{run_date}} as created_date,
{{run_date}} as updated_date,
{{ generate_load_id(model) }} as load_id
FROM
{{ source('curated_p6', 'curated_project_resourceassignmentspread') }}