{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False',
        custom_location=target.location ~ 'oracle_p6/transformed_p6_activity/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["p6", "v2"]
        )
}}

select 
    '' as activity_pk,
    accountingvariance,
    accountingvariancelaborunits,
    activityowneruserid,
    cast(actualduration as float) as actualduration,
    actualexpensecost,
    cast(actualfinishdate as timestamp) as actualfinishdate,
    actuallaborcost,
    actuallaborunits,
    actualmaterialcost,
    actualnonlaborcost,
    actualnonlaborunits,
    cast(actualstartdate as timestamp) as actualstartdate,
    actualthisperiodlaborcost,
    actualthisperiodlaborunits,
    actualthisperiodmaterialcost,
    actualthisperiodnonlaborcost,
    actualthisperiodnonlaborunits,
    actualtotalcost,
    actualtotalunits,
    atcompletionduration,
    atcompletionexpensecost,
    atcompletionlaborcost,
    atcompletionlaborunits,
    atcompletionlaborunitsvariance,
    atcompletionmaterialcost,
    atcompletionnonlaborcost,
    atcompletionnonlaborunits,
    atcompletiontotalcost,
    atcompletiontotalunits,
    atcompletionvariance,
    autocomputeactuals,
    baseline1duration,
    baseline1finishdate,
    baseline1plannedduration,
    baseline1plannedexpensecost,
    baseline1plannedlaborcost,
    baseline1plannedlaborunits,
    baseline1plannedmaterialcost,
    baseline1plannednonlaborcost,
    baseline1plannednonlaborunits,
    '' as baseline1plannedtotalcost,
    baseline1startdate,
    baseline2duration,
    baseline2finishdate,
    baseline2plannedduration,
    baseline2plannedexpensecost,
    baseline2plannedlaborcost,
    baseline2plannedlaborunits,
    baseline2plannedmaterialcost,
    baseline2plannednonlaborcost,
    baseline2plannednonlaborunits,
    baseline2plannedtotalcost,
    baseline2startdate,
    baseline3duration,
    baseline3finishdate,
    baseline3plannedduration,
    baseline3plannedexpensecost,
    baseline3plannedlaborcost,
    baseline3plannedlaborunits,
    baseline3plannedmaterialcost,
    baseline3plannednonlaborcost,
    baseline3plannednonlaborunits,
    baseline3plannedtotalcost,
    baseline3startdate,
    cast(baselineduration as float) as baselineduration,
    cast(baselinefinishdate as timestamp) as baselinefinishdate,
    baselineplannedduration,
    baselineplannedexpensecost,
    baselineplannedlaborcost,
    baselineplannedlaborunits,
    baselineplannedmaterialcost,
    baselineplannednonlaborcost,
    baselineplannednonlaborunits,
    baselineplannedtotalcost,
    cast(baselinestartdate as timestamp) as baselinestartdate,
    budgetatcompletion,
    cbscode,
    cbsid,
    cbsobjectid,
    calendarname,
    calendarobjectid,
    costpercentcomplete,
    costpercentofplanned,
    costperformanceindex,
    costperformanceindexlaborunits,
    costvariance,
    costvarianceindex,
    costvarianceindexlaborunits,
    costvariancelaborunits,
    cast(createdate as date) as createdate,
    createuser,
    cast(datadate as timestamp) as datadate,
    duration1variance,
    duration2variance,
    duration3variance,
    durationpercentcomplete,
    durationpercentofplanned,
    durationtype,
    durationvariance,
    cast(earlyfinishdate as timestamp) as earlyfinishdate,
    cast(earlystartdate as timestamp) as earlystartdate,
    earnedvaluecost,
    earnedvaluelaborunits,
    estimateatcompletioncost,
    estimateatcompletionlaborunits,
    estimatetocomplete,
    estimatetocompletelaborunits,
    estimatedweight,
    expectedfinishdate,
    expensecost1variance,
    expensecost2variance,
    expensecost3variance,
    expensecostpercentcomplete,
    expensecostvariance,
    externalearlystartdate,
    externallatefinishdate,
    feedback,
    financialperiodtmplid,
    cast(finishdate as timestamp) as finishdate,
    finishdate1variance,
    finishdate2variance,
    finishdate3variance,
    cast(finishdatevariance as float) as finishdatevariance,
    floatpath,
    floatpathorder,
    cast(freefloat as float) as freefloat,
    guid,
    hasfuturebucketdata,
    id,
    isbaseline,
    iscritical,
    islongestpath,
    isnewfeedback,
    isstarred,
    istemplate,
    isworkpackage,
    laborcost1variance,
    laborcost2variance,
    laborcost3variance,
    laborcostpercentcomplete,
    laborcostvariance,
    laborunits1variance,
    laborunits2variance,
    laborunits3variance,
    laborunitspercentcomplete,
    laborunitsvariance,
    cast(lastupdatedate as date) as lastupdatedate,
    lastupdateuser,
    cast(latefinishdate as timestamp) as latefinishdate,
    cast(latestartdate as timestamp) as latestartdate,
    levelingpriority,
    locationname,
    locationobjectid,
    materialcost1variance,
    materialcost2variance,
    materialcost3variance,
    materialcostpercentcomplete,
    materialcostvariance,
    maximumduration,
    minimumduration,
    mostlikelyduration,
    name,
    nonlaborcost1variance,
    nonlaborcost2variance,
    nonlaborcost3variance,
    nonlaborcostpercentcomplete,
    nonlaborcostvariance,
    nonlaborunits1variance,
    nonlaborunits2variance,
    nonlaborunits3variance,
    nonlaborunitspercentcomplete,
    nonlaborunitsvariance,
    notestoresources,
    cast(objectid as int) as objectid,
    owneridarray,
    ownernamesarray,
    percentcomplete,
    percentcompletetype,
    performancepercentcomplete,
    performancepercentcompletebylaborunits,
    physicalpercentcomplete,
    cast(plannedduration as float) as plannedduration,
    plannedexpensecost,
    cast(plannedfinishdate as date) plannedfinishdate,
    plannedlaborcost,
    plannedlaborunits,
    plannedmaterialcost,
    plannednonlaborcost,
    plannednonlaborunits,
    cast(plannedstartdate as date) plannedstartdate,
    plannedtotalcost,
    plannedtotalunits,
    plannedvaluecost,
    plannedvaluelaborunits,
    postrespcriticalityindex,
    postresponsepessimisticfinish,
    postresponsepessimisticstart,
    prerespcriticalityindex,
    preresponsepessimisticfinish,
    preresponsepessimisticstart,
    primaryconstraintdate,
    primaryconstrainttype,
    primaryresourceid,
    primaryresourcename,
    primaryresourceobjectid,
    projectflag,
    projectid,
    projectname,
    projectnamesepchar,
    cast(projectobjectid as int) as projectobjectid,
    projectprojectflag,
    cast(remainingduration as float) as remainingduration,
    cast(remainingearlyfinishdate as timestamp) as remainingearlyfinishdate,
    cast(remainingearlystartdate as timestamp) as remainingearlystartdate,
    remainingexpensecost,
    cast(remainingfloat as float) as remainingfloat,
    remaininglaborcost,
    remaininglaborunits,
    cast(remaininglatefinishdate as timestamp) as remaininglatefinishdate,
    cast(remaininglatestartdate as timestamp) as remaininglatestartdate,
    remainingmaterialcost,
    remainingnonlaborcost,
    remainingnonlaborunits,
    remainingtotalcost,
    remainingtotalunits,
    resumedate,
    reviewfinishdate,
    reviewrequired,
    reviewstatus,
    schedulepercentcomplete,
    scheduleperformanceindex,
    scheduleperformanceindexlaborunits,
    schedulevariance,
    schedulevarianceindex,
    schedulevarianceindexlaborunits,
    schedulevariancelaborunits,
    scopepercentcomplete,
    secondaryconstraintdate,
    secondaryconstrainttype,
    cast(startdate as timestamp) as startdate,
    startdate1variance,
    startdate2variance,
    startdate3variance,
    cast(startdatevariance as float) as startdatevariance,
    status,
    statuscode,
    suspenddate,
    taskstatuscompletion,
    taskstatusdates,
    taskstatusindicator,
    tocompleteperformanceindex,
    totalcost1variance,
    totalcost2variance,
    totalcost3variance,
    totalcostvariance,
    cast(totalfloat as float) as totalfloat,
    totalpastperiodearnedvaluecostbcwp,
    totalpastperiodearnedvaluelaborunits,
    totalpastperiodexpensecost,
    totalpastperiodlaborcost,
    totalpastperiodlaborunits,
    totalpastperiodmaterialcost,
    totalpastperiodnonlaborcost,
    totalpastperiodnonlaborunits,
    totalpastperiodplannedvaluecost,
    totalpastperiodplannedvaluelaborunits,
    type,
    unitspercentcomplete,
    unreadcommentcount,
    wbscode,
    wbsname,
    wbsnamepath,
    wbsobjectid,
    wbspath,
    workpackageid,
    '' as workpackagename,
    '' as etl_job_status_pk,
    '' as active_indicator,
    '' as created_by,
    '' as updated_by,
    execution_date as extracted_date,
    'VGCP2' as project_code,
    {{run_date}} as created_date,
    {{run_date}} as updated_date,
    {{ generate_load_id(model) }} as load_id
FROM
{{ source('curated_p6', 'curated_project_activity') }}
