{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False',
        custom_location=target.location ~ 'oracle_p6/transformed_p6_resource/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["p6", "v2"]
        )
}}

SELECT 
activityid as activity_key,
activityid as activity_val_id,
activityowneruserid as activityowneruserid,
actuallaborunits as actuallaborunits,
autocomputeactuals as autocomputeactuals,
calculatecostfromunits as calculatecostfromunits,
calendarname as calendarname,
calendarobjectid as calendarobjectid,
cbscode as cbscode,
cbsid as cbsid,
createdate as createdate,
createuser as createuser,
currencyid as currencyid,
currencyname as currencyname,
currencyobjectid as currencyobjectid,
defaultunitspertime as defaultunitspertime,
externalearlystartdate as externalearlystartdate,
externallatefinishdate as externallatefinishdate,
feedback as feedback,
floatpath as floatpath,
floatpathorder as floatpathorder,
guid as guid,
hasfuturebucketdata as hasfuturebucketdata,
id as id,
integratedtype as integratedtype,
isactive as isactive,
isovertimeallowed as isovertimeallowed,
lastupdatedate as lastupdatedate,
lastupdateuser as lastupdateuser,
locationname as locationname,
locationobjectid as locationobjectid,
maximumduration as maximumduration,
maxunitspertime as maxunitspertime,
minimumduration as minimumduration,
mostlikelyduration as mostlikelyduration,
name as name,
notestoresources as notestoresources,
objectid as objectid,
overtimefactor as overtimefactor,
owneridarray as owneridarray,
ownernamesarray as ownernamesarray,
parentobjectid as parentobjectid,
postrespcriticalityindex as postrespcriticalityindex,
postresponsepessimisticfinish as postresponsepessimisticfinish,
postresponsepessimisticstart as postresponsepessimisticstart,
prerespcriticalityindex as prerespcriticalityindex,
preresponsepessimisticfinish as preresponsepessimisticfinish,
preresponsepessimisticstart as preresponsepessimisticstart,
priceperunit as priceperunit,
primaryconstraintdate as primaryconstraintdate,
primaryroleid as primaryroleid,
primaryrolename as primaryrolename,
primaryroleobjectid as primaryroleobjectid,
project_id as project_id,
projectid as projectid,
resourcenotes as resourcenotes,
resourcetype as resourcetype,
resumedate as resumedate,
reviewfinishdate as reviewfinishdate,
secondaryconstraintdate as secondaryconstraintdate,
sequencenumber as sequencenumber,
source_system_name as source_system_name,
suspenddate as suspenddate,
taskstatusindicator as taskstatusindicator,
usetimesheets as usetimesheets,
workpackageid as workpackageid,
cast(null as string) as workpackagename,
cast(execution_date as date),
{{run_date}} as created_date,
{{run_date}} as updated_date,
{{ generate_load_id(model) }} as load_id
FROM
{{ source('curated_p6', 'curated_resource') }}
