databases_configs:
  - database_name: global_standard_reporting
    external_schema:
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_document_control_transformed
        external_schema_name: document_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_supply_chain_transformed
        external_schema_name: supply_chain_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_construction_transformed
        external_schema_name: construction_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_project_control_transformed
        external_schema_name: project_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_finance_transformed
        external_schema_name: finance_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_engineering_transformed
        external_schema_name: engineering_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_health_safety_environment_transformed
        external_schema_name: health_safety_environment_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_circuit_breaker_transformed
        external_schema_name: circuit_breaker_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_customer_csp_salesforce_transformed
        external_schema_name: customer_product
        access_via_odbc: true # optional: grant external schema access to human roles
    product_schema:
      - document_control
      - construction
      - supply_chain
      - engineering
      - project_control
      - finance
      - circuit_breaker
      - customer
      - health_safety_environment
      - snowflake_model
  - database_name: integrations
    external_schema:
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_document_control_transformed
        external_schema_name: document_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_supply_chain_transformed
        external_schema_name: supply_chain_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_construction_transformed
        external_schema_name: construction_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_project_control_transformed
        external_schema_name: project_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_finance_transformed
        external_schema_name: finance_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_engineering_transformed
        external_schema_name: engineering_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_health_safety_environment_transformed
        external_schema_name: health_safety_environment_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_circuit_breaker_transformed
        external_schema_name: circuit_breaker_product
        access_via_odbc: true # optional: grant external schema access to human roles
    product_schema:
      - document_control
      - construction
      - supply_chain
      - engineering
      - project_control
      - finance
      - health_safety_environment
      - circuit_breaker
  - database_name: dac
    external_schema:
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_dac_document_control_transformed
        external_schema_name: document_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      # - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_dac_supply_chain_transformed
      #   external_schema_name: supply_chain_product
      #   access_via_odbc: true # optional: grant external schema access to human roles
      # - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_dac_construction_transformed
      #   external_schema_name: construction_product
      #   access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_dac_project_control_transformed
        external_schema_name: project_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      # - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_dac_finance_transformed
      #   external_schema_name: finance_product
      #   access_via_odbc: true # optional: grant external schema access to human roles
    product_schema:
      - document_control
      - construction
      - supply_chain
      - project_control
      - finance
  - database_name: worley_nerve_center
    external_schema:
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_document_control_transformed
        external_schema_name: document_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_supply_chain_transformed
        external_schema_name: supply_chain_product
        access_via_odbc: true # optional: grant external schema access to human roles
      # - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_construction_transformed
      #   external_schema_name: construction_product
      #   access_via_odbc: true # optional: grant external schema access to human roles
      - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_project_control_transformed
        external_schema_name: project_control_product
        access_via_odbc: true # optional: grant external schema access to human roles
      # - glue_db_name: worley_datalake_sydney_dev_glue_catalog_database_finance_transformed
      #   external_schema_name: finance_product
      #   access_via_odbc: true # optional: grant external schema access to human roles
    product_schema:
      - document_control
      - supply_chain
      - project_control