
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'engineering_domain_model'
version: '1.0.0'


vars:
  curated_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_e3d_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_e3d_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_e3d_curated"
    
  curated_spel_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_spel_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_spel_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_spel_curated"    
    
  curated_isotracker_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_isotracker_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_isotracker_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_isotracker_curated"    
    
  curated_omie_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_omie_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_omie_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_omie_curated"   


  curated_spi_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_spi_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_spi_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_spi_curated"      
    
  curated_engreg_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_engreg_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_engreg_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_engreg_curated"  

  curated_aim_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_aim_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_aim_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_aim_curated"  

  curated_mps_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_mps_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_mps_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_mps_curated"  

  curated_mel_schema:
    dev: "worley_datalake_sydney_dev_glue_catalog_database_engineering_mel_curated"
    qa: "worley_datalake_sydney_qa_glue_catalog_database_engineering_mel_curated"
    prd: "worley_datalake_sydney_prd_glue_catalog_database_engineering_mel_curated" 
    
# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_engineering'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  engineering_domain_model:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: table
      +depends_on:
        - model.transformed_audit_table       

on-run-end:
# add run results to audit table
  - "{{ log_audit_table(results) }}" 
