version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oracleapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mb4ol2mz6xqp"
s3_prefix = "oracleapi"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
