redshift_permissions_config:
  - database_name: dac
    ad_roles:
      - role_name: AWS-PIM - DAC Data Curator
        identity_provider: AAD
        quicksight_role: quicksight # optional: only for AWS identity provider
        # redshift_role: redshift permissions are default
        # emr_studio_role: check and confirmif the use case exists
        allowed_schemas:
          - name: document_control  #Product Schema starts here
          - name: supply_chain
          - name: construction
          - name: project_control
          - name: finance
          - name: document_control_product   #dim Schema starts here
          - name: project_control_product
          # - name: finance_product
          # - name: engineering_product
          # - name: customer_product
          # - name: health_safety_environment_product
      - role_name: AWS-PIM - DAC Data Curator
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        # redshift_role: redshift permissions are default
        # emr_studio_role: check and confirmif the use case exists
        allowed_schemas:
          - name: document_control  #Product Schema starts here
          - name: supply_chain
          - name: construction
          - name: project_control
          - name: finance
          - name: document_control_product   #dim Schema starts here
          - name: project_control_product
          # - name: finance_product
          # - name: engineering_product
          # - name: customer_product
          # - name: health_safety_environment_product
    iam_roles:
    users:
      - user_name: dbt_dac_user
        identity_provider: internal
        allowed_schemas:
          - name: dbt_document_control_product # default: usage and select permissions are granted
          - name: dbt_project_control_product
          # - name: dbt_finance_product
          - name: document_control
            permissions: CREATE
          - name: project_control
            permissions: CREATE
          # - name: finance
          #   permissions: CREATE # optional: specify this if create on schema permission is required
      - user_name: api_dac_user
        identity_provider: internal
        allowed_schemas:
          - name: document_control

### NOTE: DON'T GIVE AAD access to external schema

### HOW TO REVOKE A ROLE'S ACCESS TO A SCHEMA, USE THE FLAG "ACTIVE" AND SET TO FALSE, e.g.
      # - role_name: AWS-PIM - DataPlatform Data Engineer - Non Prod
      #   identity_provider: AWSIDC
      #   quicksight_role: quicksight # optional: only for AWS identity provider
      #   allowed_schemas:
      #     - name: document_control
      #       active: false 