### NOTE: DON'T GIVE AAD access to external schema

### HOW TO REVOKE A ROLE'S ACCESS TO A SCHEMA, USE THE FLAG "ACTIVE" AND SET TO FALSE, e.g.
      # - role_name: AWS-PIM - DataPlatform Data Engineer - Non Prod
      #   identity_provider: AWSIDC
      #   quicksight_role: quicksight # optional: only for AWS identity provider
      #   allowed_schemas:
      #     - name: document_control
      #       active: false


redshift_permissions_config:
  - database_name: global_standard_reporting
    ad_roles:
      - role_name: AWS-PIM - Dataplatform GSD BI Consumer - NonProd
        # Power BI should not have access to PRODUCT
        identity_provider: AAD # required: AWSIDC | AAD | internal
        allowed_schemas:
          - name: document_control # fact/obt Schema starts here # default: usage and select permissions are granted 
          - name: supply_chain
          - name: construction
          - name: project_control
          - name: finance
          - name: engineering
          - name: health_safety_environment
          - name: customer
      - role_name: AWS-PIM - DataPlatform Data Engineer - Non Prod
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        # redshift_role: redshift permissions are default
        # emr_studio_role: check and confirmif the use case exists
        allowed_schemas:
          - name: document_control  #fact/obt Schema starts here
          - name: supply_chain
          - name: construction
          - name: project_control
          - name: finance
          - name: engineering
          - name: customer
          - name: circuit_breaker
          - name: health_safety_environment
          - name: document_control_product   #product Schema starts here
          - name: supply_chain_product
          - name: construction_product
          - name: project_control_product
          - name: finance_product
          - name: engineering_product
          - name: circuit_breaker_product
          - name: customer_product
          - name: health_safety_environment_product
      - role_name: AWS-PIM - DataPlatform Data Consumer - NonProd
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        allowed_schemas:
          - name: document_control    #fact/obt Schema starts here
          - name: supply_chain
          - name: construction
          - name: project_control
          - name: finance
          - name: engineering
          - name: customer
          - name: health_safety_environment
          - name: circuit_breaker
          - name: document_control_product  #product/obt Schema starts here
          - name: supply_chain_product
          - name: construction_product
          - name: project_control_product
          - name: finance_product
          - name: engineering_product
          - name: customer_product
          - name: health_safety_environment_product
          - name: circuit_breaker_product
          # - name: dbt_document_control_product
          #   active: false 
      - role_name: AWS-PIM - DataPlatform Data Curator - Non Prod
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        allowed_schemas:
          - name: document_control   #fact/obt Schema starts here
          - name: supply_chain
          - name: construction
          - name: project_control
          - name: finance
          - name: engineering
          - name: circuit_breaker
          - name: customer
          - name: health_safety_environment
          - name: document_control_product   #product Schema starts here
          - name: supply_chain_product
          - name: construction_product
          - name: project_control_product
          - name: finance_product
          - name: engineering_product
          - name: circuit_breaker_product
          - name: customer_product
          - name: health_safety_environment_product    
      - role_name: AWS-PIM - DataPlatform Visualization - Non Prod
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        allowed_schemas:
          - name: document_control  #fact/obt Schema starts here
          - name: supply_chain
          - name: construction
          - name: project_control
          - name: finance
          - name: engineering
          - name: customer
          - name: health_safety_environment
          - name: document_control_product   #product Schema starts here
          - name: supply_chain_product
          - name: construction_product
          - name: project_control_product
          - name: finance_product
          - name: engineering_product
          - name: health_safety_environment_product
          # - name: customer_product
      - role_name: AWS-PIM - SoftwareCircuitBreaker Visualization - Non Prod
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        allowed_schemas:
          - name: circuit_breaker  #fact/obt Schema starts here
          - name: circuit_breaker_product  #product Schema starts here
      - role_name: AWS-PIM - SoftwareCircuitBreaker Budget Visualization - Non Prod
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        allowed_schemas:
          - name: circuit_breaker  #fact/obt Schema starts here
          - name: circuit_breaker_product  #product Schema starts here
    iam_roles:
    users:
      - user_name: dbt_global_standard_reporting_user
        identity_provider: internal
        allowed_schemas:
          - name: dbt_document_control_product # default: usage and select permissions are granted
          - name: dbt_supply_chain_product
          - name: dbt_finance_product
          - name: dbt_engineering_product
          - name: dbt_construction_product
          - name: dbt_project_control_product
          - name: dbt_health_safety_environment_product
          - name: dbt_circuit_breaker_product
          - name: dbt_customer_product
          - name: document_control
            permissions: CREATE  # optional: specify this if create on schema permission is required
          - name: supply_chain
            permissions: CREATE
          - name: engineering
            permissions: CREATE
          - name: construction
            permissions: CREATE
          - name: finance
            permissions: CREATE 
          - name: project_control
            permissions: CREATE
          - name: health_safety_environment
            permissions: CREATE
          - name: circuit_breaker
            permissions: CREATE
          - name: customer
            permissions: CREATE
      - user_name: snow_user
        identity_provider: internal
        allowed_schemas:
          - name: dbt_document_control_product # default: usage and select permissions are granted
          - name: dbt_supply_chain_product
          - name: dbt_finance_product
          - name: dbt_engineering_product
          - name: dbt_construction_product
          - name: dbt_project_control_product
          - name: dbt_customer_product
          - name: snowflake_model
            permissions: CREATE  # optional: specify this if create on schema permission is required  

      - user_name: collibra_test_user
        identity_provider: internal
        allowed_schemas:
          - name: document_control
          - name: supply_chain
          - name: engineering
          - name: construction
          - name: finance # optional: specify this if create on schema permission is required
