---
SourceSystemId: contract
MetadataType: api#contract#extract_api
api_parameter:
  api_body: 
  api_exponential_backoff: 3
  api_headers:
    Content-Type: application/json
    x-erm-env: ${erm_env_prefix}
  api_method: get
  api_query_params: 
  api_request_body: 
  api_response_type: json
  api_retry: 3
  api_ssl_verify: False
  api_timeout: 300
  auth_type: Bearer
  dynamic_api_headers:
  - Authorization
  endpoint: https://iddqa.crm.dynamics.com/api/data/v9.2/idd_contractmasters
auth_api_parameter:
  api_name: contract
  auth_body:
    client_id: 
    client_secret: 
    grant_type: client_credentials
    resource: https://iddqa.crm.dynamics.com
    scope: connect  #To keep or remove
  auth_exponential_backoff: 5
  auth_headers: 
  auth_method: post
  auth_ssl_verify: False
  auth_query_params: 
  auth_retry: 3
  auth_timeout: 1200
  dynamic_auth_headers:
  - AuthToken
  endpoint: https://login.microsoftonline.com/73ad6539-b4fe-429c-97b6-fbc1b6ada80b/oauth2/token
  secret_key: ${secret_prefix}-db-contract
aws_region: ${region}
is_active: "y"
job_parameter:
  bucket_data_source_prefix: contract
  bucket_name: ${raw_bucket}
  full_incremental: i
  input_path: contract
  kms_key_id: ${kms_key_id}
  output_s3: contract
  sampling_fraction: '0.5'
  sampling_seed: 42
  schema_output_s3: contract/data_sampling
  status_timeout: 86400
  temp_output_path: temp/
  status_check: 10
name: CONTRACT_API
