SourceSystemId: csp_salesforce_curated
MetadataType: curated#conv_recordtype_gbs#csp_salesforce#job#iceberg
source:
  compute_engine: spark
  glue_options:
    connection_options: s3://${raw_bucket}/customer/csp_salesforce/conv_tables/table_conv_recordtype_gbs.parquet/
    connection_type: s3
    format: parquet
    transformation_ctx: csp_salesforce_conv_recordtype_gbs_curated
  name: conv_recordtype_gbs_csv_curated
  spark_options:
    format: parquet
table_schema:
  columns:
    - column_data_type: string
      column_name: id_record_type_gbs
      comment: id_record_type_gbs
      data_classification: null
      nullable: true
      raw_column_name: id_record_type_gbs
    - column_data_type: string
      column_name: record_type_gbs
      comment: record_type_gbs
      data_classification: null
      nullable: true
      raw_column_name: record_type_gbs
  
  schema_properties:
    enforce: true
    rename_columns: true
target:
  compute_engine: spark
  deduplication_keys:
    - id_record_type_gbs
  iceberg_properties:
    database_name: ${database_prefix}_customer_csp_salesforce_curated
    iceberg_configuration:
      create_table: true
      iceberg_catalog_warehouse: s3://${curated_bucket}/customer/csp_salesforce/conv_recordtype_gbs
      table_properties:
        format-version: "2"
        write.format.default: parquet
    table_name: curated_conv_recordtype_gbs
  load_type: full_load
  name: curated_conv_recordtype_gbs
  spark_options:
    format: iceberg
    options:
      path: s3://${curated_bucket}/customer/csp_salesforce/conv_recordtype_gbs
transforms:
  - rename_column: true
    transform: rename_columns
  - select_columns: true
    transform: select_columns_from_config_file
  - change_types: true
    transform: change_data_types
  - column_name: EXECUTION_DATE
    date_format: yyyy-MM-dd
    transform: add_run_date
