SourceSystemId: csp_salesforce_curated
MetadataType: curated#conv_country#csp_salesforce#job#iceberg
source:
  compute_engine: spark
  glue_options:
    connection_options: s3://${raw_bucket}/customer/csp_salesforce/conv_tables/table_conv_country.parquet/
    connection_type: s3
    format: parquet
    transformation_ctx: csp_salesforce_conve_country_curated
  name: conve_country_csv_curated
  spark_options:
    format: parquet
table_schema:
  columns:
    - column_data_type: string
      column_name: api_name
      comment: api_name
      data_classification: null
      nullable: true
      raw_column_name: api_name
    - column_data_type: string
      column_name: asset_country
      comment: asset_country
      data_classification: null
      nullable: true
      raw_column_name: asset_country
    - column_data_type: string
      column_name: iso_code
      comment: iso_code
      data_classification: null
      nullable: true
      raw_column_name: iso_code
    - column_data_type: string
      column_name: salesforce_str
      comment: salesforce_str
      data_classification: null
      nullable: true
      raw_column_name: salesforce_str
    - column_data_type: timestamp
      column_name: last_updated_date
      comment: Last updated timestamp for incremental load
      data_classification: null
      nullable: true
      raw_column_name: last_updated_date
  schema_properties:
    enforce: true
    rename_columns: true
target:
  compute_engine: spark
  deduplication_keys:
    - api_name
  iceberg_properties:
    database_name: ${database_prefix}_customer_csp_salesforce_curated
    iceberg_configuration:
      create_table: true
      iceberg_catalog_warehouse: s3://${curated_bucket}/customer/csp_salesforce/conv_country
      table_properties:
        format-version: "2"
        write.format.default: parquet
    table_name: curated_conv_country
  load_type: full_load
  name: curated_conv_country
  spark_options:
    format: iceberg
    options:
      path: s3://${curated_bucket}/customer/csp_salesforce/conv_country
transforms:
  - rename_column: true
    transform: rename_columns
  - select_columns: true
    transform: select_columns_from_config_file
  - change_types: true
    transform: change_data_types
  - column_name: EXECUTION_DATE
    date_format: yyyy-MM-dd
    transform: add_run_date
