SourceSystemId: csp_salesforce_curated
MetadataType: curated#fact_snapshot#csp_salesforce#job#iceberg
source:
  compute_engine: spark
  glue_options:
    connection_options: s3://${raw_bucket}/customer/csp_salesforce/conv_tables/table_fact_snapshot.parquet/
    connection_type: s3
    format: parquet
    transformation_ctx: csp_salesforce_fact_snapshot_curated
  name: fact_snapshot_csv_curated
  spark_options:
    format: parquet
table_schema:
  columns:
    - column_data_type: date
      column_name: date_snapshot
      comment: date_snapshot
      data_classification: null
      nullable: true
      raw_column_name: date_snapshot
    - column_data_type: string
      column_name: id_opportunity
      comment: id_opportunity
      data_classification: null
      nullable: true
      raw_column_name: id_opportunity
    - column_data_type: bigint
      column_name: revenue_mos_unfactored
      comment: revenue_mos_unfactored
      data_classification: null
      nullable: true
      raw_column_name: revenue_mos_unfactored
    - column_data_type: int
      column_name: gm_mos_unfactored
      comment: gm_mos_unfactored
      data_classification: null
      nullable: true
      raw_column_name: gm_mos_unfactored
    - column_data_type: int
      column_name: hours_mos_unfactored
      comment: hours_mos_unfactored
      data_classification: null
      nullable: true
      raw_column_name: hours_mos_unfactored
    - column_data_type: date
      column_name: date_lastmodified
      comment: date_lastmodified
      data_classification: null
      nullable: true
      raw_column_name: date_lastmodified
  schema_properties:
    enforce: true
    rename_columns: true
target:
  compute_engine: spark
  deduplication_keys:
    - ''
  iceberg_properties:
    database_name: ${database_prefix}_customer_csp_salesforce_curated
    iceberg_configuration:
      create_table: true
      iceberg_catalog_warehouse: s3://${curated_bucket}/customer/csp_salesforce/fact_snapshot/
      table_properties:
        format-version: "2"
        write.format.default: parquet
    table_name: curated_fact_snapshot
  load_type: full_load
  name: curated_fact_snapshot
  spark_options:
    format: iceberg
    options:
      path: s3://${curated_bucket}/customer/csp_salesforce/fact_snapshot/
transforms:
  - rename_column: true
    transform: rename_columns
  - select_columns: true
    transform: select_columns_from_config_file
  - change_types: true
    transform: change_data_types
  - column_name: EXECUTION_DATE
    date_format: yyyy-MM-dd
    transform: add_run_date
