SourceSystemId: csp_salesforce_curated
MetadataType: curated#csp_salesforce#user#job#iceberg
source:
  compute_engine: spark
  glue_options:
    connection_options: s3://${raw_bucket}/customer/csp_salesforce/user/
    connection_type: s3
    format: parquet
    transformation_ctx: csp_salesforce-user
  name: csp_salesforce_user
  spark_options:
    format: parquet
target:
  compute_engine: spark
  drop_duplicates: true
  iceberg_properties:
    database_name: ${database_prefix}_customer_csp_salesforce_curated
    iceberg_configuration:
      create_table: true
      iceberg_catalog_warehouse: ${curated_bucket}/customer/csp_salesforce/user/
      table_properties:
        format-version: '2'
        write.format.default: parquet
    table_name: curated_user
  load_type: incremental_no_delete
  primary_constraint_properties:
    enforce_primary_constraint: true
    timestamp_column_name: lastmodifieddate_ts
  db_load:
    aurora_host: ${aurora_host}
    aurora_port: '5432'
    aurora_secret: Worley-datalake-sydney-${envn}-db-csp-salesforce-glueuser
    aurora_db_name: ${aurora_db}
    aurora_db_target_table_name: user
    aurora_db_target_schema: CSP_Salesforce
    aurora_data_load_type: append
    snapshot_s3_bucket: ${raw_bucket}
    snapshot_s3_key: customer/csp_salesforce/iceberg-to-aurora/snapshot/csp_salesforce/user/last_processed_snapshot.txt
    snapshot_s3_kms_key_id: ${iceberg_snapshot_key}
    primary_key: id
  name: curated_user
  primary_key:
  - id
  spark_options:
    format: iceberg
    options:
      path: s3://${curated_bucket}/customer/csp_salesforce/user
transforms:
- rename_column: true
  transform: rename_columns
- select_columns: true
  transform: select_columns_from_config_file
- change_types: true
  transform: change_data_types
- column_name: EXECUTION_DATE
  date_format: yyyy-MM-dd HH:mm:ss
  transform: add_run_date
- sql: SELECT *, CAST(lastmodifieddate as timestamp) as lastmodifieddate_ts, 'csp_salesforce'
    as SOURCE_SYSTEM_NAME FROM temp_df_static
  temp_view_name: temp_df_static
  transform: custom_sql
table_schema:
  schema_properties:
    enforce: true
    primary_key:
    - id
    rename_columns: true
  columns:
  - column_data_type: string
    column_name: id
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: id
  - column_data_type: string
    column_name: name
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: name
  - column_data_type: string
    column_name: firstname
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: firstname
  - column_data_type: string
    column_name: lastname
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: lastname
  - column_data_type: string
    column_name: username
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: username
  - column_data_type: string
    column_name: email
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: email
  - column_data_type: string
    column_name: alias
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: alias
  - column_data_type: string
    column_name: title
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: title
  - column_data_type: string
    column_name: department
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: department
  - column_data_type: string
    column_name: companyname
    comment: null
    data_classification: null
    nullable: true
    raw_column_name: companyname
