{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_mps_logs_all/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}

select
    
    cast(sr_no as varchar(500)) as sr_no,
    cast(cwa as varchar(500)) as cwa,
    cast(old_mps_number_1 as varchar(500)) as old_mps_number_1,
    cast(old_mps_number_2 as varchar(500)) as old_mps_number_2,
    cast(mps_number as varchar(500)) as mps_number,
    cast(mps_type as varchar(500)) as mps_type,
    cast(struct_frame_no as varchar(500)) as struct_frame_no,
    cast(line_number as varchar(500)) as line_number,
    cast(tos_elevation as varchar(500)) as tos_elevation,
    cast(design_area_wbs as varchar(500)) as design_area_wbs,
    cast(cwp_area as varchar(500)) as cwp_area,
    cast(issued_to_stress_team_date as varchar(500)) as issued_to_stress_team,
    cast(loads_given_to_csa as varchar(500)) as loads_given_to_csa,
    cast(uln_no as varchar(500)) as uln_no,
    cast(ope_load_fy as varchar(500)) as ope_load_fy,
    cast(ope_load_fx as varchar(500)) as ope_load_fx,
    cast(ope_load_fz as varchar(500)) as ope_load_fz,
    cast(hydro_test_load_fy as varchar(500)) as hydro_test_load_fy,
    cast(hydro_test_load_fx as varchar(500)) as hydro_test_load_fx,
    cast(hydro_test_load_fz as varchar(500)) as hydro_test_load_fz,
    cast(mps_drawing_type as varchar(500)) as mps_drawing_type,
    cast(reviewed_by_csa as varchar(500)) as reviewed_by_csa,
    cast(csa_engineer as varchar(500)) as csa_engineer,
    cast(designed_by_csa as varchar(500)) as designed_by_csa,
    cast(model_updated_by_csa as varchar(500)) as model_updated_by_csa,
    cast(csa_drawing_no as varchar(500)) as csa_drawing_no,
    cast(remarks as varchar(500)) as remarks,
    cast(
        csa_modelled_support_checked_by_piping_design as varchar(500)
    ) as csa_modelled_support_checked_by_piping_design,
    cast(pd_comments_on_csa_model as varchar(500)) as pd_comments_on_csa_model,
    cast(
        support_checked_and_magenta_steel_removed as varchar(500)
    ) as support_checked_and_magenta_steel_removed,
    cast(mps_status as varchar(500)) as mps_status,
    cast(civil_model_name as varchar(500)) as civil_model_name,
    issued_to_stress_team_date as converted_issued_to_stress_team,
    loads_given_to_csa as converted_loads_given_to_csa,
    cast(execution_date as date) as extracted_date,
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id,
    cast('VGCP2' as varchar(100)) as project_code,
    source_system_name
from
    (
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            csa_drawing_no,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_comments_on_csa_model,
            support_checked_and_magenta_steel_removed,
            mps_status,
            '' as civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_bog') }}
        union
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            csa_drawing_no,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_comments_on_csa_model,
            support_checked_and_magenta_steel_removed,
            mps_status,
            civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_bop') }}
        union
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            csa_drawing_no,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_comments_on_csa_model,
            support_checked_and_magenta_steel_removed,
            mps_status,
            '' as civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_lfm') }}
        union
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            csa_drawing_no,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_commets_on_csa_model as pd_comments_on_csa_model,
            support_checked_and_magenta_steel_removed,
            mps_status,
            '' as civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_mar') }}
        union
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwa_area as cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            csa_drawing_no,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_commets_on_csa_model as pd_comments_on_csa_model,
            support_checked_and_magenta_steel_removed,
            mps_status,
            '' as civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_mpr') }}
        union
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            csa_drawing_no,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_commets_on_csa_model as pd_comments_on_csa_model,
            support_checked_and_magenta_steel_removed,
            mps_status,
            '' as civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_nru') }}
        union
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            y,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_commets_on_csa_model as pd_comments_on_csa_model,
            supt_checked_and_magenta_steel_removed as support_checked_and_magenta_steel_removed,
            mps_status,
            '' as civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_ptm') }}
        union
        select
            sr_no,
            cwa,
            old_mps_number_1,
            old_mps_number_2,
            mps_number,
            mps_type,
            struct_frame_no,
            line_number,
            tos_elevation,
            design_area_wbs,
            cwp_area,
            issued_to_stress_team_date,
            loads_given_to_csa,
            uln_no,
            ope_load_fy,
            ope_load_fx,
            ope_load_fz,
            hydro_test_load_fy,
            hydro_test_load_fx,
            hydro_test_load_fz,
            mps_drawing_type,
            reviewed_by_csa,
            csa_engineer,
            designed_by_csa,
            model_updated_by_csa,
            csa_drawing_no,
            remarks,
            csa_modelled_support_checked_by_piping_design,
            pd_commets_on_csa_model as pd_comments_on_csa_model,
            supt_checked_and_magenta_steel_removed as support_checked_and_magenta_steel_removed,
            mps_status,
            '' as civil_model_name,
            cast(execution_date as date) as execution_date,
			source_system_name
        from
            {{ source('curated_mps', 'mps_log_all_tnk') }}
    )