{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_omie_req/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


select
    id,
    cast(title as varchar(500)) as title,
    cast(attributes as varchar(10000)) as attributes,
    cast(description as varchar(500)) as description,
    cast(response as varchar(500)) as response,
    cast(comments as varchar(500)) as comments,
    cast(log as varchar(10000)) as log,
    cast(code as varchar(500)) as code,
    cast(rev as varchar(500)) as rev,
    wfstatus_id,
    reqpriority_id,
    probability_id,
    impact_id,
    text_id,
    combo_id,
    customdate_id,
    req_type_id,
    from,
    from_entity_id,
    to,
    to_entity_id,
    from_orgchart_id,
    cast(from_orgchart as varchar(500)) as from_orgchart,
    to_orgchart_id,
    cast(to_orgchart as varchar(500)) as to_orgchart,
    from_orgposition_id,
    cast(from_orgposition as varchar(500)) as from_orgposition,
    to_orgposition_id,
    cast(to_orgposition as varchar(500)) as to_orgposition,
    cast(component1 as varchar(500)) as component1,
    component1_id,
    cast(project as varchar(500)) as project,
    project_id,
    cast(component2 as varchar(500)) as component2,
    component2_id,
    requireddate,
    closeddate,
    responsedate,
    cast(converted_from as varchar(500)) as converted_from,
    cast(converted_to as varchar(500)) as converted_to,
    cast(last_comment as varchar(500)) as last_comment,
    cast(historyjson as varchar(10000)) as historyjson,
    cast(documentjson as varchar(10000)) as documentjson,
    documentcount,
    cast(customvals as varchar(10000)) as customvals,
    cast(commentsjson as varchar(10000)) as commentsjson,
    cast(cc_ids as varchar(500)) as cc_ids,
    cast(cc_list as varchar(500)) as cc_list,
    cast(resp_list as varchar(500)) as resp_list,
    cast(resp_ids as varchar(500)) as resp_ids,
    internal,
    cast(import as varchar(500)) as import,
    order,
    updated_by_id,
    archivedate,
    mdate,
    created_by_id,
    cdate,
    disabled,
    deleted,
    confidential,
	source_system_name,
    cast(execution_date as date) as extracted_date,
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id,
    cast('VGCP2' as varchar(30)) as project_code
from
     {{ source('curated_omie', 'curated_req') }}
