{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_spel_plantitem/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


SELECT  
	sp_id,
	tagsequenceno,
	tagsuffix,
	tagprefix,
	name,
	itemtag,
	CAST(plantitemtype AS decimal(38,0)) AS plantitemtype,
	aabbcc_code,
	CAST(fabricationcategory AS decimal(38,0)) AS fabricationcategory,
	sp_plantgroupid,
	CAST(supplyby AS decimal(38,0)) AS supplyby,
	CAST(requisitionby AS decimal(38,0)) AS requisitionby,
	CAST(isbulkitem AS decimal(38,0)) AS isbulkitem,
	inventorytag,
	CAST(constructionstatus AS decimal(38,0)) AS constructionstatus,
	CAST(constructionby AS decimal(38,0)) AS constructionby,
	CAST(designby AS decimal(38,0)) AS designby,
	erpassetno,
	requisitionno,
	sp_partno,
	sp_sourceapplication,
	itemtagfullname,
	sp_plantitemgroupid,
	CAST(referencedatachangedflag AS decimal(38,0)) AS referencedatachangedflag,
	sp_sameasuid,
	CAST(sp_isnew AS decimal(38,0)) AS sp_isnew,
	CAST(sp_claimmode AS decimal(38,0)) AS sp_claimmode,
	CAST(sp_itemprojectstatus AS decimal(38,0)) AS sp_itemprojectstatus,
	sp_sameasuid1,
	sp_sameasuid2,
	sp_sameasuid3,
	sp_sameasuid4,
	sp_sameasuid5,
	sp_sameasuid6,
	sp_sameasuid7,
	sp_sameasuid8,
	sp_sameasuid9,
	sp_piddrawingnumber,
	sp_kkstotalplant,
	sp_kkssystemkey,
	sp_kkssystemsequence,
	sp_kkscomponentkey,
	sp_kksequipmentunitkey,
	sp_kksequipmentunitsequence,
	sp_kkssystemkeyprefix,
	sp_kksequipunitadditionalcode,
	sp_kkscomponentsequence,
	CAST(sp_allowpublishflag AS decimal(38,0)) AS sp_allowpublishflag,
	sp_3pdbid,
	sp_3piid,
	sp_spiid,
	sp_fullitemtag,
	sp_sourceapplication1,
	sp_sourceapplication2,
	sp_sourceapplication3,
	sp_sourceapplication4,
	sp_sourceapplication5,
	sp_sourceapplication6,
	sp_sourceapplication7,
	sp_sourceapplication8,
	sp_sourceapplication9,
	sp_3pguid,
	sp_commissioningsystem,
	sp_commissioningsubsystem,
	source_system_name,
	'VGCP2' project_code,
	cast(execution_date as date) as extracted_date,
	{{run_date}} as model_created_date,
	{{run_date}} as model_updated_date,
	{{ generate_load_id(model) }} as model_load_id
FROM 
{{ source('curated_spel', 'curated_t_plantitem') }}
