{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_mel_cp2_mechanical_eqip/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


select
    wbs_area,
    phase,
    ownership,
    construction_work_area as construction_work_area_cwa,
    cwp_zone,
    first_lng as first_lng_lps_1,
    area,
    unit,
    sub_unit_and_train as train,
    equipment_type_code,
    equipment_number,
    tag_suffix as tag_suffix_a_b_c,
    description,
    pid_n as p_and_id_no,
    tema_designation,
    mechanical_datasheet_n as mechanical_datasheet_no,
    operating_spare,
    equipment_load,
    continuous_intermittent,
    status,
    vertical_horizontal,
    internal_diameter,
    length_or_tan_to_tan,
    width,
    height,
    rated_flow,
    differential_head,
    nominal_capacity,
    thermal_duty,
    driver_type,
    driver_tag_number,
    required_power,
    installed_power,
    voltage,
    operating_pressure,
    operating_temperature,
    operating_pressure_tube,
    operating_temperature_tube,
    design_pressure_internal,
    design_pressure_external as design_pressure_external_vacuum,
    design_temp_max,
    design_temp_min,
    mdmt,
    design_pressure_internal_tube,
    design_pressure_external_tube,
    design_temp_max_tube,
    design_temp_min_tube,
    mdmt_tube,
    design_code_specification,
    gas_liquid as gasliquid_atm_cond,
    fluid_group,
    table as table_detail,
    weight_operating,
    weight_bare,
    weight_test,
    material,
    materials_internals_tube,
    insulation_type,
    insulation_thickness,
    fireproofing,
    supplier,
    manufacturer,
    manufacturer_model_n as manufacturer_model_no,
    code_of_accounts,
    part_of_package,
    workpack_reference,
    completions_system,
    supplier_data_status_code as supplier_data_status_code_note1,
    requisition_n as requisition_no,
    re,
    gid_static_rotary,
    process_data_based_on_pq_data_sheets,
    notes,
    rev_n as rev_no,
    cast(execution_date as date) as extracted_date,	
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id,
    'VGCP2' as project_code,
    '' as line_number,
    insulation_quantity,
    fireproofing_type,
    fireproofing_quantity,
    '' as fire_scenario_envelope_plan,
    '' as vfd_vsd,
	source_system_name,
	'VGCP2'|| '_' ||COALESCE(wbs_area, '')|| '_' ||
    COALESCE(construction_work_area, '')|| '_' ||COALESCE(cwp_zone, '')
    AS PROJECT_CODE_WBS_CWA_CWPZONE    
from
    {{ source('curated_mel', 'curated_mechanical_equipment_list_eql') }}
