{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_spi_component/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}

select
    cast(comp.cmpnt_id as decimal(38, 0)),
    cast(comp.proj_id as decimal(38, 0)),
    cast(comp.site_id as decimal(38, 0)),
    cast(comp.chg_num as decimal(38, 0)),
    cast(comp.plant_id as decimal(38, 0)),
    cast(comp.area_id as decimal(38, 0)),
    cast(comp.unit_id as decimal(38, 0)),
    comp.chg_status,
    comp.user_name,
    comp.chg_date,
    comp.cmpnt_name,
    comp.cmpnt_serv,
    cast(comp.spec_id as decimal(38, 0)),
    comp.cmpnt_num,
    cast(comp.cmpnt_type_id as decimal(38, 0)),
    comp.cmpnt_suff,
    cast(comp.cmpnt_func_type_id as decimal(38, 0)),
    comp.name_lock,
    comp.cmpnt_name_parm,
    comp.old_cmpnt_name,
    cast(comp.cmpnt_loc_id as decimal(38, 0)),
    cast(comp.cmpnt_sys_io_type_id as decimal(38, 0)),
    cast(comp.cmpnt_handle_id as decimal(38, 0)),
    cast(comp.equip_id as decimal(38, 0)),
    cast(comp.item_price as decimal(38, 2)),
    comp.cmpnt_note,
    comp.remark1,
    comp.remark2,
    comp.remark3,
    comp.remark4,
    comp.remark5,
    comp.prefix,
    cast(comp.cmpnt_seq as decimal(38, 0)),
    cast(comp.loop_id as decimal(38, 0)),
    cast(comp.cmpnt_drawing_seq as decimal(38, 0)),
    comp.inst_type_blk_flg,
    comp.tag_trans_name,
    cast(comp.cmpnt_mod_id as decimal(38, 0)),
    cast(comp.cmpnt_mfr_id as decimal(38, 0)),
    cast(comp.proc_func_id as decimal(38, 0)),
    comp.spec_cmpnt_type,
    comp.spec_cmpnt_func,
    comp.spec_cmpnt_price,
    comp.spec_cmpnt_mounting,
    comp.spec_cmpnt_sn,
    comp.spec_cmpnt_po_no,
    comp.spec_cmpnt_po_item_no,
    comp.spec_cmpnt_power_supply,
    comp.spec_enclosure_class,
    cast(comp.add_line_id as decimal(38, 0)),
    cast(comp.dwg_id as decimal(38, 0)),
    cast(comp.line_id as decimal(38, 0)),
    comp.loop_param,
    cast(comp.cmpnt_critical_id as decimal(38, 0)),
    comp.cmpnt_quality_flg,
    cast(comp.inst_range_min as float),
    cast(comp.inst_range_max as float),
    comp.inst_range_uom_min,
    comp.inst_range_uom_max,
    comp.inst_range_uflg_min,
    comp.inst_range_uflg_max,
    cast(comp.calib_range_min as float),
    cast(comp.calib_range_max as float),
    comp.calib_range_uom_min,
    comp.calib_range_uom_max,
    comp.calib_range_uflg_min,
    comp.calib_range_uflg_max,
    cast(comp.dcs_range_min as float),
    cast(comp.dcs_range_max as float),
    comp.dcs_range_uom,
    cast(comp.dry_weight as float),
    cast(comp.full_weight as float),
    cast(comp.uom_id as decimal(38, 0)),
    cast(comp.instr_pd_flg as decimal(38, 0)),
    comp.dcs_range_uflg,
    cast(comp.rev_id as decimal(38, 0)),
    cast(comp.eng_proj_id as decimal(38, 0)),
    cast(comp.eng_ref_id as decimal(38, 0)),
    cast(comp.cmpnt_certif_id as decimal(38, 0)),
    comp.fb_tag_no,
    comp.fb_dev_address,
    comp.fb_dev_id,
    cast(comp.fb_min_volt as float),
    cast(comp.fb_max_volt as float),
    cast(comp.fb_dc_cur as float),
    cast(comp.fb_min_transmit_level as float),
    comp.fb_standard,
    cast(comp.wire_group_id as decimal(38, 0)),
    cast(comp.master_cmpnt_id as decimal(38, 0)),
    cast(comp.cmpnt_find_rem as decimal(38, 0)),
    comp.req_no,
    cast(comp.tc_line_number_id as decimal(38, 0)),
    comp.tc_location_layout,
    comp.tc_fire_area,
    cast(comp.tc_field_equipment_id as decimal(38, 0)),
    cast(comp.tc_signal_id as decimal(38, 0)),
    cast(comp.udt_support_id1 as decimal(38, 0)),
    cast(comp.udt_support_id2 as decimal(38, 0)),
    cast(comp.udt_support_id3 as decimal(38, 0)),
    cast(comp.udt_support_id4 as decimal(38, 0)),
    cast(comp.panel_id as decimal(38, 0)),
    cast(comp.strip_id as decimal(38, 0)),
    cast(comp.load_watt as float) load_watt,
    cast(comp.capacitance as float) capacitance,
    comp.capacitance_uom,
    comp.pipe_class,
    comp.backup_link_master,
    cast(comp.fieldbus_device_rev as decimal(38, 0)),
    cast(comp.elect_equip_id as decimal(38, 0)),
    cast(comp.elect_load_equip_id as decimal(38, 0)),
    cast(comp.dwg_schematic_id as decimal(38, 0)),
    comp.typical_schematic,
    comp.circuit,
    cast(comp.udt_support_id5 as float),
    cast(comp.udt_support_id6 as float),
    cast(comp.udt_support_id7 as float),
    cast(comp.udt_support_id8 as float),
    cast(comp.udt_support_id9 as float),
    cast(comp.udt_support_id10 as float),
    cast(comp.udt_support_id11 as float),
    cast(comp.udt_support_id12 as float),
    cast(comp.udt_support_id13 as float),
    cast(comp.udt_support_id14 as float),
    cast(comp.udt_support_id15 as float),
    cast(comp.udt_support_id16 as float),
    comp.requires_power_supply,
    cast(comp.related_voltage_id as decimal(38, 0)),
    cast(comp.frequency_id as decimal(38, 0)),
    cast(comp.number_of_phases_id as decimal(38, 0)),
    cast(comp.operating_mode_id as decimal(38, 0)),
    cast(comp.rated_voltage_id as decimal(38, 0)),
    cast(comp.full_load_current as float),
    cast(comp.starting_current as float),
    cast(comp.rated_active_load as float),
    cast(comp.rated_apparent_load as float),
    cast(comp.rated_reactive_load as float),
    comp.power_supply_type_flag,
    comp.power_distribution_board,
    comp.cell,
    cast(comp.zzcoincidencefactor as float),
    cast(comp.zcoincidencefactor as float),
    cast(comp.ycoincidencefactor as float),
    cast(comp.xcoincidencefactor as float),
    comp.phase1,
    comp.phase2,
    comp.phase3,
    cast(comp.power_factor_full_load as float),
    cast(comp.pipe_class_id as decimal(38, 0)),
    comp.analyzer_flg,
    cast(comp.cmpnt_is_circuite_type_id as decimal(38, 0)),
    cast(comp.line_cmpnt_id as decimal(38, 0)),
    cast(comp.circuit_id as decimal(38, 0)),
    comp.speaker_tag_id,
    cast(comp.cmpnt_cat_id as decimal(38, 0)),
    comp.cmpnt_profibus_node,
    cast(comp.hart_signal_id as decimal(38, 0)),
    cast(comp.signal_type_id as decimal(38, 0)),
    cast(comp.linear_type_id as decimal(38, 0)),
    comp.kks_totalplant,
    comp.kks_function_key_prefix,
    comp.kks_function_key,
    comp.kks_function_key_sequence,
    comp.kks_equipment_unit_code,
    comp.kks_equipment_unit_sequence,
    comp.kks_equipment_unit_add_code,
    comp.kks_component_key,
    comp.kks_component_key_sequence,
    comp.use_symbol_flg,
    cast(comp.cmpnt_associated_id as decimal(38, 0)),
    comp.merge_release_flg,
    comp.on_signal_state_desc,
    comp.off_signal_state_desc,
    cast(comp.typical_tag_class_id as decimal(38, 0)),
    'VGCP2' as project_code,
    cast(comp.execution_date as date) as extracted_date,
    comp.source_system_name,
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id,
    udf.udf_c03 AS WBS,
    udf.udf_c21 AS CWA,
    udf.udf_c127 AS CWPZONE,
	'VGCP2'|| '_' ||COALESCE(udf.udf_c03, '')|| '_' ||
    COALESCE(udf.udf_c21, '')|| '_' ||COALESCE(udf.udf_c127, '')
    AS PROJECT_CODE_WBS_CWA_CWPZONE  
from
    {{ source('curated_spi', 'curated_component') }} comp
    LEFT OUTER JOIN {{ source('curated_spi', 'curated_udf_component') }} udf
    ON  comp.cmpnt_id || 'VGCP2' = udf.cmpnt_id ||'VGCP2'  
	