{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_isotracker_union/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


select
    cast(object as varchar(500)) as object,
    cast(sr_no as varchar(500)) as sr_no,
    cast(dwg_no as varchar(500)) as dwg_no,
    cast(doc_no as varchar(500)) as doc_no,
    cast(iso_id as varchar(500)) as iso_id,
    cast(cwp as varchar(500)) as cwp,
    cast(line_id as varchar(500)) as line_id,
    cast(line_size as varchar(500)) as line_size,
    cast(spec as varchar(500)) as spec,
    cast(insulation as varchar(500)) as insulation,
    cast(p_and_id_no as varchar(500)) as p_and_id_no,
    cast(remarks_header as varchar(500)) as remarks_header,
    cast(modeling_status as varchar(500)) as modeling_status,
    cast(line_modelled as varchar(500)) as line_modelled,
    cast(ifh_p_and_id_check_completed as varchar(500)) as ifh_p_and_id_check_completed,
    cast(prcnt30_review_comments_updated as varchar(500)) as prcnt30_review_comments_updated,
    cast(issued_to_stress as varchar(500)) as issued_to_stress,
    cast(returned_from_stress as varchar(500)) as returned_from_stress,
    cast(stress_incorporation as varchar(500)) as stress_incorporation,
    cast(supporting_completed as varchar(500)) as supporting_completed,
    cast(inline_component_data_updated as varchar(500)) as inline_component_data_updated,
    cast(preliminary_vendor_data_updated as varchar(500)) as preliminary_vendor_data_updated,
    cast(
        line_made_clash_free_data_consistency_check_cleared as varchar(500)
    ) as line_made_clash_free_data_consistency_check_cleared,
    cast(
        prcnt60_model_review_comments_updated as varchar(500)
    ) as prcnt60_model_review_comments_updated,
    cast(
        iso_extn_desig_slfchk_aprvdmoc_availvndr_dt as varchar(500)
    ) as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
    cast(piping_moc_prepared_if_applicable as varchar(500)) as piping_moc_prepared_if_applicable,
    cast(
        piping_check_with_cut_off_p_and_id_date as varchar(500)
    ) as piping_check_with_cut_off_p_and_id_date,
    cast(
        piping_checker_comments_and_final_vendor_data_comments_received as varchar(500)
    ) as piping_checker_comments_and_final_vendor_data_comments_received,
    cast(issued_to_squad_check as varchar(500)) as issued_to_squad_check,
    cast(check_squad_check_bb_session_num as varchar(500)) as check_squad_check_bb_session_num,
    cast(internal_lot as varchar(500)) as internal_lot,
    cast(squad_check_completed as varchar(500)) as squad_check_completed,
    cast(prcnt90_model_review_applicable as varchar(500)) as prcnt90_model_review_applicable,
    cast(prcnt90_review_comments_updated as varchar(500)) as prcnt90_review_comments_updated,
    cast(
        comment_incorporation_of_final_comments_squad_and_piping as varchar(500)
    ) as comment_incorporation_of_final_comments_squad_and_piping,
    cast(final_isometric_back_checking as varchar(500)) as final_isometric_back_checking,
    cast(
        afc_isometric_extracted_and_issued_to_dcc as varchar(500)
    ) as afc_isometric_extracted_and_issued_to_dcc,
    cast(afc_isometric_transmittal_issued as varchar(500)) as afc_isometric_transmittal_issued,
    cast(hold as varchar(500)) as hold,
    cast(hold_remarks1 as varchar(500)) as hold_remarks1,
    cast(process as varchar(500)) as process,
    cast(hold_initiation_date as varchar(500)) as hold_initiation_date,
    cast(mechanical as varchar(500)) as mechanical,
    cast(hold_initiation_date_1 as varchar(500)) as hold_initiation_date_1,
    cast(instrumentation as varchar(500)) as instrumentation,
    cast(hold_initiation_date_2 as varchar(500)) as hold_initiation_date_2,
    cast(structural as varchar(500)) as structural,
    cast(hold_initiation_date_3 as varchar(500)) as hold_initiation_date_3,
    cast(piping_stress as varchar(500)) as piping_stress,
    cast(hold_initiation_date_4 as varchar(500)) as hold_initiation_date_4,
    cast(piping_spec as varchar(500)) as piping_spec,
    cast(hold_initiation_date_5 as varchar(500)) as hold_initiation_date_5,
    cast(hold_remarks2 as varchar(500)) as hold_remarks2,
    cast(
        target_to_stress_completion_date_me3 as varchar(500)
    ) as target_to_stress_completion_date_me3,
    cast(
        target_to_structural_completion_date_me4 as varchar(500)
    ) as target_to_structural_completion_date_me4,
    cast(target_iso_lock_date_me5 as varchar(500)) as target_iso_lock_date_me5,
    cast(target_afc_date_me7 as varchar(500)) as target_afc_date_me7,
    cast(process_critical_lines as varchar(500)) as process_critical_lines,
    cast(process_critical_lines2 as varchar(1)) as process_critical_lines2,
    cast(stress_calculation_number as varchar(500)) as stress_calculation_number,
    cast(stress_calculation_number2 as varchar(1)) as stress_calculation_number2,
    cast(
        piping_check_with_frozen_master_p_and_id as varchar(500)
    ) as piping_check_with_frozen_master_p_and_id,
    cast(checker as varchar(500)) as checker,
    cast(extracted_date as date) as extracted_date,
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id,
    cast('VGCP2' as varchar(30)) as project_code,
    source_system_name
from
    (
        select
            distinct 'bog_tnk' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            piping_check_with_cut_off_p_id_date as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            target_to_stress_completion_date_me_3 as target_to_stress_completion_date_me3,
            target_to_structural_completion_date_me_4 as target_to_structural_completion_date_me4,
            target_iso_lock_date__me_5 as target_iso_lock_date_me5,
            target_afc_date_me_7 as target_afc_date_me7,
            process_critical_lines_y_n as process_critical_lines,
            '' as process_critical_lines2,
            stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            '' as checker,
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_bog') }}
        where 
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_bog') }}
            )
        union
        select
            distinct 'bop' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            '' as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            '' as target_to_stress_completion_date_me3,
            '' as target_to_structural_completion_date_me4,
            '' as target_iso_lock_date_me5,
            '' as target_afc_date_me7,
            '' as process_critical_lines,
            '' as process_critical_lines2,
            '' as stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            '' as checker,
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_bop_sm_sz') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_bop_sm_sz') }}
            )
        union
        select
            distinct 'lfm' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            piping_check_with_cut_off_p_id_date as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            '' as target_to_stress_completion_date_me3,
            '' as target_to_structural_completion_date_me4,
            '' as target_iso_lock_date_me5,
            '' as target_afc_date_me7,
            process_critical_lines_y_n as process_critical_lines,
            '' as process_critical_lines2,
            stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            '' as checker,
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_lfm') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_lfm') }}
            )
        union
        select
            distinct 'mar' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            '' as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            target_to_stress_completion_date_me_3 as target_to_stress_completion_date_me3,
            target_to_structural_completion_date_me_4 as target_to_structural_completion_date_me4,
            target_iso_lock_date__me_5 as target_iso_lock_date_me5,
            target_afc_date_me_7 as target_afc_date_me7,
            process_critical_lines_y_n as process_critical_lines,
            '' as process_critical_lines2,
            stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            -- missing column
            '' as checker,
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_mar') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_mar') }}
            )
        union
        select
            distinct 'mpr' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            '' as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            target_to_stress_completion_date_me_3 as target_to_stress_completion_date_me3,
            target_to_structural_completion_date_me_4 as target_to_structural_completion_date_me4,
            target_iso_lock_date__me_5 as target_iso_lock_date_me5,
            target_afc_date_me_7 as target_afc_date_me7,
            process_critical_lines_y_n as process_critical_lines,
            '' as process_critical_lines2,
            stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            '' as checker,
            -- missing column
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_mpr') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_mpr') }}
            )
        union
        select
            distinct 'nru' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            '' as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            '' as target_to_stress_completion_date_me3,
            '' as target_to_structural_completion_date_me4,
            target_iso_lock_date__me_5 as target_iso_lock_date_me5,
            target_afc_date_me_7 as target_afc_date_me7,
            process_critical_lines_y_n as process_critical_lines,
            '' as process_critical_lines2,
            stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_cutoff_p_and_id,
            -- missing column
            '' as checker,
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_nruisotracker') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_nruisotracker') }}
            )
        union
        select
            distinct 'ptm' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            '' as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            target_to_stress_completion_date_me_3 as target_to_stress_completion_date_me3,
            target_to_structural_completion_date_me_4 as target_to_structural_completion_date_me4,
            target_iso_lock_date__me_5 as target_iso_lock_date_me5,
            target_afc_date_me_7 as target_afc_date_me7,
            process_critical_lines_y_n as process_critical_lines,
            '' as process_critical_lines2,
            stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            '' as checker,
            -- missing column
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_ptm') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_ptm') }}
            )
        union
        select
            distinct 'ug' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            piping_check_with_cut_off_p_id_date as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            target_to_stress_completion_date_me_3 as target_to_stress_completion_date_me3,
            target_to_structural_completion_date_me_4 as target_to_structural_completion_date_me4,
            target_iso_lock_date__me_5 as target_iso_lock_date_me5,
            target_afc_date_me_7 as target_afc_date_me7,
            process_critical_lines_y_n as process_critical_lines,
            '' as process_critical_lines2,
            stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            '' as checker,
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_ug') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_ug') }}
            )
        union
        select
            distinct 'bop_um_uz' as object,
            sr_no,
            dwg_no,
            doc_no,
            iso_id,
            cwp,
            line_id,
            line_size,
            spec,
            insulation,
            p_id_no as p_and_id_no,
            remarks as remarks_header,
            modeling_status,
            line_modelled,
            ifh_p_id_check_completed as ifh_p_and_id_check_completed,
            30_review_comments_updated as prcnt30_review_comments_updated,
            issued_to_stress,
            returned_from_stress,
            stress_incorporation,
            supporting_completed,
            inline_component_data_updated,
            preliminary_vendor_data_updated,
            line_made_clash_free_data_consistency_check_cleared,
            60_model_review_comments_updated_y_n as prcnt60_model_review_comments_updated,
            iso_extraction_for_designer_self_check_with_approved_mocs__available_vendor_data__date as iso_extn_desig_slfchk_aprvdmoc_availvndr_dt,
            piping_moc_prepared_if_applicable_y_n as piping_moc_prepared_if_applicable,
            '' as piping_check_with_cut_off_p_and_id_date,
            piping_checker_comments_updated__final_vendor_data_comments_received_date as piping_checker_comments_and_final_vendor_data_comments_received,
            issued_to_squad_check_date as issued_to_squad_check,
            check__squad_check_bb_session as check_squad_check_bb_session_num,
            internal_lot,
            squad_check_completed_date as squad_check_completed,
            yes_if_90_model_review_applicable_y_n as prcnt90_model_review_applicable,
            90_review_comments_updated_y_n as prcnt90_review_comments_updated,
            comment_incorporation_of_final_comments_squad__piping__date as comment_incorporation_of_final_comments_squad_and_piping,
            final_isometric_back_checking_wrt_frozen_p_id_date as final_isometric_back_checking,
            afc_isometric_extracted_and_issued_to_sign_off_date as afc_isometric_extracted_and_issued_to_dcc,
            afc_isometric_transmittal_issued,
            hold_y_n as hold,
            hold_remarks as hold_remarks1,
            process,
            hold_initiation_date,
            mechanical,
            hold_initiation_date_1,
            instrumentation,
            hold_initiation_date_2,
            structural,
            hold_initiation_date_3,
            piping_stress,
            hold_initiation_date_4,
            piping_spec_material_related as piping_spec,
            hold_initiation_date_5,
            remarks_1 as hold_remarks2,
            '' as target_to_stress_completion_date_me3,
            '' as target_to_structural_completion_date_me4,
            '' as target_iso_lock_date_me5,
            '' as target_afc_date_me7,
            '' as process_critical_lines,
            '' as process_critical_lines2,
            '' as stress_calculation_number,
            '' as stress_calculation_number2,
            '' as piping_check_with_frozen_master_p_and_id,
            '' as checker,
            cast(execution_date as date) as extracted_date,
            source_system_name
        from
            {{ source('curated_isotracker', 'curated_bop_um_uz') }}
        where
            execution_date = (
                select
                    max(execution_date)
                from
                    {{ source('curated_isotracker', 'curated_bop_um_uz') }}
            )
    )
