{%- set run_date = "CURRENT_TIMESTAMP()" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_spi_component_function_type/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true
        ) 
}}


select
    cast(cmpnt_func_type_id as decimal(38, 0)) as cmpnt_func_type_id,
    cast(proj_id as decimal(38, 0)) as proj_id,
    cast(site_id as decimal(38, 0)) as site_id,
    cast(chg_num as decimal(38, 0)) as chg_num,
    cast(plant_id as decimal(38, 0)) as plant_id,
    cast(chg_status as varchar(500)) as chg_status,
    cast(user_name as varchar(300)) as user_name,
    cast(chg_date as date) as chg_date,
    cast(cmpnt_func_type_name as varchar(500)) as cmpnt_func_type_name,
    cast(cmpnt_func_type_desc as varchar(400)) as cmpnt_func_type_desc,
    cast(prf_spec as varchar(500)) as prf_spec,
    cast(prf_wiring as varchar(500)) as prf_wiring,
    cast(prf_cs_point as varchar(500)) as prf_cs_point,
    cast(prf_in_line_device as varchar(500)) as prf_in_line_device,
    cast(prf_hu_electrical as varchar(500)) as prf_hu_electrical,
    cast(prf_hu_pneumatic as varchar(500)) as prf_hu_pneumatic,
    cast(prf_hu_support as varchar(500)) as prf_hu_support,
    cast(prf_hu_process as varchar(500)) as prf_hu_process,
    cast(prf_hu_winterization as varchar(500)) as prf_hu_winterization,
    cast(prf_f1 as varchar(500)) as prf_f1,
    cast(prf_f2 as varchar(500)) as prf_f2,
    cast(prf_f3 as varchar(500)) as prf_f3,
    cast(prf_f4 as varchar(500)) as prf_f4,
    cast(prf_f5 as varchar(500)) as prf_f5,
    cast(calc_pd_type_id as decimal(38, 0)) as calc_pd_type_id,
    cast(dwg_external_blk_id as decimal(38, 0)) as dwg_external_blk_id,
    cast(panel_id as decimal(38, 0)) as panel_id,
    cast(cable_id as decimal(38, 0)) as cable_id,
    cast(landing_type_id as decimal(38, 0)) as landing_type_id,
    cast(proc_func_id as decimal(38, 0)) as proc_func_id,
    cast(spec_form_id as decimal(38, 0)) as spec_form_id,
    cast(hu_id as decimal(38, 0)) as hu_id,
    cast(hu_type_id as decimal(38, 0)) as hu_type_id,
    cast(bom_include_flg as varchar(500)) as bom_include_flg,
    cast(spec_dwg_id as decimal(38, 0)) as spec_dwg_id,
    cast(prf_io_type as varchar(500)) as prf_io_type,
    cast(cmpnt_io_type_id as decimal(38, 0)) as cmpnt_io_type_id,
    cast(prf_location as varchar(500)) as prf_location,
    cast(cmpnt_loc_id as decimal(38, 0)) as cmpnt_loc_id,
    cast(prf_pd_tag as varchar(500)) as prf_pd_tag,
    cast(prf_no_loop as varchar(500)) as prf_no_loop,
    cast(prf_pm as varchar(500)) as prf_pm,
    cast(prf_cs_tag as varchar(500)) as prf_cs_tag,
    cast(prf_dimension as varchar(500)) as prf_dimension,
    cast(dim_grp_id as decimal(38, 0)) as dim_grp_id,
    cast(prf_pd_requir as varchar(1)) as prf_pd_requir,
    cast(spec_format_id as decimal(38, 0)) as spec_format_id,
    cast(cstag_func_type_name as varchar(200)) as cstag_func_type_name,
    cast(proc_func_cat_id as decimal(38, 0)) as proc_func_cat_id,
    cast(prf_udt as varchar(500)) as prf_udt,
    cast(udt_support_id1 as decimal(38, 0)) as udt_support_id1,
    cast(udt_support_id2 as decimal(38, 0)) as udt_support_id2,
    cast(udt_support_id3 as decimal(38, 0)) as udt_support_id3,
    cast(udt_support_id4 as decimal(38, 0)) as udt_support_id4,
    cast(udt_support_id5 as decimal(38, 0)) as udt_support_id5,
    cast(udt_support_id6 as decimal(38, 0)) as udt_support_id6,
    cast(udt_support_id7 as decimal(38, 0)) as udt_support_id7,
    cast(udt_support_id8 as decimal(38, 0)) as udt_support_id8,
    cast(udt_support_id9 as decimal(38, 0)) as udt_support_id9,
    cast(udt_support_id10 as decimal(38, 0)) as udt_support_id10,
    cast(udt_support_id11 as decimal(38, 0)) as udt_support_id11,
    cast(udt_support_id12 as decimal(38, 0)) as udt_support_id12,
    cast(udt_support_id13 as decimal(38, 0)) as udt_support_id13,
    cast(udt_support_id14 as decimal(38, 0)) as udt_support_id14,
    cast(udt_support_id15 as decimal(38, 0)) as udt_support_id15,
    cast(udt_support_id16 as decimal(38, 0)) as udt_support_id16,
    cast(symbol_path as varchar(255)) as symbol_path,
    cast(device_type_id as varchar(500)) as device_type_id,
    cast(fb_tag_no as varchar(500)) as fb_tag_no,
    cast(fb_dev_address as varchar(500)) as fb_dev_address,
    cast(fb_dev_id as varchar(500)) as fb_dev_id,
    cast(fb_dc_cur as float) as fb_dc_cur,
    cast(capacitance as float) as capacitance,
    cast(capacitance_uom as varchar(500)) as capacitance_uom,
    cast(fb_min_transmit_level as float) as fb_min_transmit_level,
    cast(fb_min_volt as float) as fb_min_volt,
    cast(fb_max_volt as float) as fb_max_volt,
    cast(backup_link_master as varchar(500)) as backup_link_master,
    cast(prf_fieldbus as varchar(500)) as prf_fieldbus,
    cast(graphic_file_name as varchar(500)) as graphic_file_name,
    cast(cmpnt_fun_type_udf_c01 as varchar(500)) as cmpnt_fun_type_udf_c01,
    cast(cmpnt_fun_type_udf_c02 as varchar(500)) as cmpnt_fun_type_udf_c02,
    cast(cmpnt_fun_type_udf_c03 as varchar(500)) as cmpnt_fun_type_udf_c03,
    cast(cmpnt_fun_type_udf_c04 as varchar(500)) as cmpnt_fun_type_udf_c04,
    cast(cmpnt_fun_type_udf_c05 as varchar(500)) as cmpnt_fun_type_udf_c05,
    cast(cmpnt_fun_type_udf_c06 as varchar(500)) as cmpnt_fun_type_udf_c06,
    cast(cmpnt_fun_type_udf_c07 as varchar(500)) as cmpnt_fun_type_udf_c07,
    cast(cmpnt_fun_type_udf_c08 as varchar(500)) as cmpnt_fun_type_udf_c08,
    cast(cmpnt_fun_type_udf_c09 as varchar(500)) as cmpnt_fun_type_udf_c09,
    cast(cmpnt_fun_type_udf_c10 as varchar(500)) as cmpnt_fun_type_udf_c10,
    cast(cmpnt_fun_type_udf_c11 as varchar(500)) as cmpnt_fun_type_udf_c11,
    cast(cmpnt_fun_type_udf_c12 as varchar(500)) as cmpnt_fun_type_udf_c12,
    cast(cmpnt_fun_type_udf_c13 as varchar(500)) as cmpnt_fun_type_udf_c13,
    cast(cmpnt_fun_type_udf_c14 as varchar(500)) as cmpnt_fun_type_udf_c14,
    cast(cmpnt_fun_type_udf_c15 as varchar(500)) as cmpnt_fun_type_udf_c15,
    cast(cmpnt_fun_type_udf_c16 as varchar(500)) as cmpnt_fun_type_udf_c16,
    cast(cmpnt_fun_type_udf_c17 as varchar(500)) as cmpnt_fun_type_udf_c17,
    cast(cmpnt_fun_type_udf_c18 as varchar(500)) as cmpnt_fun_type_udf_c18,
    cast(cmpnt_fun_type_udf_c19 as varchar(500)) as cmpnt_fun_type_udf_c19,
    cast(cmpnt_fun_type_udf_c20 as varchar(500)) as cmpnt_fun_type_udf_c20,
    cast(prf_default as varchar(500)) as prf_default,
    cast(lop_class_uid as varchar(500)) as lop_class_uid,
    cast('VGCP2' as varchar(500)) as project_code,
    cast(execution_date as date) as extracted_date,
     source_system_name,
    cast(
        case
        when cmpnt_func_type_desc in (
            select
                instr_type_desc
            from
				{{ source('curated_spi', 'curated_dim_static_phyinstru') }}
        ) then 'y'
        else 'n' end as varchar(1)
    ) as phy_instru,
    {{run_date}} as model_created_date,
    {{run_date}} as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id  
from
    {{ source('curated_spi', 'curated_component_function_type') }}