SourceSystemId: csp_salesforce
MetadataType: api#csp_salesforce#user
api_parameter:
  endpoint: '{instance_url}/services/data/v{api_version}/query?q={soql_query}'
  sf_qualified_api_name: user
job_parameter:
  bucket_data_source_prefix: user
  bucket_name: ${raw_bucket}
  status_timeout: 60
  input_path: null
  output_s3: customer/csp_salesforce/user
  temp_output_path: temp/customer/csp_salesforce/user/raw
  sampling_fraction: '0.5'
  sampling_seed: 42
  schema_output_s3: customer/csp_salesforce/data_sampling/user
  full_incremental: I
  index_key: LastModifiedDate
  incremental_value_format: '{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{SSS}'
  incremental_default: 2020-01-01T00:00:00.000%2B0000
  job_process_folder: customer/csp_salesforce/audit_folder
  job_process_file: user/user.json
  is_named_col: true
  named_columns: Id,Name,FirstName,LastName,Username,Email,Alias,Title,Department,CompanyName
name: user
aws_region: ${region}
