SourceSystemId: csp_salesforce
MetadataType: api#csp_salesforce#b_p_request__c
api_parameter:
  endpoint: '{instance_url}/services/data/v{api_version}/query?q={soql_query}'
  sf_qualified_api_name: b_p_request__c
job_parameter:
  bucket_data_source_prefix: b_p_request__c
  bucket_name: ${raw_bucket}
  status_timeout: 60
  input_path: null
  output_s3: customer/csp_salesforce/b_p_request__c
  temp_output_path: temp/customer/csp_salesforce/b_p_request__c/raw
  sampling_fraction: '0.5'
  sampling_seed: 42
  schema_output_s3: customer/csp_salesforce/data_sampling/b_p_request__c
  full_incremental: I
  index_key: LastModifiedDate
  incremental_value_format: '{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{SSS}'
  incremental_default: 2020-01-01T00:00:00.000%2B0000
  job_process_folder: customer/csp_salesforce/audit_folder
  job_process_file: b_p_request__c/b_p_request__c.json
  is_named_col: true
  named_columns: Id,B_P_Budget_Corporate__c,B_P_Budget_Contract__c,Status__c,Sales_Lead__c,Jacobs_Sales_Lead__c,Opportunity__c,Work_Hours__c
is_active: Y
name: b_p_request__c
aws_region: ${region}
