name: Publish Metadata assests


on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "dev-templates/**"
      - "env_config.yaml"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  pull-requests: write

jobs:
  sync-prd:
    runs-on: ubuntu-latest
    environment: prd
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Assume AWS IAM Role
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::471112986846:role/github-oidc-provider-aws
          role-session-name: Worley_AWS_Metadata_${{ github.run_id }}
          role-duration-seconds: 3600 # 1 hour

      - run: aws sts get-caller-identity

      - name: Zip the dev-templates folder and env_config.yaml
        id: Zip_Metadata_files
        run: |
          mkdir -p source_code
          cp -r dev-templates source_code/
          cp env_config.yaml source_code/
          cd source_code
          zip -r source_code.zip .

      - name: Publish Metadata files
        id: Metadata_files
        working-directory: source_code
        run: aws s3 cp ./source_code.zip s3://worley-mf-sydney-prd-pipeline-artifacts-bucket/worley-mf-sydney-prd/
        continue-on-error: false
