{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}

{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_ecosys_ecodata/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
		tags=["ecosys"]
        ) 
}}

select
    project_id as projectid,
    cost_object_hierarchy_path_id as costobjecthierarchypathid,
    billableyesnoname,
    obcost,
    obsell,
    approved_changes_cost as approvedchangescost,
    approved_changes_sell as approvedchangessell,
    pending_changes_cost as pendingchangescost,
    pending_changes_sell as pendingchangessell,
    current_budget_cost as cbcost,
    current_budget_sell as cbsell,
    actual_costs as actualcosts,
    alternate_actual_costs as alternateactualcosts,
    working_forecast_cfc as workingforecastcfc,
    working_forecast_cfs as workingforecastcfs,
    original_budget as originalbudgeth,
    approved_changes as approvedchangesh,
    pending_changes as pendingchangesh,
    current_budget_hours as cbhours,
    actual_units as actualunits,
    cfhours as cfhours,
    code_of_account_id as codeofaccountid,
    code_of_account_name as codeofaccountname,
    cost_type_id as costtypeid,
    cost_type_name as costtypename,
    cost_object_id as costobjectid,
    cost_object_name as costobjectname,
    wbs_id_namel01 as wbsidnamel01,
    wbs_id_namel02 as wbsidnamel02,
    wbs_id_namel03 as wbsidnamel03,
    wbs_id_namel04 as wbsidnamel04,
    wbs_id_namel05 as wbsidnamel05,
    wbs_id_namel06 as wbsidnamel06,
    wbs_id_namel07 as wbsidnamel07,
    wbs_id_namel08 as wbsidnamel08,
    wbs_id_namel09 as wbsidnamel09,
    wbs_id_namel10 as wbsidnamel10,
    pcs_ct_category as pcsctcategory,
    planned_cost as plannedcost,
    planned_sell as plannedsell,
    earned_cost as earnedcost,
    earned_sell as earnedsell,
    planned_hours as plannedhours,
    earned_hours as earnedhours,
    original_budget_start_date AS originalbudgetstartdate,
    original_budget_end_date AS originalbudgetenddate,
    working_forecast_end_date AS workingforecastenddate,
    committed_cost as committedcost,
    committed_sell as committedsell,
    top_task_id as toptaskid,
    pa_date,
    snapshot_id as snapshotid,
    secorg_id as secorgid,
    execution_date,
    ctinternalid as ct_internal_id,
    coainternalid as coa_internal_id,
    '' as status,
    '' as status_update_date,
    is_current,	
    controlaccountinternalid as control_account_internal_id,
    projectinternalid as project_internal_id,
    {{run_date}} as created_date,
    {{run_date}} as updated_date,
    {{ generate_load_id(model) }} as load_id
from
    {{ ref('transformed_vw_ecosys_secorg_ecodata_latest') }}    
where
    status = 'active' AND is_current = '1'
