{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}

{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'ecosys/transformed_deliverable/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
		tags=["ecosys"]
        ) 
}}

select 
    deliverable_actualfinish as actualfinish,
	deliverable_actualstart as actualstart,
	deliverable_apprchghrs as apprchghrs,
	deliverable_budgethours as budgethours,
	deliverable_caid as caid,
	deliverable_cainternalid as cainternalid,
	deliverable_caname as caname,
	deliverable_classification as classification,
	deliverable_complete as complete,
	deliverable_currentbgthrs as currentbgthrs,
	deliverable_delid as delid,
	deliverable_delinternalid as delinternalid,
	deliverable_delname as delname,
	deliverable_delowner as delowner,
	deliverable_delegate as delegate,
	deliverable_doctype as doctype,
	deliverable_doctypeid as doctypeid,
	deliverable_earnedhours as earnedhours,
	deliverable_ftchours as ftchours,
	deliverable_forecastfinish as forecastfinish,
	deliverable_forecaststart as forecaststart,
	deliverable_gatemethod as gatemethod,
	deliverable_gatename as gatename,
	deliverable_getseq as getseq,
	deliverable_milestone as milestone,
	deliverable_pendingchghrs as pendingchghrs,
	deliverable_plannedfinish as plannedfinish,
	deliverable_plannedstart as plannedstart,
	deliverable_planningactivity as planningactivity,
	deliverable_project as project,
	deliverable_projectinternalid as projectinternalid,
	deliverable_qty as qty,
	deliverable_responsibility as responsibility,
	deliverable_rev as rev,
	deliverable_revdate as revdate,
	deliverable_secorg as secorg,
	deliverable_status as status,
	deliverable_systemdate as systemdate,
	deliverable_udf01 as udf01,
	deliverable_udf02 as udf02,
	deliverable_udf03 as udf03,
	deliverable_udf04 as udf04,
	deliverable_udf05 as udf05,
	deliverable_udf06 as udf06,
	deliverable_udf07 as udf07,
	deliverable_udf08 as udf08,
	deliverable_udf09 as udf09,
	deliverable_udf10 as udf10,
    execution_date,
    source_system_name,
    {{run_date}} as created_date,
    {{run_date}} as updated_date,
    {{ generate_load_id(model) }} as load_id
FROM {{ source('curated_ecosys','curated_deliverable') }}