{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}

{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'ecosys/transformed_control_account/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
		tags=["ecosys"]
        ) 
}}

select 
    controlaccount_acost as acost,
    controlaccount_ahours as ahours,
    controlaccount_asell as asell,
    controlaccount_apprchgcost as apprchgcost,
    controlaccount_apprchghours as apprchghours,
    controlaccount_apprchgsell as apprchgsell,
    controlaccount_bcost as bcost,
    controlaccount_bhours as bhours,
    controlaccount_bsell as bsell,
    controlaccount_billable as billable,
    controlaccount_cacc01id as cacc01id,
    controlaccount_cacc01name as cacc01name,
    controlaccount_cacc02id as cacc02id,
    controlaccount_cacc02name as cacc02name,
    controlaccount_cacc03id as cacc03id,
    controlaccount_cacc03name as cacc03name,
    controlaccount_cacc04id as cacc04id,
    controlaccount_cacc04name as cacc04name,
    controlaccount_caid as caid,
    controlaccount_cainternalid as cainternalid,
    controlaccount_caname as caname,
    controlaccount_castatus as castatus,
    controlaccount_closedca as closedca,
    controlaccount_codeofaccountid as codeofaccountid,
    controlaccount_codeofaccountname as codeofaccountname,
    controlaccount_committedcost as committedcost,
    controlaccount_committedsell as committedsell,
    controlaccount_costtypeid as costtypeid,
    controlaccount_costtypename as costtypename,
    controlaccount_currency as currency,
    controlaccount_customercaowner as customercaowner,
    controlaccount_ecost as ecost,
    controlaccount_ehours as ehours,
    controlaccount_esell as esell,
    controlaccount_faccost as faccost,
    controlaccount_fachours as fachours,
    controlaccount_facsell as facsell,
    controlaccount_ftccost as ftccost,
    controlaccount_ftchours as ftchours,
    controlaccount_ftcsell as ftcsell,
    controlaccount_forecastfinish as forecastfinish,
    controlaccount_forecaststart as forecaststart,
    controlaccount_ocost as ocost,
    controlaccount_ohours as ohours,
    controlaccount_osell as osell,
    controlaccount_originalfinish as originalfinish,
    controlaccount_originalstart as originalstart,
    controlaccount_pendingbgtcost as pendingbgtcost,
    controlaccount_pendingbgthours as pendingbgthours,
    controlaccount_pendingbgtsell as pendingbgtsell,
    controlaccount_pendingchgcost as pendingchgcost,
    controlaccount_pendingchghours as pendingchghours,
    controlaccount_pendingchgsell as pendingchgsell,
    controlaccount_portfoliocacode01id as portfoliocacode01id,
    controlaccount_portfoliocacode01name as portfoliocacode01name,
    controlaccount_portfoliocacode02id as portfoliocacode02id,
    controlaccount_portfoliocacode02name as portfoliocacode02name,
    controlaccount_portfoliocacode03id as portfoliocacode03id,
    controlaccount_portfoliocacode03name as portfoliocacode03name,
    controlaccount_portfoliocacode04id as portfoliocacode04id,
    controlaccount_portfoliocacode04name as portfoliocacode04name,
    controlaccount_portfoliocacode05id as portfoliocacode05id,
    controlaccount_portfoliocacode05name as portfoliocacode05name,
    controlaccount_portfoliocacode06id as portfoliocacode06id,
    controlaccount_portfoliocacode06name as portfoliocacode06name,
    controlaccount_portfoliocacode07id as portfoliocacode07id,
    controlaccount_portfoliocacode07name as portfoliocacode07name,
    controlaccount_portfoliocacode08id as portfoliocacode08id,
    controlaccount_portfoliocacode08name as portfoliocacode08name,
    controlaccount_portfoliocacode09id as portfoliocacode09id,
    controlaccount_portfoliocacode09name as portfoliocacode09name,
    controlaccount_portfoliocacode10id as portfoliocacode10id,
    controlaccount_portfoliocacode10name as portfoliocacode10name,
    controlaccount_projstatus as projstatus,
    controlaccount_project as project,
    controlaccount_projectinternalid as projectinternalid,
    controlaccount_secorg as secorg,
    controlaccount_systemdate as systemdate,
    controlaccount_udf01 as udf01,
    controlaccount_udf02 as udf02,
    controlaccount_udf03 as udf03,
    controlaccount_udf04 as udf04,
    controlaccount_udf05 as udf05,
    controlaccount_udf06 as udf06,
    controlaccount_udf07 as udf07,
    controlaccount_udf08 as udf08,
    controlaccount_udf09 as udf09,
    controlaccount_udf10 as udf10,
    controlaccount_wbsid01 as wbsid01,
    controlaccount_wbsid02 as wbsid02,
    controlaccount_wbsid03 as wbsid03,
    controlaccount_wbsid04 as wbsid04,
    controlaccount_wbsid05 as wbsid05,
    controlaccount_wbsid06 as wbsid06,
    controlaccount_wbsid07 as wbsid07,
    controlaccount_wbsid08 as wbsid08,
    controlaccount_wbsid09 as wbsid09,
    controlaccount_wbsid10 as wbsid10,
    controlaccount_wbsnamel01 as wbsnamel01,
    controlaccount_wbsnamel02 as wbsnamel02,
    controlaccount_wbsnamel03 as wbsnamel03,
    controlaccount_wbsnamel04 as wbsnamel04,
    controlaccount_wbsnamel05 as wbsnamel05,
    controlaccount_wbsnamel06 as wbsnamel06,
    controlaccount_wbsnamel07 as wbsnamel07,
    controlaccount_wbsnamel08 as wbsnamel08,
    controlaccount_wbsnamel09 as wbsnamel09,
    controlaccount_wbsnamel10 as wbsnamel10,
    controlaccount_worleycaowner as worleycaowner,
    execution_date,
    source_system_name,
    {{run_date}} as created_date,
    {{run_date}} as updated_date,
    {{ generate_load_id(model) }} as load_id
FROM {{ source('curated_ecosys','curated_control_account') }}