{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False',
        custom_location=target.location ~ 'ecosys/transformed_ecosys_header/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["ecosys","v2"]
        )
}}
 
select
    header_completedby as completed_by,
    header_projectstartdate as project_start_date,
    header_projectenddate as project_forecast_end_date,
    case when header_projecttypeidname <> '' then header_projecttypeidname else null end as project_type,
    header_worleycontractingentityorjvid as wp_contracting_entity,
    case when header_businesslineidname <> '' then header_businesslineidname else null end as business_line,
    '' as advisian_service_line,
    header_serviceunitidname as service_unit,
    case when header_industrysectoridname <> '' then header_industrysectoridname else null end as sector,
    header_industrysubsectoridname as industry_sub_sector,
    case when header_homeofficelocationidname <> '' then header_homeofficelocationidname else null end as home_office_location,
    header_projectexecutionlocation as project_execution_location,
    header_projectname as project_title,
    header_proposalnumber as proposal_no,
    header_projectid as project_no,
    '' as crmt_entry_no,
    header_gbsprojecttemplateidname as gbs_project_template,
    header_customer as customer_name,
    header_existingcustomerreferenceno as existing_customer_reference_no,
    header_customercontactname as customer_contact_name,
    header_billtoaddressline1 as bill_to_address_line_1,
    header_billtoaddressline2 as bill_to_address_line_2,
    header_billtoaddressline3 as bill_to_address_line_3,
    header_billtoaddressline4 as bill_to_address_line_4,
    header_billtoaddressline5 as bill_to_address_line_5,
    header_shiptoaddressline1 as ship_to_address_line_1,
    header_shiptoaddressline2 as ship_to_address_line_2,
    header_shiptoaddressline3 as ship_to_address_line_3,
    header_shiptoaddressline4 as ship_to_address_line_4,
    header_shiptoaddressline1 as ship_to_address_line_5,
    header_estimatedwphours as estimated_wp_hours,
    header_estimatedwprevenue as estimated_wp_revenue,
    header_costobjectcurrencycodename as project_currency,
    case when header_projectsizeclassificationidname <> '' then header_projectsizeclassificationidname else null end as project_size_classification,
    case when header_servicetypeidname <> '' then header_servicetypeidname else null end as service_type,
    case when header_projectriskclassificationid <> '' then header_projectriskclassificationid else null end as project_risk_classification,
    header_billingtypename as billing_type,
    case when header_billingtypename <> '' then header_billingtypename else null end as billing_type_name,
    header_existingwpcontractyesno as existing_wp_contract,
    header_contractnumberifexisting as contract_no,
    header_purchaseordernumber as purchase_order_no,
    header_contractualbasisforcommencementofbillableworkidname as contractual_basis_for_commencement_of_billable_work,
    header_projectsponsor as project_sponsor,
    header_projectmanager as project_manager,
    header_projectcontroller as project_controller,
    header_riskformattachedyesno as risk_form_attached,
    header_assoldbasisattachedyesno as as_sold_basis_attached,
    header_checklistcsocattachedyesno as checklist_csoc_attached,
    header_wopocontractattachedyesno as wo_po_contract_attached,
    header_projectmanagername as project_manager_name,
    '' as pm_date,
    header_authorizedsignatorysignaturedate as authorized_signatory_name,
    '' as asn_date,
    header_projectapprovalstatusid as approval_status_id,
    header_approvaldate as approval_date,
    header_approvedrejectedby as approved_by,
    header_rundate as run_date,
    header_proposalbudget as proposal_budget,
    case when header_customertypeidname <> '' then header_customertypeidname else null end as customer_type,
    header_internalentity as internal_entity,
    header_earnedvalueweightingid as earned_value_weighting,
    header_legacywbs as legacy_wbs,
    header_imagepath1 as image_path1,
    header_imagepath2 as image_path2,
    header_pcac01 as pcac1,
    header_pcac02 as pcac2,
    header_pcac03 as pcac3,
    header_pcac04 as pcac4,
    header_pcac05 as pcac5,
    header_pcac06 as pcac6,
    header_pcac07 as pcac7,
    header_pcac08 as pcac8,
    header_pcac09 as pcac9,
    header_pcac10 as pcac10,
    header_ownerorganizationid as ownerorganizationid,
    header_hwpcoactlibrary as hwpcoa_ctlibrary,
    cast(header_projectfunding as float) as project_funding,
    header_projectinternalid as project_internal_id,
    header_alternateid as alternate_id,
    header_sustainability as sustainability,
    header_countryofasset as countryofasset,
    header_assettype as asset_type,
    header_majorproject as major_project,
    header_customerprojectmanager as customer_project_manager,
    header_customerinternalentity as customer_internal_entity,
    header_smallprojectmoc as small_project_moc,
    header_closeddate as closed_date,
    header_forecastperioddate as forecast_period_date,
    header_snapshotdate as snap_shot_date,
    header_lastrequestmadefordocuments as last_request_madefor_documents,
    header_projectcreatedate as project_create_date,
    header_portfolioprojectgrouping as portfolio_project_grouping,
    header_udf01 as udf01,
    header_udf02 as udf02,
    header_udf03 as udf03,
    header_udf04 as udf04,
    header_udf05 as udf05,
    header_udf06 as udf06,
    header_udf07 as udf07,
    header_udf08 as udf08,
    header_udf09 as udf09,
    header_udf10 as udf10,
    header_secorgprojectcat01 as sec_org_project_cat01,
    header_secorgprojectcat02 as sec_org_project_cat02,
    header_secorgprojectcat03 as sec_org_project_cat03,
    header_secorgprojectcat04 as sec_org_project_cat04,
    header_secorgprojectcat05 as sec_org_project_cat05,
    header_secorgprojectcat06 as sec_org_project_cat06,
    header_secorgprojectcat07 as sec_org_project_cat07,
    header_secorgprojectcat08 as sec_org_project_cat08,
    header_secorgprojectcat09 as sec_org_project_cat09,
    header_secorgprojectcat10 as sec_org_project_cat10,
{{run_date}} as created_date,
{{run_date}} as updated_date,
{{ generate_load_id(model) }} as load_id
from 
    {{ source('curated_ecosys', 'curated_header') }}
where
    is_current = 1
