{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = "CURRENT_DATE" -%}

{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_timephased/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
		tags=["ecosys"]
        ) 
}}

SELECT 
    secorg,
    project,
    projectinternalid,
    systemdate,
    caid,
    cainternalid,
    majorperiod,
    minorperiod,
    ohours,
    bhours,
    chours,
    pendingchghours,
    pendingbgthours,
    ahours,
    ehours,
    ftchours,
    fachours,
    ocost,
    bcost,
    ccost,
    pendingchgcost,
    pendingbgtcost,
    acost,
    ecost,
    ftccost,
    faccost,
    osell,
    bsell,
    csell,
    pendingchgsell,
    pendingbgtsell,
    asell,
    esell,
    ftcsell,
    facsell,
    committedcost,
    committedsell,
    ca,
    billableyesnoid,
    codeofaccountidname,
    costtypeid,
    costtypeinternalid,
    cast(execution_date as date),
    source_system_name,
    {{run_date}} as created_date,
    {{run_date}} as updated_date,
    {{ generate_load_id(model) }} as load_id	
FROM {{ source('curated_ecosys', 'curated_timephased') }}
