version: 2

sources:
  - name: integrations_finance
    database: integrations
    schema: dbt_finance_product
    tables:
      - name: transformed_gbs_project
      - name: transformed_gbs_project_client
      - name: transformed_gbs_project_task
      - name: transformed_gbs_bp_daedalus
      - name: transformed_gbs_bp_program
      - name: transformed_gbs_nobian
      - name: transformed_gbs_sppt
      - name: transformed_gbs_shell_program
      - name: transformed_gbs_vendor_software_usage_analytics
      - name: transformed_gbs_susan_timesheet_data
      
      