redshift_permissions_config:
  - database_name: worley_nerve_center
    ad_roles:
      - role_name: AWS-PIM - DataPlatform Data Engineer - Non Prod
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        allowed_schemas:
          - name: project_control            #Product Schema starts here
          - name: supply_chain
          - name: document_control
          - name: project_control_product    #External Schema starts here
          - name: supply_chain_product
          - name: document_control_product
      - role_name: AWS-PIM - Dataplatform WNC Consumer - NonProd
        identity_provider: AWSIDC
        quicksight_role: quicksight # optional: only for AWS identity provider
        allowed_schemas:
          - name: project_control            #Product Schema starts here
          - name: supply_chain
          - name: document_control
          - name: project_control_product    #External Schema starts here
          - name: supply_chain_product
          - name: document_control_product
    iam_roles:
    users:
      - user_name: dbt_worley_nerve_center_user
        identity_provider: internal
        allowed_schemas:
          - name: dbt_document_control_product # default: usage and select permissions are granted
          - name: document_control
            permissions: CREATE 
          - name: dbt_supply_chain_product # default: usage and select permissions are granted
          - name: supply_chain
            permissions: CREATE
          - name: dbt_project_control_product # default: usage and select permissions are granted
          - name: project_control
            permissions: CREATE
          # - name: worley_nerve_center
          #   permissions: CREATE # optional: specify this if create on schema permission is required

### NOTE: DON'T GIVE AAD access to external schema