version: 2

sources:
  - name: curated_erm
    schema: "{{ var('curated_schema')[target.name] }}"
    tables:
      - name: po_hdr
      - name: proj
      - name: proj_cpv
      - name: po_hdr_cpv
      - name: cont
      - name: pay_term
      - name: po_code
      - name: cusp_value_list_item
      - name: inv_hdr
      - name: inv_hdr_cpv
      - name: suppl
      - name: suppl_addr
      - name: proc_int_stat
      - name: po_item
      - name: tmr_hdr
      - name: tmr_item_po_item
      - name: tmr_item
      - name: proj_fin_acc_code_cpv
      - name: proj_fin_acc_code
      - name: trans_term
      - name: proj_cost_acc
      - name: proj_sys_brkdwn
      - name: deliv_term
      - name: mat
      - name: part
      - name: commodity
      - name: std_mat
      - name: std_mat_cpv
      - name: proj_comp_cpv
      - name: receipt_hdr
      - name: receipt_item
      - name: mmt_hdr
      - name: receipt_hdr_cpv
      - name: expedite_item
      - name: inv_item
      - name: inv_pay
      - name: cont_addr
      - name: po_hdr_hist
      - name: tmr_hdr_hist
      - name: tmr_item_hist
      - name: po_item_hist
      - name: expedite_hdr
      - name: proc_sch_hdr
      - name: proc_sch_item
      - name: proc_sch_item_cpv
      - name: proc_milestone
      - name: calendar
      - name: proc_ext_stat
      - name: proj_planned_tmr_hdr
      - name: draw_discipline
      - name: legal_entity
      - name: site
      - name: deliv_addr
      - name: expedite_hdr_cpv
      - name: expedite_item_log
      - name: proj_comp
      - name: country
      - name: cont_person
      - name: usr
      - name: cur
      - name: std_mat_scheme
      - name: scheme
      - name: mat_grp_type
      - name: proc_sch_hdr_cpv
      - name: expedite_hdr_log
      - name: tmr_hdr_cpv
      - name: tmr_item_po_item_hist
      - name: pl_hdr
      - name: pl_item
      - name: pl_hdr_cpv
      - name: tmr_hdr_hist_cpv
      - name: supplier_country
      - name: location_hierarchy
      - name: project_location
      - name: taxonomy_master
      - name: ar_usr_grp_usr
      - name: ar_usr_grp_role
      - name: ar_role
      - name: dim_date
      - name: workflow_purpose
      - name: support_info_criteria_and_calculations
      - name: vat_type
      - name: po_hdr_hist_cpv
      - name: po_pay_plan
      - name: drl_hdr
      - name: drl_item
      - name: pick_lst_stat
      - name: site_mto_hdr
      - name: store_hdr
      - name: proj_std_txt
      - name: proj_std_txt_lang
      - name: pick_lst_item
      - name: pick_lst_hdr
      - name: pick_lst_hdr_cpv
      - name: site_mto_item
      - name: stock_trx
      - name: insp_sch
      - name: insp_sch_hdr
      - name: insp_sch_item
      - name: drl_hdr_cpv
      - name: draw
      - name: site_mto_hdr_cpv
      - name: business_units
      - name: ril_min_list
      - name: deliv_desig