{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = dbt.date_trunc("second", dbt.current_timestamp()) %}

{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_ewps/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["o3"]
    ) 
}}
     
select
    {{ dbt_utils.generate_surrogate_key(['projectid', 'name']) }} as ewps_key,
    id,
    projectid,
    projectinfo,
    name,
    statusid,
    status,
    CAST(statusdate AS DATE) as statusdate,
     cast(assemblystartdate as timestamp) as assemblystartdate,
     cast(assemblyfinishdate as timestamp) as assemblyfinishdate,
     releasedtouserid,
     releasedtouser,
	 CAST(percentdocumentedinclusive as FLOAT) as percentdocumentedinclusive,
	cast(dateconstraintfree as timestamp) as dateconstraintfree,
    cast(datedatacomplete as timestamp) as datedatacomplete,
     CAST(openconstraintcount as INT) as openconstraintcount,
     cast(datecloseoutdatacomplete as timestamp) as datecloseoutdatacomplete,
     datacompletenessstatus,
	CAST(contractgroupid as INT) as contractgroupid,
     contractgroup,
    CAST(overviewmodelshotattachmentid as INT) as overviewmodelshotattachmentid,
    CAST(criticalpath as BOOLEAN) as criticalpath,
	cast(plannedreadyforreviewdate as timestamp) as plannedreadyforreviewdate,
   cast(readyforreviewdate as timestamp) as readyforreviewdate,
	CAST(attachmentcount as INT) as attachmentcount,
    unitcategoryid,
    unitcategory,   
    labels,
    CAST(stateid as INT) as stateid,
    CAST(externallinkverified as BOOLEAN) as externallinkverified,
    externallinkverifiedbyuser,
    externallinkverifiedbyuserid,
    cast(externallinkverifieddate as timestamp) as externallinkverifieddate,
    cast(dateapprovedforconstruction as timestamp) as dateapprovedforconstruction,
    cast(plannedapprovedforconstructiondate as timestamp) as plannedapprovedforconstructiondate,
    cast(cwpplannedstartdate as timestamp) as cwpplannedstartdate,
    cast(cwpplannedfinishdate as timestamp) as cwpplannedfinishdate,
    cast(calendarstartdate as timestamp) as calendarstartdate,
    cast(calendarenddate as timestamp) as calendarenddate,
    statuscolor,
    CAST(annotateddrawingscount as INT ) as annotateddrawingscount,
    CAST(modelshot as BOOLEAN) as modelshot, 
    forecastduration,
    productivityfactor,
    CAST(plotplancount as INT) as plotplancount,
    CAST(entitytypeid as INT) as entitytypeid,
    cast(scheduledatadate as timestamp) as scheduledatadate,
    cast(earlystartdate as timestamp) as earlystartdate,
    cast(latestartdate as timestamp) as latestartdate,
   cast(earlyfinishdate as timestamp) as earlyfinishdate,
   cast(latefinishdate as timestamp) as latefinishdate,
   CAST(companyresponsibleid as INT) as companyresponsibleid,
   company,
   remarks,
    notes,
    ewpstatus,
    description,
    longdescription,
    significantrequirements,
    scopeexclusions,
    externallink,
    revision,
    CAST(revisiondate AS DATE) as revisiondate,
    constructionworkpackageid,
    cwp,
    unitid,
    unit,
    constructionworkareaid,
    constructionworkarea,
    zoneid,
    zone,
    constructiontypeid,
    constructiontype,
    areaid,
    area,
    disciplineid,
    discipline,
    purposeid,
    purpose,
    engineeruserid,
    engineeruser,
    CAST(drawingcount AS INT) as drawingcount,
    CAST(budgetedhours AS INT) as budgetedhours,
    CAST(estimatedhours AS INT) as estimatedhours,
    scheduleactivityid,
    CAST(plannedissuedate AS DATE) as plannedissuedate,
    CAST(actualissuedate AS DATE) as actualissuedate,
    CAST(issuedatevariance AS INT) as issuedatevariance,
    CAST(plannedstartdate AS DATE) as plannedstartdate,
    CAST(plannedstartyear AS INT) as plannedstartyear,
    CAST(plannedstartmonth AS INT) as plannedstartmonth,
    CAST(plannedstartweekofyear AS INT) as plannedstartweekofyear,
    CAST(plannedstartdayofyear AS INT) as plannedstartdayofyear,
    CAST(plannedstartweek AS INT) as plannedstartweek,
    CAST(actualstartdate AS DATE) as actualstartdate,
    CAST(actualstartyear AS INT) as actualstartyear,
    CAST(actualstartmonth AS INT) as actualstartmonth,
    CAST(actualstartweekofyear AS INT) as actualstartweekofyear,
    CAST(actualstartdayofyear AS INT) as actualstartdayofyear,
    CAST(startdatevariance AS INT) as startdatevariance,
    CAST(plannedfinishdate AS DATE) as plannedfinishdate,
    CAST(actualfinishdate AS DATE) as actualfinishdate,
    CAST(finishdatevariance AS INT) as finishdatevariance,
    CAST(actualfinishyear AS INT) as actualfinishyear,
    CAST(actualfinishmonth AS INT) as actualfinishmonth,
    CAST(actualfinishweekofyear AS INT) as actualfinishweekofyear,
    CAST(actualfinishdayofyear AS INT) as actualfinishdayofyear,
    CAST(datereleased AS DATE) as datereleased,
    CAST(datedelivered AS DATE) as datedelivered,
    CAST(earnedhours AS INT) as earnedhours,
    CAST(actualhours AS INT) as actualhours,
    CAST(forecastedhours AS INT) as forecastedhours,
    CAST(percentcomplete AS FLOAT) as percentcomplete,
    CAST(percentdocumented AS FLOAT) as percentdocumented,
    CAST(percentconstraintfree AS FLOAT) as percentconstraintfree,
    CAST(percentdelayfree AS FLOAT) as percentdelayfree,
    CAST(percentapproved AS FLOAT) as percentapproved,
    CAST(percentdeveloped AS FLOAT) as percentdeveloped,
    CAST(datecreated AS DATE) as datecreated,
    createdbyuserid,
    createdbyuser,
    CAST(datemodified AS DATE) as datemodified,
    modifiedbyuserid,
    modifiedbyuser,
    CAST(isdeleted AS BOOLEAN) as isdeleted,
    CAST(sourcedeleted AS BOOLEAN) as sourcedeleted,
    contractid,
    contract,
    planneruserid,
    planneruser,
    plannerusercompany,
    CAST(draftreviewdate AS DATE) as draftreviewdate,
    CAST(plannedapproveddate AS DATE) as plannedapproveddate,
    CAST(approveddate AS DATE) as approveddate,
    CAST(planneddevelopmentstartdate AS DATE) as planneddevelopmentstartdate,
    CAST(actualdevelopmentstartdate AS DATE) as actualdevelopmentstartdate,
    CAST(plannedcloseoutdate AS DATE) as plannedcloseoutdate,
    CAST(actualcloseoutdate AS DATE) as actualcloseoutdate,
    CAST(plannedduration AS INT) as plannedduration,
    CAST(actualduration AS INT) as actualduration,
    CAST(baselinestartdate AS DATE) as baselinestartdate,
    CAST(baselinefinishdate AS DATE) as baselinefinishdate,
    CAST(forecaststartdate AS DATE) as forecaststartdate,
    CAST(forecastfinishdate AS DATE) as forecastfinishdate,
    datemodified_ts,
    source_system_name,
    primary_key,
    is_current,
    eff_start_date,
    eff_end_date,
    cast(execution_date as DATE) as execution_date,
    CAST({{run_date}} as DATE) as model_created_date,
    CAST({{run_date}} as DATE) as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from {{ source('curated_o3', 'curated_ewps') }}
where is_current = 1
{%- if execution_date_arg != "" %}
    and execution_date >= '{{ execution_date_arg }}'
{%- else %}
    {%- if is_incremental() %}
        and cast(execution_date as DATE) > (select max(execution_date) from {{ this }})
    {%- endif %}
{%- endif %}
 