{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = dbt.date_trunc("second", dbt.current_timestamp()) %}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_iwps/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["o3"]
    )
}}
   
select 
    {{ dbt_utils.generate_surrogate_key(['projectid', 'id', 'name']) }} as iwpspk,
    a.id as ID,
    a.name,
    a.constructionworkarea,
    a.area,
    a.constructiontype,
    a.zone,
    CAST(a.issuedatevariance AS INT) AS issuedatevariance,
    a.cwpdescription,
    CAST(a.cwpscheduleactivityid AS INT) AS cwpscheduleactivityid,
    CAST(a.cwpplannedstartdate AS TIMESTAMP) AS cwpplannedstartdate,
    a.discipline,
    a.disciplinedescription,
    CAST(a.cwpplannedfinishdate AS TIMESTAMP) AS cwpplannedfinishdate,
    CAST(a.plannedstartyear AS INT) AS plannedstartyear,
    CAST(a.plannedstartmonth AS INT) AS plannedstartmonth,
    CAST(a.plannedstartweekofyear AS INT) AS plannedstartweekofyear,
    CAST(a.plannedstartdayofyear AS INT) AS plannedstartdayofyear,
    CAST(a.plannedstartweek AS INT) AS plannedstartweek,
    CAST(a.actualstartyear AS INT) AS actualstartyear,
    CAST(a.actualstartmonth AS INT) AS actualstartmonth,
    CAST(a.actualstartweekofyear AS INT) AS actualstartweekofyear,
    CAST(a.actualstartdayofyear AS INT) AS actualstartdayofyear,
    CAST(a.startdatevariance AS INT) AS startdatevariance,
    CAST(a.plannedfinishweek AS INT) AS plannedfinishweek,
    CAST(a.actualfinishyear AS INT) AS actualfinishyear,
    CAST(a.actualfinishmonth AS INT) AS actualfinishmonth,
    CAST(a.actualfinishweekofyear AS INT) AS actualfinishweekofyear,
    CAST(a.actualfinishdayofyear AS INT) AS actualfinishdayofyear,
    CAST(a.finishdatevariance AS INT) AS finishdatevariance,
    CAST(a.assemblystartweek AS INT) AS assemblystartweek,
    CAST(a.cwpstatusid AS INT) AS cwpstatusid,
    a.cwpstatus,
    a.cwpstatuscolor,
    CAST(a.id AS INT) as entityid,
    CAST(a.entitytypeid AS INT) as entitytypeid,
    CAST(a.constructionworkareaid AS INT) as constructionworkareaid,
    CAST(a.constructiontypeid AS INT) as constructiontypeid,
    CAST(a.disciplineid AS INT) as disciplineid,
    a.cwp as cwpsid,
    a.name as iwpsid,
    a.description as iwpsdescription,
    a.longdescription as iwpslongdescription,
    CAST(a.projectid AS INT) as projectid,
    a.projectcode as projectcode,
    a.projectinfo as projectinfo,
    CAST(a.statusid AS INT) as statusid,
    a.status as status,
    CAST(a.statusdate AS TIMESTAMP) as statusdate,
    a.iwpstatuscolor as iwpstatuscolor,
    a.significantrequirements as significantrequirements,
    a.scopeexclusions as scopeexclusions,
    a.externallink as externallink,
    a.workpackagetypeid as workpackagetypeid,
    a.workpackagetype as workpackagetype,
    a.revision as revision,
    CAST(a.constructionworkpackageid AS INT) as constructionworkpackageid,
    CAST(a.unitid AS INT) as unitid,
    a.unit as unit,
    a.deliveryteamid as deliveryteamid,
    a.deliveryteam as deliveryteam,
    CAST(a.zoneid AS INT) as zoneid,
    CAST(a.areaid AS INT) as areaid,
    CAST(b.RegionID AS INT) as RegionID,
    a.areacode as areacode,
    CAST(a.purposeid AS INT) as purposeid,
    a.purpose as purpose,
    a.purposecategoryid as purposecategoryid,
    a.purposecategory as purposecategory,
    CAST(a.contractid AS INT) as contractid,
    a.contract as contract,
    CAST(a.planneruserid AS INT) as planneruserid,
    a.planneruser as planneruser,
    a.planneruseremail as planneruseremail,
    a.plannerusercompany as plannerusercompany,
    CAST(a.drawingcount AS INT) as drawingcount,
    CAST(a.budgetedhours AS FLOAT) as budgetedhours,
    CAST(a.estimatedhours AS FLOAT) as estimatedhours,
    CAST(a.iwpsequencenumber AS INT) as iwpsequencenumber,
    a.scheduleactivityid as scheduleactivityid,
    a.taskcode as taskcode,
    CAST(a.plannedissuedate AS TIMESTAMP) as plannedissuedate,
    CAST(a.actualissuedate AS TIMESTAMP) as actualissuedate,
    CAST(a.plannedstartdate AS TIMESTAMP) as plannedstartdate,
    CAST(a.actualstartdate AS TIMESTAMP) as actualstartdate,
    CAST(a.plannedfinishdate AS TIMESTAMP) as plannedfinishdate,
    CAST(a.actualfinishdate AS TIMESTAMP) as actualfinishdate,
    CAST(a.assemblystartdate AS TIMESTAMP) as assemblystartdate,
    CAST(a.assemblyfinishdate AS TIMESTAMP) as assemblyfinishdate,
    a.releasedtouserid as releasedtouserid,
    a.releasedtouser as releasedtouser,
    CAST(a.datereleased AS TIMESTAMP) as datereleased,
    CAST(a.datedelivered AS TIMESTAMP) as datedelivered,
    CAST(a.earnedhours AS FLOAT) as earnedhours,
    CAST(a.actualhours AS FLOAT) as actualhours,
    CAST(a.forecastedhours AS FLOAT) as forecastedhours,
    a.productivityfactor as productivityfactor,
    CAST(a.percentcomplete AS FLOAT) as percentcomplete,
    CAST(a.percentdocumented AS FLOAT) as percentdocumented,
    CAST(a.percentdocumentedinclusive AS FLOAT) as percentdocumentedinclusive,
    CAST(a.openconstraintcount AS INT) as openconstraintcount,
    CAST(a.overdueconstraintcount AS INT) as overdueconstraintcount,
    CAST(a.totalconstraintcount AS INT) as totalconstraintcount,
    CAST(a.closedconstraintcount AS INT) as closedconstraintcount,
    CAST(a.percentconstraintfree AS FLOAT) as percentconstraintfree,
    a.percentdelayfree as percentdelayfree,
    CAST(a.percentapproved AS FLOAT) as percentapproved,
    CAST(a.percentdeveloped AS FLOAT) as percentdeveloped,
    a.subcwp as subcwp,
    a.iwpfilename as iwpfilename,
    a.iwpstatus as iwpstatus,
    CAST(a.keyquantity AS FLOAT) AS keyquantity,
    CAST(a.unitofmeasureid AS INT) as unitofmeasureid,
    a.uom as uom,
    CAST(a.draftreviewdate AS TIMESTAMP) as draftreviewdate,
    CAST(a.plannedreadyforreviewdate AS TIMESTAMP) as plannedreadyforreviewdate,
    CAST(a.readyforreviewdate AS TIMESTAMP) as readyforreviewdate,
    CAST(a.plannedapproveddate AS TIMESTAMP) as plannedapproveddate,
    CAST(a.approveddate AS TIMESTAMP) as approveddate,
    a.preparedfor as preparedfor,
    a.plannedduration as plannedduration,
    a.actualduration as actualduration,
    CAST(a.wbsid AS INT) as wbsid,
    a.wbs as wbs,
    a.wbsdescription as wbsdescription,
    a.sourceid as sourceid,
    a.source as source,
    a.sourceimportid as sourceimportid,
    CAST(a.sourcedatecreated AS TIMESTAMP) as sourcedatecreated,
    CAST(a.sourcedeleted AS BOOLEAN) as sourcedeleted,
    CAST(a.datecreated AS TIMESTAMP) as datecreated,
    CAST(a.createdbyuserid AS INT) as createdbyuserid,
    a.createdbyuser as createdbyuser,
    CAST(a.datemodified AS TIMESTAMP) as datemodified,
    CAST(a.modifiedbyuserid AS INT) as modifiedbyuserid,
    a.modifiedbyuser as modifiedbyuser,
    CAST(a.isdeleted AS BOOLEAN) as isdeleted,
    CAST(a.dateconstraintfree AS TIMESTAMP) as dateconstraintfree,
    CAST(a.datefirstconstraintcompleted AS TIMESTAMP) as datefirstconstraintcompleted,
    CAST(a.datefirstconstraintcreated AS TIMESTAMP) as datefirstconstraintcreated,
    CAST(a.datelastconstraintcreated AS TIMESTAMP) as datelastconstraintcreated,
    CAST(a.datedatacomplete AS TIMESTAMP) as datedatacomplete,
    CAST(a.datecloseoutdatacomplete AS TIMESTAMP) as datecloseoutdatacomplete,
    CAST(a.planneddevelopmentstartdate AS TIMESTAMP) as planneddevelopmentstartdate,
    CAST(a.actualdevelopmentstartdate AS TIMESTAMP) as actualdevelopmentstartdate,
    CAST(a.lastpackagedcomponentdate AS TIMESTAMP) as lastpackagedcomponentdate,
    CAST(a.constraintrollupstatusid AS INT) as constraintrollupstatusid,
    a.constraintrollupstatus as constraintrollupstatus,
    a.constraintrollupstatuscolor as constraintrollupstatuscolor,
    a.datacompletenessstatus as datacompletenessstatus,
    CAST(a.calendarstartdate AS TIMESTAMP) as calendarstartdate,
    CAST(a.calendarenddate AS TIMESTAMP) as calendarenddate,
    CAST(a.crewsize AS INT) as crewsize,
    a.workconditionid as workconditionid,
    a.workcondition as workcondition,
    CAST(a.revisiondate AS TIMESTAMP) as revisiondate,
    a.tradecoordinationnotes as tradecoordinationnotes,
    a.plantoperationsnotes as plantoperationsnotes,
    a.specialtycontractornotes as specialtycontractornotes,
    a.qualitynotes as qualitynotes,
    a.toolnotes as toolnotes,
    a.constructionequipmentnotes as constructionequipmentnotes,
    a.overviewmodelshotattachmentid as overviewmodelshotattachmentid,
    CAST(a.actualcloseoutdate AS TIMESTAMP) as actualcloseoutdate,
    CAST(a.plannedcloseoutdate AS TIMESTAMP) as plannedcloseoutdate,
    CAST(a.contractgroupid AS INT) as contractgroupid,
    a.contractgroup as contractgroup,
    CAST(a.criticalpath AS BOOLEAN) as criticalpath,
    a.criticalpathcategoryid as criticalpathcategoryid,
    a.criticalpathcategory as criticalpathcategory,
    a.statuscolor as statuscolor,
    a.safetynotes as safetynotes,
    CAST(a.dateapprovedforconstruction AS TIMESTAMP) as dateapprovedforconstruction,
    a.fccnotes as fccnotes,
    a.lessonslearnednotes as lessonslearnednotes,
    a.interfacesnotes as interfacesnotes,
    a.specialnotes as specialnotes,
    a.turnoversystemid as turnoversystemid,
    a.turnoversystem as turnoversystem,
    a.turnoversubsystemid as turnoversubsystemid,
    a.turnoversubsystem as turnoversubsystem,
    CAST(a.baselinestartdate AS TIMESTAMP) as baselinestartdate,
    CAST(a.baselinefinishdate AS TIMESTAMP) as baselinefinishdate,
    CAST(a.attachmentcount AS INT) as attachmentcount,
    a.foremanuserid as foremanuserid,
    a.foreman as foreman,
    a.foreman2userid as foreman2userid,
    a.foreman2 as foreman2,
    a.foreman3userid as foreman3userid,
    a.foreman3 as foreman3,
    a.alternateforemanuserid as alternateforemanuserid,
    a.alternateforeman as alternateforeman,
    a.generalforemanuserid as generalforemanuserid,
    a.generalforeman as generalforeman,
    a.generalforemanemail as generalforemanemail,
    a.generalforeman2userid as generalforeman2userid,
    a.generalforeman2 as generalforeman2,
    a.generalforeman2email as generalforeman2email,
    a.generalforeman3userid as generalforeman3userid,
    a.generalforeman3 as generalforeman3,
    a.generalforeman3email as generalforeman3email,
    a.superintendentuserid as superintendentuserid,
    a.superintendent as superintendent,
    a.superintendentemail as superintendentemail,
    a.superintendent2userid as superintendent2userid,
    a.superintendent2 as superintendent2,
    a.superintendent2email as superintendent2email,
    a.superintendent3userid as superintendent3userid,
    a.superintendent3 as superintendent3,
    a.superintendent3email as superintendent3email,
    a.testsystemid as testsystemid,
    a.testsystem as testsystem,
    a.testsubsystemid as testsubsystemid,
    a.testsubsystem as testsubsystem,
    a.permitissuerid as permitissuerid,
    a.permitissuer as permitissuer,
    a.latestartrootcauseid as latestartrootcauseid,
    a.latestartrootcause as latestartrootcause,
    a.latefinishrootcauseid as latefinishrootcauseid,
    a.latefinishrootcause as latefinishrootcause,
    a.companysupervisorid as companysupervisorid,
    a.companysupervisor as companysupervisor,
    a.contractorsupervisorid as contractorsupervisorid,
    a.contractorsupervisor as contractorsupervisor,
    a.unitcategoryid as unitcategoryid,
    a.unitcategory as unitcategory,
    a.labels as labels,
    a.stateid as stateid,
    CAST(a.forecaststartdate AS TIMESTAMP) as forecaststartdate,
    CAST(a.forecastfinishdate AS TIMESTAMP) as forecastfinishdate,
    CAST(a.externallinkverified AS BOOLEAN) as externallinkverified,
    a.externallinkverifiedbyuser as externallinkverifiedbyuser,
    a.externallinkverifiedbyuserid as externallinkverifiedbyuserid,
    CAST(a.externallinkverifieddate AS TIMESTAMP) as externallinkverifieddate,
    CAST(a.plannedapprovedforconstructiondate AS TIMESTAMP) as plannedapprovedforconstructiondate,
    a.forgemodelshotstate as forgemodelshotstate,
    CAST(a.invalidmodeldata AS BOOLEAN) as invalidmodeldata,
    a.operationsrequirements as operationsrequirements,
    CAST(a.projectphaseid AS INT) as projectphaseid,
    a.projectphase as projectphase,
    CAST(a.criticalpath2 AS BOOLEAN) as criticalpath2,
    CAST(a.systemrequired AS BOOLEAN) as systemrequired,
    CAST(a.plannedreleasedtoqualitydate AS TIMESTAMP) as plannedreleasedtoqualitydate,
    CAST(a.actualreleasedtoqualitydate AS TIMESTAMP) as actualreleasedtoqualitydate,
    a.rigginglocationid as rigginglocationid,
    a.rigginglocation as rigginglocation,
    CAST(a.tasksneedingcalculationcount AS INT) as tasksneedingcalculationcount,
    CAST(a.modelshot AS BOOLEAN) as modelshot,
    a.forecastduration as forecastduration,
    a.insulationtypeid  as insulationtypeid,
    a.insulationtype as insulationtype,
    a.painttypeid  as painttypeid,
    a.painttype as painttype,
    a.hydrotesttypeid AS  hydrotesttypeid,
    a.hydrotesttype as hydrotesttype,
    CAST(a.estimatedcost AS FLOAT) as estimatedcost,
    CAST(a.forecastcost AS FLOAT) as forecastcost,
    CAST(a.actualcost AS FLOAT) as actualcost,
    a.scheduleactivitylookupid as scheduleactivitylookupid,
    a.scheduleactivity as scheduleactivity,
    CAST(a.plotplancount AS INT) as plotplancount,
    a.crewid as crewid,
    a.crew as crew,
    CAST(a.scaffoldingrequired AS BOOLEAN) as scaffoldingrequired,
    CAST(a.remaininghours AS FLOAT) as remaininghours,
    CAST(a.scheduledatadate AS TIMESTAMP) as scheduledatadate,
    CAST(a.earlystartdate AS TIMESTAMP) as earlystartdate,
    CAST(a.latestartdate AS TIMESTAMP) as latestartdate,
    CAST(a.earlyfinishdate AS TIMESTAMP) as earlyfinishdate,
    CAST(a.latefinishdate AS TIMESTAMP) as latefinishdate,
    CAST(a.workingdayduration AS FLOAT) as workingdayduration,
    CAST(a.developedhours AS FLOAT) AS developedhours,
    a.functionalareaid as functionalareaid,
    a.functionalarea as functionalarea,
    a.is_current,
    cast(a.execution_date as DATE) as execution_date,
    CAST({{run_date}} as DATE) as model_created_date,
    CAST({{run_date}} as DATE) as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from {{ source('curated_o3', 'curated_iwps') }} a
left join {{ ref('transformed_region') }} b ON a.zoneid = b.zoneid and a.areaid = b.areaid
where a.is_current = 1
{%- if execution_date_arg != "" %}
    and a.execution_date >= '{{ execution_date_arg }}'
{%- else %}
    {%- if is_incremental() %}
        and cast(a.execution_date as DATE) >
            (select MAX(cast(execution_date as DATE)) as max_execution_date
            from {{ this }})
    {%- endif %}
{%- endif %} 