{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = dbt.date_trunc("second", dbt.current_timestamp()) %}

{{
    config(
        
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_construction_components/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["o3"]
    )
}}
     
select
    {{ dbt_utils.generate_surrogate_key(['projectid', 'componenttype', 'componenttypeid', 'lookupkey', 'objecttype']) }} as construction_component_key,
    id,
    projectid,
    tagnumber,
    lookupkey,
    systempath,
    drawingid,
    uniqueid,
    drawing,
    drawingsourceurn,
    drawingmaterialavailabilityid,
    drawingmaterialavailability,
    drawingmaterialavailabilitycolor,
    componenttypeid,
    componenttype,
    datecreated,
    createdbyuserid,
    createdbyuser,
    datemodified,
    modifiedbyuserid,
    modifiedbyuser,
    sheet,
    area,
    module,
    unit,
    core,
    description,
    insulation,
    insulationspecification,
    linenumber,
    loopnumber,
    pipelineid,
    material,
    materialidentifier,
    objecttype,
    pid,
    pressurerating,
    schedule,
    service,
    shortmaterialtype,
    specification,
    subobjecttype,
    subsystemname,
    systemname,
    terminationnumber,
    testpressure,
    testtype,
    voltage,
    insulationthickness,
    fromtag,
    totag,
    boresize,
    length,
    areadimension,
    volume,
    weight,
    constructionworkareaid,
    cwa,
    constructionworkpackageid,
    cwp,
    ismodelcomponent,
    systemdescription,
    subsystemdescription,
    status,
    pipespoolid,
    topelevation,
    bottomelevation,
    locationposition,
    materialuom,
    materialquantity,
    materialtype,
    materialcategory,
    materialdrawing,
    materialsource,
    drawings,
    trackingtag,
    hostcomponents,
    width,
    height,
    thickness,
    perimeter,
    temperature,
    componentidentifier,
    classification,
    maincomponent,
    engineeringrevision,
    cwatext,
    cwptext,
    fabricationstatusid,
    fabricationstatus,
    paintingspec,
    tracingspec,
    pressureequipmentdirective,
    shopweldcount,
    fieldweldcount,
    ewptext,
    engineeringworkpackageid,
    ewp,
    iwpcount,
    systemid,
    subsystemid,
    ismanual,
    componentbacklogtaskcount,
    ratecode,
    costcode,
    externallookup,
    sequencerank,
    splitparentid,
    keyquantity,
    keyquantityuom,
    splitallocatedquantity,
    splitremainingquantity,
    datemodified_ts,
    source_system_name,
    primary_key,
    is_current,
    eff_start_date,
    eff_end_date,
    cast(execution_date as DATE) as execution_date,
    CAST({{run_date}} as DATE) as model_created_date,
    CAST({{run_date}} as DATE) as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from {{ source('curated_o3', 'curated_construction_components') }}
where is_current = 1
{%- if execution_date_arg != "" %}
    and execution_date >= '{{ execution_date_arg }}'
{%- else %}
    {%- if is_incremental() %}
        and cast(execution_date as DATE) > (select MAX(CAST(execution_date) as DATE)   from {{ this }})
    {%- endif %}
{%- endif %}
   