{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = dbt.date_trunc("second", dbt.current_timestamp()) %}
{{
      config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_constraints/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["o3"]
        ) 
}} 
       
select
    {{ dbt_utils.generate_surrogate_key(['projectid','entityid','constraintid']) }} as constraint_key,
    CAST(entityid AS INT) AS entityid,
    CAST(entitytypeid AS INT) AS entitytypeid,
    entitytype,
    CAST(id AS INT) AS id,
    CAST(projectid AS INT) AS projectid,
    projectinfo,
    CAST(constrainttypeid AS INT) AS constrainttypeid,
    constrainttype,
    constraintid,
    cwpstatus,
    cwpdescription,
    CAST(cwpstatusid AS INT) AS cwpstatusid,
    constructionworkarea,
    constructiontype,
    CAST(actionentitytypeid AS INT) AS actionentitytypeid,
    CAST(entitycontractid AS INT) AS entitycontractid,
    entityname,
    CAST(statusid AS INT) AS statusid,
    status,
    statuscolor,
    CAST(priorityid AS INT) AS priorityid,
    priority,
    CAST(hardconstraint AS BOOLEAN) AS hardconstraint,
    companyid,
    company,
    category,
    "constraint" as _constraint,
    longname as constraintlongdescription,
    description as constraintdescription,
    entityplannedstartdate,
    CAST(countdown AS INT) AS countdown,
    editorroleids,
    CAST(sortorder AS INT) AS sortorder,
    CAST(workpackagestageid AS INT) AS workpackagestageid,
    workpackagestage,
    CAST(workpackagestagesortorder AS INT) AS workpackagestagesortorder,
    notes,
    CAST(constructionworkareaid AS INT) AS constructionworkareaid,
    CAST(disciplineid AS INT) AS disciplineid,
    discipline,
    disciplinedescription,
    CAST(purposeid AS INT) AS purposeid,
    purpose,
    CAST(zoneid AS INT) AS zoneid,
    zone,
    CAST(constructiontypeid AS INT) AS constructiontypeid,
    CAST(areaid AS INT) AS areaid,
    area,
    CAST(contractid AS INT) AS contractid,
    contract,
    CAST(planneruserid AS INT) AS planneruserid,
    planneruser,
    scheduleactivityid,
    CAST(unitid AS INT) AS unitid,
    unit,
    ewpestimatedhours,
    CAST(constructionworkpackageid AS INT) AS constructionworkpackageid,
    cwp as cwpsid,
    assignedtoroleid,
    assignedtorole,
    assignedtousergroupid,
    assignedtousergroup,
    CAST(assignedtouserid AS INT) AS assignedtouserid,
    assignedtouser,
    CAST(assignedbyuserid AS INT) AS assignedbyuserid,
    assignedbyuser,
    dateassigned,
    CAST(completedbyuserid AS INT) AS completedbyuserid,
    completedbyuser,
    CAST(datecompleted AS TIMESTAMP) AS datecompleted,
    CAST(iscomplete AS BOOLEAN) AS iscomplete,
    CAST(datedue AS TIMESTAMP) AS datedue,
    CAST(forecastdate AS TIMESTAMP) AS forecastdate,
    CAST(commentcount AS INT) AS commentcount,
    sourceid,
    source,
    sourcekey,
    sourceimportid,
    CAST(datemarkedneedsverification AS TIMESTAMP) AS datemarkedneedsverification,
    markedneedsverificationuserid,
    markedneedsverificationbyuser,
    CAST(datecreated AS TIMESTAMP) AS datecreated,
    CAST(createdbyuserid AS INT) AS createdbyuserid,
    createdbyuser,
    CAST(datemodified AS TIMESTAMP) AS datemodified,
    CAST(modifiedbyuserid AS INT) AS modifiedbyuserid,
    modifiedbyuser,
    CAST(dateduedateassigned AS TIMESTAMP) AS dateduedateassigned,
    CAST(daystoduedate AS INT) AS daystoduedate,
    CAST(urgencyid AS INT) AS urgencyid,
    CAST(lastcommentid AS INT) AS lastcommentid,
    lastcomment,
    CAST(lastcommentdate AS TIMESTAMP) AS lastcommentdate,
    lastcommentuser,
    urgency,
    CAST(defaultduedays AS INT) AS defaultduedays,
    CAST(keepduedatealignedwithpsd AS BOOLEAN) AS keepduedatealignedwithpsd,
    CAST(isautocreatedconstraint AS BOOLEAN) AS isautocreatedconstraint,
    parentactionid,
    parentaction,
    "float" as _float,
    CAST(constraintplannedstartdate AS TIMESTAMP) AS constraintplannedstartdate,
    completedbyuseremail,
    assignedtouseremail,
    assignedbyuseremail,
    CAST(releasedonentityid AS INT) AS releasedonentityid,
    referencenumber,
    attachmentannotationid,
    CAST(isrestrictedannotation AS BOOLEAN) AS isrestrictedannotation,
    CAST(isdeleted AS BOOLEAN) AS isdeleted,
    constrainttypedescription,
    CAST(assignedtoprojectteamid AS INT) AS assignedtoprojectteamid,
    assignedtoprojectteam,
    CAST(simpleentityid AS INT) AS simpleentityid,
    ewpnumber,
    CAST(ewpstatusid AS INT) AS ewpstatusid,
    ewpstatus,
    statusdate,
    ewpdescription,
    ewplongdescription,
    ewpexternallink,
    ewprevision,
    CAST(criticalpath AS BOOLEAN) AS criticalpath,
    CAST(plannedstartdate AS TIMESTAMP) AS plannedstartdate,
    CAST(actualstartdate AS TIMESTAMP) AS actualstartdate,
    CAST(plannedfinishdate AS TIMESTAMP) AS plannedfinishdate,
    CAST(actualfinishdate AS TIMESTAMP) AS actualfinishdate,
    labels,
    CAST(forecaststartdate AS TIMESTAMP) AS forecaststartdate,
    CAST(forecastfinishdate AS TIMESTAMP) AS forecastfinishdate,
    documentid,
    CAST(documentstatusid AS INT) AS documentstatusid,
    documentstatus,
    documentdescription,
    documentlongdescription,
    documentexternallink,
    documentrevision,
    documentownercompanyid,
    documentownercompany,
    CAST(documenttypeid AS INT) AS documenttypeid,
    documenttype,
    documentnumber,
    CAST(attachmentcount AS INT) AS attachmentcount,
    mechanicalequipmentid,
    mechanicalequipment,
    unitcode,
    areacode,
    CAST(wbsid AS INT) AS wbsid,
    wbs,
    CAST(contractgroupid AS INT) AS contractgroupid,
    contractgroup,
    criticalpathcategoryid,
    criticalpathcategory,
    masterentityid,
    releasedbyuserid,
    releasedbyuser,
    CAST(datereleased AS TIMESTAMP) AS datereleased,
    CAST(leadengineeruserid AS INT) AS leadengineeruserid,
    CAST(constructionrepresentativeuserid AS INT) AS constructionrepresentativeuserid,
    leadengineer,
    constructionrepresentative,
    CAST(iwpnumber AS INT) AS iwpsid,
    subcwp,
    deliveryteamid,
    deliveryteam,
    purposecategoryid,
    purposecategory,
    CAST(keyquantity AS FLOAT) AS keyquantity,
    unitofmeasureid,
    uom,
    CAST(datefirstconstraintcompleted AS TIMESTAMP) AS datefirstconstraintcompleted,
    CAST(datefirstconstraintcreated AS TIMESTAMP) AS datefirstconstraintcreated,
    CAST(datelastconstraintcreated AS TIMESTAMP) AS datelastconstraintcreated,
    plannedduration,
    CAST(criticalpath2 AS BOOLEAN) AS criticalpath2,
    CAST(plannedreleasedtoqualitydate AS TIMESTAMP) AS plannedreleasedtoqualitydate,
    CAST(actualreleasedtoqualitydate AS TIMESTAMP) AS actualreleasedtoqualitydate,
    CAST(calendarstartdate AS TIMESTAMP) AS calendarstartdate,
    CAST(calendarenddate AS TIMESTAMP) AS calendarenddate,
    CAST(projectphaseid AS INT) AS projectphaseid,
    projectphase,
    CAST(plannedreleasedate AS TIMESTAMP) AS plannedreleasedate,
    CAST(forecastreleasedate AS TIMESTAMP) AS forecastreleasedate,
    cwaareareleaseid,
    cwaarearelease,
    drawingnumber,
    CAST(drawingstatusid AS INT) AS drawingstatusid,
    drawingstatus,
    drawingdescription,
    longdescription,
    externallink,
    revision,
    CAST(revisiondate AS TIMESTAMP) AS revisiondate,
    CAST(drawingtypeid AS INT) AS drawingtypeid,
    drawingtype,
    CAST(dateissued AS TIMESTAMP) AS dateissued,
    filename,
    location,
    CAST(percentdocumented AS FLOAT) AS percentdocumented,
    CAST(percentdocumentedinclusive AS FLOAT) AS percentdocumentedinclusive,
    CAST(percentconstraintfree AS FLOAT) AS percentconstraintfree,
    CAST(percentdelayfree AS FLOAT) AS percentdelayfree,
    CAST(percentapproved AS FLOAT) AS percentapproved,
    CAST(percentdeveloped AS FLOAT) AS percentdeveloped,
    drawingcompanyid,
    drawingcompany,
    sheet,
    CAST(sourcedeleted AS BOOLEAN) AS sourcedeleted,
    sourceurn,
    modelguid,
    modelid,
    CAST(hasreleasedversion AS BOOLEAN) AS hasreleasedversion,
    CAST(hasworkingversion AS BOOLEAN) AS hasworkingversion,
    CAST(drawinghasrevisionattachment AS BOOLEAN) AS drawinghasrevisionattachment,
    CAST(drawingrevisionattachmentispdf AS BOOLEAN) AS drawingrevisionattachmentispdf,
    workingrevision,
    CAST(openannotationcount AS INT) AS openannotationcount,
    manufacturer,
    CAST(visibletoallusers AS BOOLEAN) AS visibletoallusers,
    rfi,
    CAST(rfistatusid AS INT) AS rfistatusid,
    rfidescription,
    rfistatus,
    CAST(companycontactuserid AS INT) AS companycontactuserid,
    companycontactuser,
    CAST(scheduleimpactid AS INT) AS scheduleimpactid,
    scheduleimpact,
    scheduleimpactcolor,
    CAST(costimpactid AS INT) AS costimpactid,
    costimpact,
    costimpactcolor,
    CAST(responsibleengineeruserid AS INT) AS responsibleengineeruserid,
    responsibleengineeruser,
    CAST(reasonid AS INT) AS reasonid,
    reason,
    resolutionid AS resolutionid,
    resolution,
    CAST(documentrevisionsrequired AS BOOLEAN) AS documentrevisionsrequired,
    CAST(rfitypeid AS INT) AS rfitypeid,
    rfitype,
    workimpactid,
    workimpact,
    workimpactcolor,
    disciplines,
    subject,
    CAST(openedbyuserid AS INT) AS openedbyuserid,
    openedbyuser,
    source_system_name,
    is_current,
    cast(execution_date as DATE) as execution_date,
    CAST({{run_date}} as DATE) as model_created_date,
    CAST({{run_date}} as DATE) as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from {{ source('curated_o3', 'curated_constraints') }}
where is_current = 1
{%- if execution_date_arg != "" %}
    and execution_date >= '{{ execution_date_arg }}'
{%- else %}
    {%- if is_incremental() %}
        and cast(execution_date as DATE) > (select max(execution_date)  from {{ this }})
    {%- endif %}
{%- endif %}