{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = dbt.date_trunc("second", dbt.current_timestamp()) %}

{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots='False', 
        custom_location=target.location ~ 'transformed_twps/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["o3"]
    ) 
}}
 
select
    {{ dbt_utils.generate_surrogate_key(['projectid','name']) }} as twps_key,
    id,
    projectid,
    projectinfo,
    entitytypeid,
    name,
    statusid,
    status,
    twpstatus,
    statusdate,
    description,
    longdescription,
    externallink,
    revision,
    unitid,
    unit,
    constructionworkareaid,
    constructionworkarea,
    areaid,
    area,
    disciplineid,
    discipline,
    purposeid,
    purpose,
    planneruserid,
    planneruser,
    drawingcount,
    budgetedhours,
    estimatedhours,
    twpsequencenumber,
    scheduleactivityid,
    plannedissuedate,
    actualissuedate,
    issuedatevariance,
    plannedstartdate,
    actualstartdate,
    startdatevariance,
    plannedfinishdate,
    actualfinishdate,
    plannedduration,
    actualduration,
    finishdatevariance,
    assemblystartdate,
    assemblyfinishdate,
    releasedtouserid,
    releasedtouser,
    datereleased,
    datedelivered,
    earnedhours,
    actualhours,
    forecastedhours,
    percentcomplete,
    percentdocumented,
    percentdocumentedinclusive,
    percentconstraintfree,
    percentdelayfree,
    percentapproved,
    percentdeveloped,
    datecreated,
    createdbyuserid,
    createdbyuser,
    datemodified,
    modifiedbyuserid,
    modifiedbyuser,
    isdeleted,
    sourcedeleted,
    dateconstraintfree,
    datedatacomplete,
    datecloseoutdatacomplete,
    datacompletenessstatus,
    contractid,
    contract,
    contractgroupid,
    contractgroup,
    criticalpath,
    baselinestartdate,
    baselinefinishdate,
    attachmentcount,
    unitcategoryid,
    unitcategory,
    labels,
    CAST(forecaststartdate AS DATE) as forecaststartdate,
    CAST(forecastfinishdate AS DATE) as forecastfinishdate,
    externallinkverified,
    externallinkverifiedbyuser,
    externallinkverifiedbyuserid,
    externallinkverifieddate,
    systemid,
    system,
    subsystemid,
    subsystem,
    CAST(calendarstartdate AS DATE) as calendarstartdate,
    CAST(calendarenddate AS DATE) as calendarenddate,
    statuscolor,
    openconstraintcount,
    totalconstraintcount,
    CAST(mechanicalcompletiondate AS DATE) as mechanicalcompletiondate,
    executionplanincluded,
    packagingstatusid,
    packagingstatus,
    notes,
    foremanuserid,
    foreman,
    generalforemanuserid,
    generalforeman,
    superintendentuserid,
    superintendent,
    percentiwpcomplete,
    CAST(plannedmechanicalcompletiondate AS DATE) as plannedmechanicalcompletiondate,
    CAST(forecastmechanicalcompletiondate AS DATE) as forecastmechanicalcompletiondate,
    CAST(actualmechanicalcompletiondate AS DATE) as actualmechanicalcompletiondate,
    CAST(plannedreadyforstartupdate AS DATE) as plannedreadyforstartupdate,
    CAST(forecastreadyforstartupdate AS DATE) as forecastreadyforstartupdate,
    CAST(actualreadyforstartupdate AS DATE) as actualreadyforstartupdate,
    forecastduration,
    criticalpathcategoryid,
    criticalpathcategory,
    parentgroup,
    prioritygroupid,
    prioritygroup,
    keyquantity,
    unitofmeasureid,
    uom,
    testpressure,
    operatingpressure,
    testmediumid,
    testmedium,
    testtypeid,
    testtype,
    volume,
    tasksneedingcalculationcount,
    qualitynotes,
    safetynotes,
    insulationtypeid,
    insulationtype,
    painttypeid,
    painttype,
    hydrotesttypeid,
    hydrotesttype,
    plotplancount,
    wbsid,
    wbs,
    plannerusercompany,
    generalforemanemail,
    superintendentemail,
    CAST(scheduledatadate AS DATE) as scheduledatadate,
    CAST(earlystartdate AS DATE) as earlystartdate,
    CAST(latestartdate AS DATE) as latestartdate,
    CAST(earlyfinishdate AS DATE) as earlyfinishdate,
    CAST(latefinishdate AS DATE) as latefinishdate,
    datemodified_ts,
    source_system_name,
    primary_key,
    is_current,
    eff_start_date,
    eff_end_date,
   cast(execution_date as DATE) as execution_date,
    CAST({{run_date}} as DATE) as model_created_date,
    CAST({{run_date}} as DATE) as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from {{ source('curated_o3', 'curated_twps') }}
where is_current = 1
{%- if execution_date_arg != "" %}
    and execution_date >= '{{ execution_date_arg }}'
{%- else %}
    {%- if is_incremental() %}
        and cast(execution_date as DATE) > (select max(execution_date) from {{ this }})
    {%- endif %}
{%- endif %}
     