{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = dbt.date_trunc("second", dbt.current_timestamp()) %}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots=False, 
        custom_location=target.location ~ 'transformed_fabrication_status/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        full_refresh=true,
        tags=["o3"]
        ) 
}}
 
  
select
    job_no as jobno,
    order_co as orderco,
    order_co_name as orderconame,
    order_no as orderno,
    spool_no as spoolno,
    drawing_ref as drawingref,
    piecemark as TagNumber,
    transmittal_no as transmittalno,
    transmittal_dt as transmittaldate,
    last_status_desc as laststatusdesc,
    header_size as headersize,
    CAST(material_type as INT) as materialtype,
    material_type_desc as materialtypedesc,
    priority,
    CAST(num_sort as INT) as numsort,
    fdi,
    weight,
    surface_area as surfacearea,
    bay_code as baycode,
    line_spec as linespec,
    laydown_area as laydownarea,
    alpha_sort as alphasort,
    column1 as cwasid,
    heat_treat as heattreat,
    bend_y_n as bendyn,
    hydro_y_n as hydroyn,
    hydro_l_list_r9 as hydrolist,
    sort_code as sortcode,
    paint_system as paintsystem,
    order_notes as ordernotes,
    no_of_welds as noofwelds,
    delivery_no as deliveryno,
    ship_to_name as shiptoname,
    revision,
    hold_code as holdcode,
    hold_code_desc as holdcodedesc,
    hold_dt as holddate,
    current_days_on_hold as currentdaysonhold,
    total_days_on_hold as totaldaysonhold,
    drawing_received_dt as drawingreceiveddate,
    engineering_released_dt as engineeringreleaseddate,
    edit_check_complete_dt as editcheckcompletedate,
    inventory_release_dt as inventoryreleasedate,
    material_handling_dt as materialhandlingdate,
    release_to_wip_dt as releasetowipdate,
    shop_short_return_to_mc_dt as shopshortreturntomcdate,
    cut_complete_dt as cutcompletedate,
    machining_dt as machiningdate,
    machining_complete_dt as machiningcompletedate,
    fit_complete_dt as fitcompletedate,
    final_fit_complete_dt as finalfitcompletedate,
    weld_complete_dt as weldcompletedate,
    square_up_dt as squareupdate,
    shop_repair_dt as shoprepairdate,
    checkout_complete_dt as checkoutcompletedate,
    hydro_cut_apart_dt as hydrocutapartdate,
    received_in_qc_dt as receivedinqcdate,
    nde_dt as ndedate,
    ready_to_stress_dt as readytostressdate,
    stress_complete_dt as stresscompletedate,
    xray_dt as xraydate,
    xray_repair_dt as xrayrepairdate,
    hydro_dt as hydrodate,
    hydro_complete_dt as hydrocompletedate,
    qc_review_dt as qcreviewdate,
    qc_complete_dt as qccompletedate,
    loaded_on_cart_dt as loadedoncartdate,
    id_blast_dt as idblastdate,
    coat_1_complete_dt as coat1completedate,
    coat_2_complete_dt as coat2completedate,
    coat_3_complete_dt as coat3completedate,
    paint_complete_dt as paintcompletedate,
    inspection_complete_dt as inspectioncompletedate,
    ready_to_ship_dt as readytoshipdate,
    loaded_on_truck_dt as loadedontruckdate,
    shipped_dt as shippeddate,
    voided_spool_dt as voidedspooldate,
    canceled_in_order_entry_dt as canceledinorderentrydate,
    ros,
    ssct,
    projectid AS projectid,
    cast(execution_date as DATE) as execution_date,
    CAST({{run_date}} as DATE) as model_created_date,
    CAST({{run_date}} as DATE) as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from {{ source('curated_o3', 'curated_fabrication_status') }}
{%- if execution_date_arg != "" %}
    and execution_date >= '{{ execution_date_arg }}'
{%- else %}
    {%- if is_incremental() %}
        and cast(execution_date as DATE) > (select max(execution_date)  from {{ this }})
    {%- endif %}
{%- endif %}
     