{%- set execution_date_arg = var("execution_date", "") %}
{%- set run_date = dbt.date_trunc("second", dbt.current_timestamp()) %}
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        file_format='iceberg',
        iceberg_expire_snapshots=False,
        custom_location=target.location ~ 'transformed_work_package_components/',
        table_properties={'write.target-file-size-bytes': '268435456'},
        on_schema_change='append_new_columns',
        tags=["o3"]
    )
}}
 
SELECT 
    id,
    entityid,
    entitytypename,
    projectid,
    entitytypeid,
    entitystatusid,
    entitystatus,
    entitystatuscolor,
    entityname,
    entitydescription,
    plannedstartdate,
    plannedfinishdate,
    actualstartdate,
    actualfinishdate,
    componenttype,
    tagnumber,
    lookupkey,
    constructioncomponentid,
    description,
    datecreated,
    createdbyuserid,
    createdbyuser,
    datemodified,
    modifiedbyuserid,
    modifiedbyuser,
    componentmissing,
    drawingid,
    drawing,
    associatedentityplannerid,
    isdeleted,
    purposeid,
    constraintrollupstatusid,
    constraintrollupstatus,
    constraintrollupstatuscolor,
    systempath,
    sheet,
    area,
    module,
    unit,
    core,
    insulation,
    insulationspecification,
    linenumber,
    loopnumber,
    pipelineid,
    material,
    materialidentifier,
    objecttype,
    pid,
    pressurerating,
    schedule,
    service,
    shortmaterialtype,
    specification,
    subobjecttype,
    subsystemname,
    systemname,
    terminationnumber,
    testpressure,
    testtype,
    voltage,
    insulationthickness,
    fromtag,
    totag,
    boresize,
    length,
    areadimension,
    volume,
    weight,
    systemdescription,
    subsystemdescription,
    status,
    topelevation,
    bottomelevation,
    locationposition,
    drawingtypeid,
    drawingtype,
    sourceurn,
    trackingtag,
    contractid,
    priority,
    fabricationstatusid,
    fabricationstatus,
    entitystatusstateid,
    autocreatedfromcc,
    externallookup,
    CAST(keyquantity as float) as keyquantity,
    keyquantityuom,
    sortorder,
    haspendingdatareview,
    datemodified_ts,
    source_system_name,
    primary_key,
    is_current,
    eff_start_date,
    eff_end_date,
    cast(execution_date as DATE) as execution_date,
    CAST({{run_date}} as DATE) as model_created_date,
    CAST({{run_date}} as DATE) as model_updated_date,
    {{ generate_load_id(model) }} as model_load_id
from {{ source('curated_o3', 'curated_work_package_components') }}
{% if execution_date_arg != "" %}
WHERE CAST(execution_date as DATE) >= '{{ execution_date_arg }}'
{% elif is_incremental() %}
WHERE CAST(execution_date as DATE) > (
    SELECT MAX(execution_date) FROM {{ this }}
)
{% endif %}