{{
     config(
         materialized = "table",
         tags=["project_control"]
         )

}}

select
    startminorperiod,
    cast(aed as float) as aed,
    cast(aoa as float) as aoa,
    cast(ars as float) as ars,
    cast(aud as float) as aud,
    cast(azn as float) as azn,
    cast(bgn as float) as bgn,
    cast(bhd as float) as bhd,
    cast(bnd as float) as bnd,
    cast(brl as float) as brl,
    cast(cad as float) as cad,
    cast(chf as float) as chf,
    cast(clp as float) as clp,
    cast(cny as float) as cny,
    cast(cop as float) as cop,
    cast(czk as float) as czk,
    cast(dkk as float) as dkk,
    cast(egp as float) as egp,
    cast(eur as float) as eur,
    cast(gbp as float) as gbp,
    cast(ghs as float) as ghs,
    cast(hkd as float) as hkd,
    cast(idr as float) as idr,
    cast(inr as float) as inr,
    cast(iqd as float) as iqd,
    cast(irr as float) as irr,
    cast(jmd as float) as jmd,
    cast(jod as float) as jod,
    cast(jpy as float) as jpy,
    cast(kes as float) as kes,
    cast(kgs as float) as kgs,
    cast(krw as float) as krw,
    cast(kwd as float) as kwd,
    cast(kzt as float) as kzt,
    cast(lyd as float) as lyd,
    cast(mad as float) as mad,
    cast(mnt as float) as mnt,
    cast(mxn as float) as mxn,
    cast(myr as float) as myr,
    cast(mzn as float) as mzn,
    cast(nad as float) as nad,
    cast(ngn as float) as ngn,
    cast(nok as float) as nok,
    cast(nzd as float) as nzd,
    cast(omr as float) as omr,
    cast(pen as float) as pen,
    cast(pgk as float) as pgk,
    cast(php as float) as php,
    cast(pln as float) as pln,
    cast(qar as float) as qar,
    cast(ron as float) as ron,
    cast(rub as float) as rub,
    cast(sar as float) as sar,
    cast(sek as float) as sek,
    cast(sgd as float) as sgd,
    cast(skk as float) as skk,
    cast(syp as float) as syp,
    cast(thb as float) as thb,
    cast(tnd as float) as tnd,
    cast(try as float) as try,
    cast(ttd as float) as ttd,
    cast(tzs as float) as tzs,
    cast(uah as float) as uah,
    cast(usd as float) as usd,
    cast(uyu as float) as uyu,
    cast(uzs as float) as uzs,
    cast(vef as float) as vef,
    cast(vnd as float) as vnd,
    cast(xaf as float) as xaf,
    cast(xpf as float) as xpf,
    cast(zar as float) as zar,
    cast(zmk as float) as zmk
from {{ source('Project_control_domain_integrated_model', 'transformed_ecosys_exchange_rates') }}