SourceSystemId: aconex
MetadataType: batch#aconex#${envn}#package_cacdcwpspf06v
is_active: true
aws_region: ${region}
Pattern: batch
smb_configuration: 
  host_url: 10.71.102.86
  host_port: 445
  secret_credentials: worley-datalake-sydney-dev-db-aconex-cacdcwpspf06v-bot-server 
  destination_bucket: ${raw_bucket} 
  destination_folder: document_control/aconex/package_report/raw
  kms_key_arn: ${iceberg_snapshot_key}
  file_archive_flag: false
  file_delete_flag: false
  archive_folder: ""
  source: 
    - SourcePath: /BOT_Reports
      pattern: .*PackageReport.*\.csv$
 